### ISSUE TITLE
Feature request: Add support for FastDL

### ISSUE THREAD

**Issue by Ferks-FK** [PufferPanel/PufferPanel#1007]
Add the next version of the panel, the possibility to synchronize FastDL with the game servers.

**Comment by Coolguy3289** [comment]
If I remember correctly, FastDL depends on a webserver doesn't it? If that's the case, I don't think you'd want Pufferpanel serving web content. Just my opinion on the matter assuming I'm correct, been a while since I've touched Source servers and FastDL

**Comment by john-f-chamberlain** [comment]
I agree that this isn't something that necessarily needs to be a modification to Puffer, I think a web server configuration for nginx/apache should be able to handle it.

I'll see what I can come up with.

**Comment by rugalservidores** [comment]
Yes, it can be done by configuring on a nginx/apache server.
The point is that there are other panels that you just click on a button, and all the personalized content is automatically compressed and uploaded to the FastDL of the given user.

**Comment by LordRalex** [comment]
The overall problem is that PufferPanel is *designed* to be generic. It doesn't have any way of handling such a feature by itself. Technically, this could be achieved with a Caddy template and a second "server" for them, which they need to run.

**Comment by john-f-chamberlain** [comment]
The following NGINX server block will achieve your desired goal.
It requires a "fastdl" folder to exist in the fileroot of your server, this can be created via SFTP or using the file manager on the server screen.

The URL, in the example below, would be `http://<ip>/fastdl/<serverid>/<filename>`
IE `http://127.0.0.1/fastdl/713d0900/test.zip`

```nginx
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        root /var/www/html;
        
        index index.html index.htm index.nginx-debian.html;
        
        server_name _;
        
        ## START FastDL PufferPanel
        location ~ "^/fastdl/(?<serverID>[a-f0-9]{8})/(.*)" {
                root /var/lib/pufferpanel/servers/$serverID/fastdl;
                autoindex on; 
                try_files /$2 /$2/ =404;
        }
        ## END FastDL PufferPanel
        
        location / {
                try_files $uri $uri/ =404;
        }
}
```
