### ISSUE TITLE
All Accounts Had Permissions Nuked

### ISSUE THREAD

**Issue by greysilly7** [PufferPanel/PufferPanel#1015]
Pufferpanel Version: PufferPanel 2.2.0 (e2a9deb0236380e57174650bfc3a4c23c306e614)
OS: Ubuntu 20.4

Issue: All account perms got nuked

Suspected Reason: Ok so my friend was managing their server I host for them, then they removed a user from accessing their server you know the normal, they went to remove another well the other one was special it had a UUID for its name (Look to Screenshots), then the error happened, at least that's what my friend said

![image](https://user-images.githubusercontent.com/65827291/114630871-7efe9c00-9c89-11eb-8c22-992587a962b6.png)

EDIT 1: More details
![image](https://user-images.githubusercontent.com/65827291/114631105-fe8c6b00-9c89-11eb-969b-952696eaab06.png)

**Comment by nepcore** [comment]
I tried to replicate it on my development environment, removing users both with a UUID as their name (those are not yet accepted invites) and "normal" users both on a servers user panel and on the users page and so far I have not seen any issues  
Could you try to find out the permissions all involved users had at the time both on the server and panel wide?

**Comment by greysilly7** [comment]
of the perms of all the users involved before the nuke were ``Edit Server Settings`` and ``See Servers`` after it was ``Blank``
