### ISSUE TITLE
[Suggestion] Add possibility change Server Name

### ISSUE THREAD

**Issue by DoctaEnkoda** [PufferPanel/PufferPanel#1016]
Hello,

I propose to add in the panel the means to change the name of the server in question. Since you compared to some panels which I will not mention do not allow you to sort the servers by their names, the way to rename them to see them better or just change the name to avoid getting confused or deleting and recreate an instance.

**Comment by Agent-010447** [comment]
also having the possibility to sort the instances by categories could be interesting. 🙂
