### ISSUE TITLE
Multiple Ports

### ISSUE THREAD

**Issue by Daggy1234** [PufferPanel/PufferPanel#1021]
Hey so I run a MC server standard with multiple plugins. I would like to expose certain ports for the plugins. How can I expose more than just the default 25565.

**Comment by InflamedSebi** [comment]
Pufferpanel does not expose any port on its own. The port settings in the templates only define the setting for the software, so for example minecraft does know, which ports to listen on.
Exposing ports usually has to be done on the firewalls and/or routers between your server and the Internet.

If your server is run by a hosting provider and uses a somewhat common linux distribution, you are probably looking for 'ufw allow 8080' or similar. But this has nothing to do with pufferpanel. This is just plain network/security management.

**Comment by Daggy1234** [comment]
yeah my bad
