### ISSUE TITLE
Disabling the file manager

### ISSUE THREAD

**Issue by b1sergiu** [PufferPanel/PufferPanel#1022]
Hey there, is there any way to hide/disable the front end file manager? I suppose it could be done with custom CSS but I'm not sure how to do that. Thanks

**Comment by thecmdradama** [comment]
As long as you are managing permissions on a server by server basis and not just granting the4 user administrator permissions, you can disable the "view and download files using the file manager" permission... Note: Also disable the "Allow access to files using SFTP" permission.

**Comment by b1sergiu** [comment]
Oh thank you, I've been looking for this option for an entire day and couldn't find it. The edit button for the assigned users is in the servers' settings apparently
