### ISSUE TITLE
Change user password from within command line (ubuntu)

### ISSUE THREAD

**Issue by LoganTheOverlord** [PufferPanel/PufferPanel#1031]
Hello there,

I would like to know how to change user password DIRECTLY. I know edit command, but it executes several menus and steps. I need it to happen in single command for hourly password changes. How can I achieve this?

**Comment by LordRalex** [comment]
Why are you doing hourly password changes..........

**Comment by LordRalex** [comment]
No.

Email is NOT a secure medium, so you actually make it less secure doing this.

Use SSH keys and fail2ban or something. Your reason for doing it via CLI is horribly wrong.

**Comment by LordRalex** [comment]
I'm not going to argue this point further. Use proper security. You don't need this type of feature.
