### ISSUE TITLE
[BUG] SFTP Across Nodes + unzip

### ISSUE THREAD

**Issue by tuxorials2** [PufferPanel/PufferPanel#1033]
I noticed, that if i want to put a world in, i have to put the zip file on the server via SFTP, and unzip it. That works good, but it isn't fast, since most FTP clients like filezilla don't unzip them on the node itself, but they unzip it locally and copy the files (at least AFAIK) which is painfully slow (Maybe because of sftp). i would suggest a feature to unzip the files within the web panel.

As i said before, i copy the file via SFTP, which works all right on the main node, but on the other 26 nodes i have, it DOESN'T work at all. I always have to get on the root user and hop into /var/lib/pufferpanel/servers/69dope to add files.. then i have to chown them and, overall, its a heck of a pain. My theory is that the users aren't synchronized between the nodes for security, but i would love to see the SFTP working.

Thanks in advanced,
Tuxorials

PD:
Screenshots:
![image](https://user-images.githubusercontent.com/84857461/119676246-ffdeb500-be3d-11eb-9a3b-43211c963d42.png)
![image](https://user-images.githubusercontent.com/84857461/119676989-9b702580-be3e-11eb-83e1-8cbf226ebc37.png)

**Comment by nepcore** [comment]
Archive handling features have already been implemented and will be in the next release

Your screenshot looks like the username might be malformatted, I see a `%` at the end of the input field that i doubt is part of the actual username

**Comment by tuxorials2** [comment]
It's because of the url encoding

**Comment by nepcore** [comment]
The username field of filezilla takes an unencoded username though, url encoding is not only not necessary, but actually gets in the way there

**Comment by tuxorials2** [comment]
I normally dont even use filezilla, i use nautilus most times, but for the purpose of the screenshot i used filezilla

**Comment by nepcore** [comment]
That doesn't change the fact that the username shouldn't be url encoded, a url encoded username isn't the same to sftp as its decoded version, that's the issue in the screenshot  
If you have issues (with filezilla or other applications) while not using a url encoded username and want help with that, please provide information on those issues
