### ISSUE TITLE
Adding Discord Bot as Puffer's Model

### ISSUE THREAD

**Issue by ICExFS** [PufferPanel/PufferPanel#1034]
I'm requesting this to ask to the Puffer Team to create a model for discord.py/discord.js so people can host their Discord Bot 
with Puffer

**Comment by LexFuturorum** [comment]
You can create your own templates using the built in template editor. Also consider sharing it with the community. ;)

**Comment by ICExFS** [comment]
I saw it but i'm kinda new in this so I don't really know how to do, I was asking if anyone already made it or if the staff could make it for everyone

**Comment by LexFuturorum** [comment]
https://discord.gg/v8dz49e feel free to join in
