### ISSUE TITLE
PufferPanel not removing servers from database

### ISSUE THREAD

**Issue by ReactiveSlime** [PufferPanel/PufferPanel#1050]
If I was to name a server for example as "Modded Minecraft" then delete it i am unable to make a new server on that node with the same name

Endpoint: get /api/servers/false?perms

Authorization Header: Bearer eyJhbGciO...

Stacktrace: Error: Request failed with status code 403
    at t.exports (https://*******.com/js/chunk-vendors.51fbe782.js:7:70541)
    at t.exports (https://*******.com/js/chunk-vendors.51fbe782.js:20:56255)
    at XMLHttpRequest.p.onreadystatechange ((https://*******.com/js/chunk-vendors.51fbe782.js:37:38845)
and the deleted servers show up on the server page for half a second before disappearing

I was on the discord server asking for help. [Heres the start of that conversation](https://discord.com/channels/291396338141364226/291396338141364226/878960471829520416)

**Comment by Romaindu35** [comment]
I have also problem when I deleting server with pufferpanel api, the server is deleting, but continue to be show during 1 second when I go on servers panel. After 1 second, the server despears of the list.

**Comment by Satanic-Spirit** [comment]
I can second the above findings. Running CentOS 7 and it appears that the servers are not deleting properly.

**Comment by SchokoShampoo** [comment]
I also had this error, after some investigating i found out, that the server files were deleted, but the entry in the database is still present, after deleting that manually, i could recreate a server with the same name

**Comment by Satanic-Spirit** [comment]
Just to provide some additional information. Once you delete a server you can't recreate a server with same name. You will end up getting the following error message. 

>Error Details
>Permission denied (403)
>
>Endpoint: get /api/servers/false?perms
>
>Authorization Header: Bearer eyJhbGciO...
>
>
>
>Stacktrace: 2d83/t.exports@http://xxx.xxx.x.xx:8080/js/chunk-vendors.51fbe782.js:7:70541
>467f/t.exports@http://xxx.xxx.x.xx:8080/js/chunk-vendors.51fbe782.js:20:56255
>b50d/t.exports/</p.onreadystatechange@http://xxx.xxx.x.xx:8080/js/chunk-vendors.51fbe782.js:37:38846

**Comment by ReactiveSlime** [comment]
@SchokoShampoo 
Can aslo confirm the servers remain in the database and the issue was fixed after editing the database

**Comment by LexFuturorum** [comment]
Its a known bug will be fixed in the next update.

**Comment by lbbrhzn** [comment]
how do you remove a server manually from the database?

> I also had this error, after some investigating i found out, that the server files were deleted, but the entry in the database is still present, after deleting that manually, i could recreate a server with the same name

I'm also seeing this issue. How do you remove a server manually from the database?

**Comment by SchokoShampoo** [comment]
@lbbrhzn what database are you using? mysql or sqlite?

**Comment by lbbrhzn** [comment]
sqlite, in a docker container

**Comment by LordRalex** [comment]
Resolved in v2.3.2
