### ISSUE TITLE
Cant start the panel

### ISSUE THREAD

**Issue by NuggetRP** [PufferPanel/PufferPanel#1055]
I installed pufferpanel from the installation documenation but i cant reach the webserver, and getting this weird error:
https://i.gyazo.com/b5244463459a8cc20a0a09d7b63b4c12.png

`[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

open email/emails.json: no such file or directory
goroutine 1 [running]:
runtime/debug.Stack(0xc000899690, 0x1096720, 0xc00038e570)
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/debug/stack.go:24 +0x9f
main.main.func1()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:32 +0x76
panic(0x1096720, 0xc00038e570)
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/panic.go:969 +0x1b9
github.com/pufferpanel/pufferpanel/v2/services.LoadEmailService()
        /home/runner/work/PufferPanel/PufferPanel/services/email.go:57 +0xb85
main.panel(0xc00053c3c0)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:129 +0x3c
main.internalRun(0x1bfd880, 0xc00038e290, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:89 +0x393
main.executeRun(0x1bfd880, 0xc00038e290, 0x1, 0x1)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:52 +0x50
github.com/spf13/cobra.(*Command).execute(0x1bfd880, 0xc00038e260, 0x1, 0x1, 0x1bfd880, 0xc00038e260)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1bfd380, 0x1, 0x1, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:60 +0x65
main.main()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:39 +0x8c`

Anyone have any clue on how to fix this?

**Comment by LordRalex** [comment]
Please use our Discord for assistance. https://discord.gg/v8dz49e
