### ISSUE TITLE
Pass host environment variables to the dockerfile

### ISSUE THREAD

**Issue by brickmonster** [PufferPanel/PufferPanel#1079]
Is there a way to pass environment variables from the host into the docker container? I would like to pass the host's HOSTNAME into the container for logging, and pufferpanel's ID for the server.

I tried using a pre-run hook to write a file to disk with a command but couldn't figure that out.

**Comment by LordRalex** [comment]
You can pass additional values to the server's environment variables by setting the "environmentVars" in the run portion of the server's JSON. However, this won't parse based on the machine itself, so they will have ti be hard-coded.

Example:
```json
{
  "run": {
    "environmentVars": {
      "HOST": "somehost",
      "SERVERID": "123456"
    }
   }
}
```
