### ISSUE TITLE
[Request] Variables don't work in docker Port Bindings

### ISSUE THREAD

**Issue by brickmonster** [PufferPanel/PufferPanel#1080]
I would like to specify the Outside Port and IP with a variable from pufferpanel for bridge mode.
`Invalid ip address: ${ip}`

**Comment by disconsented** [comment]
This is a known limitation, token replacement only works with fields that are strings

**Comment by brickmonster** [comment]
Are there any plans to handle this in the future? And if that's the problem then I would think that specifying the IP should work, although I only really care about the port for my case.

**Comment by brickmonster** [comment]
It turns out you can modify the json and it just works.
