### ISSUE TITLE
[Request] Conan Exiles

### ISSUE THREAD

**Issue by fmohican** [PufferPanel/PufferPanel#1083]
Hello,

Can you add support for Conan Exiles?

Thank you!

**Comment by ItsYuriil** [comment]
The Conan Exiles servers can not be used with linux, you could before with a docker, but not anymore, wine cannot handle the game no more

**Comment by gOOvER** [comment]
> The Conan Exiles servers can not be used with linux, you could before with a docker, but not anymore, wine cannot handle the game no more

thats not true. Conan works fine with Wine 10

**Comment by ItsYuriil** [comment]
> > The Conan Exiles servers can not be used with linux, you could before with a docker, but not anymore, wine cannot handle the game no more
> 
> thats not true. Conan works fine with Wine 10

Please, could you tell how did you downloaded Conan Exiles Dedicatef server and run it using wine? I've been trying to set it up for a really long time and I figured wine was outdated

**Comment by fmohican** [comment]
> > > The Conan Exiles servers can not be used with linux, you could before with a docker, but not anymore, wine cannot handle the game no more
> > 
> > 
> > thats not true. Conan works fine with Wine 10
> 
> Please, could you tell how did you downloaded Conan Exiles Dedicatef server and run it using wine? I've been trying to set it up for a really long time and I figured wine was outdated

by using steamcmd (linux native version not through wine).

The command will be like:
steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /home/user/conanexiles_de +login anonymous +app_update 443030 validate +quit

Then we have to run start.bat through wine
