### ISSUE TITLE
Invalid path to emails.json

### ISSUE THREAD

**Issue by JanSmrz** [PufferPanel/PufferPanel#1102]
Using pufferpanel-2.4.0-1.x86_64 from pufferpanel repo on Rocky Linux release 8.5 (Green Obsidian)

When starting pufferpanel it stops with an error:

```
[user@host ~]# pufferpanel run
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[ERROR] 2022/01/01 23:12:19 open email/emails.json: no such file or directory
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/debug/stack.go:24 +0x65
main.main.func1()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:35 +0x39
panic({0x10c8600, 0xc0008efb00})
        /opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x215
github.com/pufferpanel/pufferpanel/v2/services.LoadEmailService()
        /home/runner/work/PufferPanel/PufferPanel/services/email.go:57 +0x845
main.panel(0xc000103ba0)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:150 +0x30
main.internalRun(0xc000096600, 0xc000096720)
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:89 +0x29a
main.executeRun(0x1dcba60, {0x11ea977, 0x0, 0x0})
        /home/runner/work/PufferPanel/PufferPanel/cmd/run.go:54 +0x46
github.com/spf13/cobra.(*Command).execute(0x1dcba60, {0x277abf0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1dcb7e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.Execute()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:77 +0x5e
main.main()
        /home/runner/work/PufferPanel/PufferPanel/cmd/main.go:42 +0x76

```

It starts correctly when executed from directory /etc/pufferpanel.
I believe it is because the default path for email template (config.go line 63, "email/emails.json") is used and it is not prefixed with location of the config file (in this case "/etc/pufferpanel")

**Comment by disconsented** [comment]
Rocky Linux isn't supported, and Puffer should only ever be started via a service manager (SystemD/`systemctl`).

The "problem" is that Puffer expects to be run with specific files in its working directory which don't exist, hence the error.

**Comment by nepcore** [comment]
if you installed it using one of the .deb or .rpm packages you're supposed to use systemd to start it, not the `pufferpanel run` command

**Comment by JanSmrz** [comment]
Starting it as service (systemctl start pufferpanel) ended with the same error.  The same error was on Centos 8.5 and Centos Stream 8 as well. Something might have changed because on older Centos 8 (not sure what version) it used to work.

As a solution I modified config.json, I added 
```
    "email": {
      "templates": "/etc/pufferpanel/email/emails.json"

```
Overwriting the default values with full path allowed the program to run.

**Comment by JanSmrz** [comment]
Yes, you are right. I got distracted by various debug warnings, got mislead and started to use pufferpanel run.

**Comment by 4rchXceed** [comment]
I have the same issue but I don't have systemctl, how can I run pufferpanel?

**Comment by disconsented** [comment]
You're using an unsupported platform then. Also, just in case https://docs.pufferpanel.com/en/stable/faq.html#q-can-i-use-github-codespaces-i-need-help-with-github-codespaces.

**Comment by 4rchXceed** [comment]
I use it in docker, ARM64, it works... just last time I tried, but that's works now, I runs sudo apt-get install libterm-readline-gnu-perl and it works. 
Thanks
