### ISSUE TITLE
Can't access WebUI for PufferPanel V2

### ISSUE THREAD

**Issue by masonwjohnson** [PufferPanel/PufferPanel#1112]
Hello, I set up everything using the instructions on the website but when I try to connect using https://10.0.0.70:8080(10.0.0.70 is my server ip) it doesn't connect it says "This site can’t be reached 10.0.0.70 refused to connect." I would love some help, thanks.

I am using ubuntu server 20.04.3
I allowed access of the ports through firewall

I am new to this so if there is any other info you need just ask, thanks.

**Comment by nepcore** [comment]
HTTPS doesn't work with ips as you need a certificate for the host and those certificates are only given out for domains (not considering self-signed certs as browsers don't trust those), try using HTTP instead  
If that doesn't work, please consider coming to [our Discord](https://discord.gg/v8dz49e) and ask for help there as it's easier to help you and more people tend to be active there than there are here

**Comment by masonwjohnson** [comment]
> 

bro thank you so much that worked that seems like something I would have tried but I guess not, thanks a lot!
