### ISSUE TITLE
[Request] More Template import options

### ISSUE THREAD

**Issue by 2020Sanoj** [PufferPanel/PufferPanel#1115]
Hello, I wanted to ask if there could be in the future an option added, which makes it possible to use other template repositories than https://github.com/PufferPanel/templates. So that I could just insert the URL of the Template Repository, and then I could import all templates of another template repository.

And it would be great if it would be possible to add templates by uploading a JSON file and with this the panel creates the template.

Thanks

**Comment by LexFuturorum** [comment]
Adding other reporsitories besides this one would be kinda counterproductive because there is no guarantee for the templates to work not if they are really that what they claim to be, as for the upload you can select json in the upper right corner and copy the json in.

**Comment by 2020Sanoj** [comment]
For the JSON, I know, but the option to direct upload templates to the panel would be much faster.
And with the repository I meant that the user has the option to fully manual add them, so they should not be included with the panel.

**Comment by disconsented** [comment]
You can use the template editor in the UI to "upload" templates

**Comment by 2020Sanoj** [comment]
> You can use the template editor in the UI to "upload" templates

I know, but opening the file, copying the content, creating a template, opening the JSON tab from the template, removing the default content, pasting the new content, setting a name of the template which will be anyway get override by the template and saving, takes a bit more time than if it would be possible to just drag and drop the JSON over the templates tab from the panel, and it is imported. I know these steps are very fast done, but I would like it if this would be possible.
