### ISSUE TITLE
Suggestions for newer Versions

### ISSUE THREAD

**Issue by WaldperlachFabi** [PufferPanel/PufferPanel#1141]
- Adding option to create MySQL Databases in the menu of Servers
- Adding option to create Backups in the menu of Servers
- Adding option to create Tasks in the menu of Servers like creating a backup every day at 12:00 or restarting/stopping/starting
//🔴 - Adding option to install a Server software after creating it in the menu of Servers

This are the most important things in my opinion.

**Comment by LexFuturorum** [comment]
As pufferpanel isnt intended as a commercial panel i dont see any benefits in integrating database management . As for point 2 and 3 they are in the works and i have no clue what you mean by server software in the last portion.

**Comment by WaldperlachFabi** [comment]
Yeah i know that put i would personally be Interested in it, because i use a new database for every Plugin.

**Comment by nepcore** [comment]
Database management can be nice for non commercial users as well, that's not really the issue there, far more problematic for that would be that PufferPanel may be running on any kind of database and such a feature would then require a hard dependency on MySQL which we very intentionally moved away from as we moved to v2 as that complicates setup significantly  
Plus once creating and deleting databases exists, there will almost guaranteed be users that want to see full db management which is a major time invest that is just entirely out of scope for us

Point 3, as @LexFuturorum said, is already being worked on and by extension bring the ability to set up backups along

And like @LexFuturorum I too am very much not sure what you're trying to ask for in point 4

**Comment by WaldperlachFabi** [comment]
@nepcore Point 4: Like a menu where i can select spigot 1.18.2(or older versions) when i have 1.18.1 installed(and the same for forge, fabric, paper, …

**Comment by InflamedSebi** [comment]
The templates usually have a variable to set the version. Whenever you press the install button the version from this variable will be installed. That's the same procedure like updating to a never version.
But you can't switch your server from paper to forge. That would require too change the template and would not make sense at all.

**Comment by LexFuturorum** [comment]
Ohh ok that would be the version variable from the template just edit the variable type to options and add the versions you need, but it would make no sense for the default templates because they should be as futur proof as possible and don't have to be changes with every release.

**Comment by LordRalex** [comment]
Each suggestion should be it's own issue.
