### ISSUE TITLE
Add the abbility to switch between text editors

### ISSUE THREAD

**Issue by Aulluna** [PufferPanel/PufferPanel#1143]
Idk what it is called exactly , but I mean something like this  :
![image](https://user-images.githubusercontent.com/76559595/159220861-eebf1db8-d09d-493f-8ffd-987ed7676776.png)

I dont ofc need all of these text editors , just adding the basic one that are cable of reading .json .yaml .java .proprieties .

**Comment by LexFuturorum** [comment]
Press ctrl+,
