### ISSUE TITLE
 CloudNet V3 Template

### ISSUE THREAD

**Issue by WaldperlachFabi** [PufferPanel/PufferPanel#1162]
Hello, I made a template for CloudNet V3 maybe you would like to integrate it in any further versions!

{
  "name": "CloudNetV3",
  "display": "CloudNet V3",
  "type": "cloudnet",
  "install": [
    {
      "files": [
        "https://cloudnetservice.eu/cloudnet/version/release/3.4.3/CloudNet.zip"
      ],
      "type": "download"
    },
    {
      "commands": [
        "unzip CloudNet.zip",
        "chmod -R 777 ."
      ],
      "type": "command"
    }
  ],
  "run": {
    "stop": "exit",
    "command": "./start.sh",
    "workingDirectory": "",
    "pre": [],
    "post": [],
    "environmentVars": {}
  },
  "data": {},
  "environment": {
    "type": "standard"
  },
  "supportedEnvironments": [
    {
      "type": "standard"
    }
  ]
}

**Comment by disconsented** [comment]
Templates have their own repo at https://github.com/PufferPanel/templates/

**Comment by WaldperlachFabi** [comment]
Ok my fault!
