### ISSUE TITLE
Swagger on github pages

### ISSUE THREAD

**Issue by TekExplorer** [PufferPanel/PufferPanel#1165]
Hello! I am working on a mobile/desktop app for Pterodactyl Panel, and someone asked about supporting Puffer, but to even begin to consider that, I need Api docs to look over.

I'm told that docs are included in the program itself, but I don't want to set up Puffer just to reach those docs

Could you perhaps set up your workflows and repo to also build a github pages instance of the swagger docs?

_Also, where's the linux amd zip? I thought that kinda odd while looking around_

**Comment by LordRalex** [comment]
This is purely a release thing. However, the files are also all available here: https://github.com/PufferPanel/PufferPanel/actions/runs/2391066059

**Comment by LordRalex** [comment]
The swagger json and yaml files are now included with the release.
