### ISSUE TITLE
Web GUI does not prompt to re login

### ISSUE THREAD

**Issue by KlutzyBubbles** [PufferPanel/PufferPanel#1172]
If i load the web gui after i had a session before, no servers, nodes or any errors. Just infinite loading icons .

When i look into the web console i see a bunch of 401 errors, and the log file for pufferpanel says the token had expired 3 days ago.

Solution right now it to log out and log back in but i would have expected the web GUI to redirect me to the login page if the token is expired.

**Comment by nepcore** [comment]
This is a known issue and only happens in 2.5.0 due to a bug in a library we use, a fix for that is already there (part of 2483367d41794c3e5a16f81c64ba253afb20ac3f) and is just waiting to be released

**Comment by KlutzyBubbles** [comment]
Has this been fixed in 2.5.1?

**Comment by nepcore** [comment]
Yes, though you may need to clear your browser cache for it to take effect
