### ISSUE TITLE
[Feature] Some template improvements.

### ISSUE THREAD

**Issue by InflamedSebi** [PufferPanel/PufferPanel#1179]
Sometimes templates change internal names, since new variations pop up (fe Terraria vanilla, tshock, tmodloader, etc )
So, if you pull a template from github, you occasionally end up with duplicate entries in the list, since some internal names changed and the template gets added instead of overwritten.
Display names usually do not change, so you cannot differentiate between the old and the freshly pulled version during server creation and in the template area of the panel.
So you either start to compare templates internally or just delete them all and pull them again.

Some sort of versioning and appending it to the title would help a lot, to check if your template is up to date and which of the duplicates is the newer/older version.
Also I would love to see a repository link getting added to the template, which determines the location, it was pulled from, like "https://github.com/PufferPanel/templates/tree/v2/terraria-tshock" or even the direct link "https://raw.githubusercontent.com/PufferPanel/templates/v2/terraria-tshock/terraria-tshock.json"
This could ease the update process, since it would 
- allow for a button to pull updates for all existing templates, since they know where they came from
- allow to update a template even if the internal name changed
- allow for other sources/repositories of templates

I don't know, if this is a good idea, especially to allow 3rd party sources for templates, but I wanted to share it anyway.

**Comment by LordRalex** [comment]
The template structure is changing in v3.

Templates are moving to a repository system, and so are not going to be stored internally if you are only using the community-provided templates.

This will resolve this issue, as it will just always reference the latest templates we have.
