### ISSUE TITLE
Installation problems tmp/pufferd.sh

### ISSUE THREAD

**Issue by MoeSzyszlak** [PufferPanel/PufferPanel#1182]
Im using an oracle cloud compute instance:
VM.Standard.A1.Flex (ARM 24G CPU)
wich Canonical-Ubuntu-18.04-aarch64-2022.06.16-0 freshly installed and followed the installation process on PufferPanels [https://docs.pufferpanel.com/en/1.x/installing.html]  documentation 1:1

after configuring mysql and installing pufferd i receive this error:
`/tmp/pufferd.sh: line 169: ./pufferd: cannot execute binary file: Exec format error An error occurred while installing, halting...
Installation of pufferd failed locally, you will have to create a node manually on this machine if needed
`
I tried it 3 times with fresh Ubuntu 18.04 machines and once with Ubuntu 16.04

Im quite new to working with servers/linux so any help is appreciated.

Best regards,
Moe

**Comment by disconsented** [comment]
You're using outdated and unsupported documentation, follow the up-to-date instructions at https://docs.pufferpanel.com/en/latest/installing.html#starting-the-panel

**Comment by nepcore** [comment]
You're trying to install v1 which is quiteoutdated and doesn't support ARM architectures, [install v2 as described here](https://docs.pufferpanel.com/en/latest/installing.html) and it'll work

**Comment by MoeSzyszlak** [comment]
Thanks to both of you i will try once i get home again

**Comment by MoeSzyszlak** [comment]
The installation worked without problems now, only thing is i cant connect even though port 8080 and 5657 are open for TCP and UDP.

this is the result of `systemctl status pufferpanel
● pufferpanel.service - pufferpanel
     Loaded: loaded (/lib/systemd/system/pufferpanel.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-07-19 08:34:34 UTC; 8min ago
   Main PID: 11769 (pufferpanel)
      Tasks: 9 (limit: 28705)
     Memory: 21.7M
     CGroup: /system.slice/pufferpanel.service
             └─11769 /usr/sbin/pufferpanel run

Jul 19 08:34:34 server pufferpanel[11769]: [DEBUG] 2022/07/19 08:34:34 Email template registered: passwordReset
Jul 19 08:34:34 server pufferpanel[11769]: [DEBUG] 2022/07/19 08:34:34 Email template registered: emailChanged
Jul 19 08:34:34 server pufferpanel[11769]: [DEBUG] 2022/07/19 08:34:34 Email template registered: passwordChanged
Jul 19 08:34:34 server pufferpanel[11769]: [DEBUG] 2022/07/19 08:34:34 Email template registered: otpDisabled
Jul 19 08:34:34 server pufferpanel[11769]: [INFO] 2022/07/19 08:34:34 Adding local node
Jul 19 08:34:34 server pufferpanel[11769]: [INFO] 2022/07/19 08:34:34 Generating new key
Jul 19 08:34:34 server pufferpanel[11769]: [INFO] 2022/07/19 08:34:34 Loading existing key
Jul 19 08:34:34 server pufferpanel[11769]: [INFO] 2022/07/19 08:34:34 Started SFTP Server on 0.0.0.0:5657
Jul 19 08:34:34 server pufferpanel[11769]: [ERROR] 2022/07/19 08:34:34 No server directory found, creating
Jul 19 08:34:34 server pufferpanel[11769]: [INFO] 2022/07/19 08:34:34 Listening for HTTP requests on [::]:8080
`

**Comment by Jack-Stoller** [comment]
For me, I needed to add the ports to the ip table with this. I still don't have it working completely, but I can connect through the public ip now.

```
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 8080 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 8080 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 5657 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 5657 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 25565 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 25565 -j ACCEPT
sudo netfilter-persistent save
```
