### ISSUE TITLE
[BUG] Scrollbar reset

### ISSUE THREAD

**Issue by pierrbt** [PufferPanel/PufferPanel#1192]
Each time a row is added to the logs, the scrollbar resets and it go down. So if we want to see an error on startup, we have to wait the load finished, at condition no user connect in that time. Quite annoying. If you can resolve that.

**Comment by nepcore** [comment]
That is not a bug, but intentional, as otherwise the console would just stay where it loads, requiring you to scroll down yourself the entire time  
For that exact reason there is a pause button at the top of the console that pauses the console fetching new lines

**Comment by pierrbt** [comment]
Oh yeah I forgot that pause button, thank you
