### ISSUE TITLE
[FEATURE] Redesign Server UI Elements

### ISSUE THREAD

**Issue by tom-ricci** [PufferPanel/PufferPanel#1212]
**Is your feature request related to a problem? Please describe.**
I feel like the current design of the server management UI could be changed to look better.

**Describe the solution you'd like**
First of all, I think the information at the top can be moved to the bottom navigation:
![The server status, name, start, stop, kill, and install buttons all on the same bar as the bottom navigation.](https://user-images.githubusercontent.com/79022795/200876596-48a79f7a-c265-4102-aae7-dfdbac9522e3.png)
The console can expand to take up its whole container (obviously a place to send input would still be needed at the bottom of the container):
![The console taking up it's whole container](https://user-images.githubusercontent.com/79022795/200880688-74bba336-98b3-4145-9f68-d3e8fbdff8d4.png)
The other views could also maybe? be expanded, doing away with the margins and rounded-shadowed container they're in now.

This is a super rough concept and it still needs a lot of polishing, but I'd be happy to write an mvp for it based on this initial idea.

**Comment by nepcore** [comment]
Squishing everything into the bottom bar will quickly go sideways the moment you start looking at different screen sizes, PufferPanel is supposed to work on all devices, phone screens already have the pretty much unsolvable issue of a messy console, but that doesn't mean it needs to get worse and apply to everything, especially something as central as navigation elements  
Additionally, having information like server name and functions like start, stop, etc at the bottom is quite counterintuitive, I've seen too many cases of people not finding the bottom bar in general as to move everything there, the only reason it's where it is in the first place is that the combination of vuetify and past bad design choices didn't leave me many options other than just accepting that the tabs are completely out of the logical flow and hide at the bottom of the screen  
However, we are currently working on PufferPanel v3, one of the breaking changes prompting the major version bump being a full rewrite of the frontend code for multiple under the hood reasons which however also resulted in me fixing a lot of the bad design choices I made in the past and the bottom bar is one of those things, it'll move into a more logical position at the top of the server page, close to the server name and quick actions

Entirely removing margins and compacting the entire page to oblivion may be nice for some users, but it's not exactly a secret that margins exist for decently well researched reasons and as PufferPanel aims to make server hosting easy for _anyone_, not just powerusers, I don't see that as a good idea for the panels default look and feel  
As a theme however it's an entirely different story as that is both actively opted into and can easily be opted out of as well and while the current theming system in v2 has you fight with vuetifys aggressive as all hell default styles, probably making bigger changes like your suggestions a huge pain, v3 will also completely redo the theme system making writing themes a lot less of a mess as its default styles are a lot less agressive in general and can even be entirely taken out if you want to make your own design from the ground up

And to lessen the guessing as to where v3 is headed here's a somewhat recent screenshot of the server page, it might still change a bit, but is probably not going to move all that much anymore
![Screenshot 2022-11-09 at 16-59-02 PufferPanel](https://user-images.githubusercontent.com/12681731/200893354-45b4360f-81ad-44fe-ad8e-3ee770203feb.png)

**Comment by tom-ricci** [comment]
Good point. The v3 design is definitely a more intuitive design than what I suggested, I'll probably just wait until its released.
