### ISSUE TITLE
able to run steam server and Minecraft in one container (docker) 

### ISSUE THREAD

**Issue by progamer562** [PufferPanel/PufferPanel#1213]
Hello world i would like to know is it possible to run steam games like tf2 and run Minecraft in one container (docker) like I don't wana run separate containers

**Comment by LexFuturorum** [comment]
afaik thats not possible, but there is no need for containers at all they are no necessity.

**Comment by thecmdradama** [comment]
In the same container... No. Even if you could. You really don't want to do that.
Essentially you want your container and application to be a 1:1 relationship. So having both Minecraft and tf2 in the same container is not a grood ideas

**Comment by progamer562** [comment]
ok so if i do node thingy and copy the config to the steam node when i try to make a server it times out then logout sure I'm doing something wrong

**Comment by progamer562** [comment]
one by lime guide might help

**Comment by LordRalex** [comment]
Such things can be asked in our Discord
