### ISSUE TITLE
SFTP - can't connect to server - usage of weak SHA1

### ISSUE THREAD

**Issue by SzczurekYT** [PufferPanel/PufferPanel#1222]
**Describe the bug**
Hello
When I try to connect to the sftp server through the kde dolphin file manager I get this error.
kex error : no match for method server host key algo: server [ssh-rsa], client [ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-256,rsa-sha2-512]
I also tried using the sftp command and I get a very similar error:
Unable to negotiate with *ip* port 5657: no matching host key type found. Their offer: ssh-rsa
I did some searching and If I understand correctly the situation is:
Pufferpanel is using a deprecated sha-rsa public key algorithm which is using a weak SHA1 hasing algorithm that isn't secure now. OpenSSH deprecated this few years ago and now by default you can't connect to a server using this.

**To Reproduce**
1. Have a running pufferpanel instance with sftp redy.
2. Try connecting with the sftp command, it available both on windows and linux (macos probably too):
sftp -P 5657 "username@host"
You should get an error like mine.

**Expected behavior**
Connection should be succesfult.

**Solution**
Pufferpanel should switch to a stronger, modern standard, for example `rsa-sha2-256`.

**Versions**
 - Desktop OS: Nobara Linux 36 (basically it's a fedora 36 but with fixes for gamers)
 - Browser: Opera
 - Host OS: Ubuntu 22.04 LTS (Jammy Jellyfish)
 - Pufferpanel:  2.5.2

**Additional context**
Here are few articles about the OpenSSH deprecating the SHA1 algorithm.
https://ikarus.sg/rsa-is-not-dead/
https://levelup.gitconnected.com/demystifying-ssh-rsa-in-openssh-deprecation-notice-22feb1b52acd

Thanks

**Comment by nepcore** [comment]
RSA is only relevant to key based auth which PufferPanel currently doesn't support, only password auth is currently available for PufferPanels SFTP integration, therefore any connection attempts trying to authenticate using an SSH key are expected to fail

**Comment by nepcore** [comment]
If it was about the servers fingerprint I think we'd have noticed such issues, though I did definitely phrase that in a bad way, I should have made more clear that I meant RSA auth keys

**Comment by LordRalex** [comment]
It seems that while it's deprecated, it's not actually removed yet, and so it's just newer installs of servers entirely that may have the issue.

Fortunately, it should just be updating the /etc/pufferpanel/ keys with a different algorithm and it should just use those keys instead. 

But, I need to confirm how it works, and how to regenerate the new keys with a better key

**Comment by LordRalex** [comment]
To solve it if you run into this issue:
Stop the daemon/panel.
Run as root:
`ssh-keygen -t ed25519 -m pem -f /etc/pufferpanel/sftp.key`
Start daemon/panel
