### ISSUE TITLE
[BUG] The docker container's ports are not being binded on the NodeJS docker template

### ISSUE THREAD

**Issue by ArnavGupta30** [PufferPanel/PufferPanel#1228]
**Describe the bug**
I did configure it to use the server port of 3000 and project it at 6000 but it wont work. Also any port I assign on my project works so basically it allows all ports for some reason.

**To Reproduce**
Just make a docker discord.js server and put on a port binding

**Expected behavior**
All ports should be blocked and the source port should be forwarded to the target port (mentioned in config)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version idk
 
**Additional context**
Couldnt find help on discord

**Comment by LexFuturorum** [comment]
as the release notes in discord show there is no support for windows
