### ISSUE TITLE
Centos 8

### ISSUE THREAD

**Issue by duncosta** [PufferPanel/PufferPanel#1232]
Hi , how can i install this panel on centos 8 stream ?

**Comment by InflamedSebi** [comment]
See [this](https://docs.pufferpanel.com/en/2.x/installing.html#unsupported-os-version).

**Comment by duncosta** [comment]
I know it's not supported, but I thought there was a way to install it. I managed to install version 1.2.x, but it doesn't work as it should.

**Comment by nepcore** [comment]
There's an RPM tab there, that's what you need for cent os

**Comment by duncosta** [comment]
Give me link with that rpm for centos

**Comment by nepcore** [comment]
![Screenshot_20230218-211942-905.png](https://user-images.githubusercontent.com/12681731/219893200-7814cc30-79eb-45f1-b848-b134dbd6f96d.png)

That is from the link you have previously been given

**Comment by duncosta** [comment]
Thanks

**Comment by duncosta** [comment]
I installed on centos 8 using docker , and now works.

**Comment by Whitebrim** [comment]
> I installed on centos 8 using docker , and now works.

I tried to update it manually from 2.5.2 to 2.6.3, but it requires Libc.so.6(glibc_2.28)(64bit) that is v2.17 last official support for Centos 7

**Comment by Whitebrim** [comment]
> I installed on centos 8 using docker , and now works.

I think you can close this issue now
