### ISSUE TITLE
Remote servers do not delete

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#1236]
v2.6.5

Remote servers are not being deleted when button is being used.

Panel isn't associating the server on the DELETE call to the correct node, so it's not redirecting appropriately.

**Comment by nalvarez508** [comment]
This issue stemmed from a docker installation of pufferpanel:java (on both nodes). Digest `sha256:2e8d28b6241466701c99a12eb0b5c1c43abb8e0b94686b71117222f36e90fecc`

These nodes are not on the same network, they are two physical servers in two different locations. Delete functionality for servers and users (from server access) does not function as expected. **It should be noted that all other functionality has been fine - creating a server, managing, uploading files - all works.** Restarting a server has been hit or miss, but that's not what's important here.

This behavior is present in the following conditions:
- SSL enabled/disabled on both local/remote nodes
  - Hosting panel via nginx reverse proxy to an internal address, listening on 80
  - Likewise, listening on 443 with certificate
  - Remote: Proxied via 80, 443, as well as direct IP access from local with a separate public port
- SFTP port open/public and closed, did not think that made any difference either way.

Some environmental information:
- Panel, remote node in docker containers
- Outside port mapped to docker's 8080, config files generated from panel for remote node are also modified to reflect 8080 as the listening port
- Remote: Ubuntu Server 18.04.6 (docs mention lack of support, but- docker image is latest)
  - can upgrade this to further test
- Panel: Ubuntu Server 22.04.1

The following logs are from the local node (hosting the panel). 9.9.9.9 represents the admin/user accessing from some web location:
```[GIN] 2023/02/28 - 23:53:39 | 200 |    1.788867ms |   9.9.9.9 | GET      "/api/servers/cccd8c08/user"
[GIN] 2023/02/28 - 23:53:39 | 200 |    1.509394ms |   9.9.9.9 | GET      "/api/servers/cccd8c08/oauth2"
[GIN] 2023/02/28 - 23:53:39 | 200 |   86.718238ms |   9.9.9.9 | GET      "/proxy/daemon/server/cccd8c08/tasks"
[GIN] 2023/02/28 - 23:53:39 | 200 |   91.208556ms |   9.9.9.9 | GET      "/proxy/daemon/server/cccd8c08/data"
[DEBUG] 2023/02/28 23:53:39 Proxying connection to wss://remote.example.net:443/daemon/socket/cccd8c08
[GIN] 2023/02/28 - 23:53:39 | 200 |  121.638433ms |   9.9.9.9 | GET      "/proxy/daemon/server/cccd8c08"
[GIN] 2023/02/28 - 23:53:39 | 200 |  182.216686ms |   9.9.9.9 | GET      "/proxy/daemon/socket/cccd8c08"
[GIN] 2023/02/28 - 23:54:26 | 404 |     279.987µs |                 | DELETE   "/daemon/server/cccd8c08"
[ERROR] 2023/02/28 23:54:26 invalid status code response: 404 Not Found
[GIN] 2023/02/28 - 23:54:26 | 500 |    6.135652ms |   9.9.9.9 | DELETE   "/api/servers/cccd8c08"
[ERROR] 2023/02/28 23:54:26 Error proxying socket: websocket: close 1005 (no status)
[GIN] 2023/02/28 - 23:54:26 | 200 |    2.200041ms |   9.9.9.9 | GET      "/api/userSettings"
[GIN] 2023/02/28 - 23:54:27 | 200 |     8.10603ms |   9.9.9.9 | GET      "/api/servers?page=1&limit=10"
[GIN] 2023/02/28 - 23:54:27 | 200 |     2.55463ms |   9.9.9.9 | GET      "/daemon/server/75bd030f/status""
```

This comes from the remote node (notice it never receives any DELETE request). 1.1.1.1 represents the local (primary) node.:
```[GIN] 2023/02/28 - 23:53:38 | 200 |      40.687µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:53:38 | 200 |    4.631302ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/status"
[GIN] 2023/02/28 - 23:53:39 | 200 |      48.627µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:53:39 | 200 |      48.597µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:53:39 | 200 |    1.088949ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/tasks"
[GIN] 2023/02/28 - 23:53:39 | 200 |    1.149352ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/data"
[GIN] 2023/02/28 - 23:53:39 | 200 |      52.923µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:53:39 | 200 |     111.012µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:53:39 | 200 |    1.347524ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08"
[GIN] 2023/02/28 - 23:53:39 | 200 |    1.442332ms |  1.1.1.1 | GET      "/daemon/socket/cccd8c08"
[GIN] 2023/02/28 - 23:54:27 | 200 |       60.55µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:54:27 | 200 |    4.207877ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/status"
[GIN] 2023/02/28 - 23:54:57 | 200 |      93.786µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:54:57 | 200 |    4.693657ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/status"
[GIN] 2023/02/28 - 23:55:27 | 200 |      78.481µs |  1.1.1.1 | OPTIONS  "/daemon"
[GIN] 2023/02/28 - 23:55:27 | 200 |    3.512075ms |  9.9.9.9 | GET      "/daemon/server/cccd8c08/status"
```

**Comment by LordRalex** [comment]
Also seems to cause undefined to show up on the server list.
