### ISSUE TITLE
./srcds_run: 32: pushd: not found ./srcds_run: 35: popd: not found ERROR: Source engine binary './srcds_linux' not executable, exiting

### ISSUE THREAD

**Issue by SametKecici** [PufferPanel/PufferPanel#1237]
Starting process: ./srcds_run -game csgo -usercon -strictportbind -ip 0.0.0.0 -port 27015 +clientport 27016 +tv_port 27017 +map de_dust2 -maxplayers_override 24 +sv_setsteamaccount KEYSECRET -tickrate 64 +mapgroup <nil> +game_mode 0 +game_type 0 -net_port_try 1 -norestart
./srcds_run: 32: pushd: not found
./srcds_run: 35: popd: not found
ERROR: Source engine binary './srcds_linux' not executable, exiting
Wed Mar  1 01:11:07 UTC 2023: Server Failed
DAEMON
 Running post-execution steps

**Comment by SametKecici** [comment]
![image](https://user-images.githubusercontent.com/47273768/222022009-8a1711f5-7810-4252-add4-4bc5734e020c.png)

**Comment by LordRalex** [comment]
This is not a panel issue directly, but an issue with SRCDS. Please refer to the documentation and install any missing dependencies. 

https://docs.pufferpanel.com/en/latest/games/srcds/dependencies.html
