### ISSUE TITLE
Build from source guide

### ISSUE THREAD

**Issue by PolarianDev** [PufferPanel/PufferPanel#1244]
Can you please provide a guide on how to build your project from source, it seems you have two different applications in a single repository, the pufferpanel command line tool and the server.

Conventionally with go, it will attempt to build `main.go` but I do not see such a file existing.

I am not a go developer, I am a packager, so please provide the build procedure for this project :)

**Comment by LordRalex** [comment]
The build process is simple, but if you're not doing dev work, then you don't need the process anyways.

I do not approve of using our name for packages. If it's not coming from us, there is no reason to use our name.

And no, I don't care how Arch/AUR is. The only package that is needed is the binary package, which is under our control.

**Comment by PolarianDev** [comment]
@LordRalex Can you confirm that you would like the AUR package, pufferpanel-bin, deleted?

Secondly, you license the code under apache 2.0, under the license I am free to use the source code, for open source or closed source projects, I can fork and modify it at will, without the permission of the author, thus, unless you are going to start writing up a EULA to prohibit the build and redistribution of binaries which were not built by you, go ahead, but otherwise nothing legally stops me from building from source, and besides you are making it harder for people to contribute by not providing build instructions, not every project has the same build instructions.

Thirdly, pufferpanel does not seem like it is a registered trademark (I checked), so unless my searches missed it, anyone is free to use the name `pufferpanel`, apache does however protect trademarks, thus if it is registered trademark you do have a foot to stand on there.

Fourthly, if you are so against open source ways of doing things, like source installs, then why even bother open sourcing it? The source code is useless if you are not permitted to build it or fork it.

**Comment by PolarianDev** [comment]
You are confusing you know that, you quite clearly stated you do not want people building the source code because you want full control, and then you go back on it?

secondly, answer the original question:

> @LordRalex Can you confirm that you would like the AUR package, pufferpanel-bin, deleted?

**Comment by PolarianDev** [comment]
You stated you do not want pufferpanel-bin on the AUR, so do you want it deleted.

**Comment by LordRalex** [comment]
I never said such a thing. So, until you can full read what I said, I have no reason to answer.

I also never said no one can build it. I just said I am not going to tell you how, because you don't seem to really need it. As I can assume, you want to know so you can create a pufferpanel-git or pufferpanel-src for AUR.

So, this is now over.
