### ISSUE TITLE
User can't see "Server" tab if removed from a server

### ISSUE THREAD

**Issue by PolarianDev** [PufferPanel/PufferPanel#1248]
**Describe the bug**
When a user was looking at the panel, and the server was deleted (only had access to a single server), the server tab disappeared (despite the user having permission to "view server"), when i added them to a new server, the "servers" tab never reappeared, and despite the user being able to access the panel, they still can not access the "servers" tab.

_The user does have the "see servers" permission, they should be able to see the servers_

**To Reproduce**
1. Create a server, and add a user to it
2. While the user is viewing the panel, delete the server
3. Create a new server and add the user to it.

**Expected behavior**
When the new server is added to the user, they should be able to see the server tab, they can open a direct link to the server, but they can't see the "servers" panel and thus cant view the server they were allocated.

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - Browser Chrome
 - Version `unknown`

**Comment by PolarianDev** [comment]
I forgot to add, this can be fixed by the user logging out and logging back in again, however ideally they shouldn't need to do this.

**Comment by LordRalex** [comment]
I will need to know the version of the browser they are using, along with any plugins/extensions they are using.

I cannot replicate it with either Firefox or Chrome n 2.6.6.

- Created a new user on a fresh install (one admin, one with just View Servers)
- Created a new server using the admin account that the new user had access to (and only that user)
- Had user in a completely different browser logged in, could see new server
- Navigated into server to ensure user was even viewing the server as it was deleted
- Deleted server with the admin session

I still saw the Servers tab on the test account, even forcing refreshing and navigating around pages.

**Comment by PolarianDev** [comment]
I have passed this issue over to the user which encountered it, good luck!
