### ISSUE TITLE
Unable to create new servers

### ISSUE THREAD

**Issue by GiraffeSummer** [PufferPanel/PufferPanel#1266]
When I try to create a new (Minecraft) server I keep getting an `Unknown error`

I've tried different templates, but none seem to work, not even with default settings.

the extended message I get is:

```
Request failed with status code 400

Endpoint: post /api/servers

Authorization Header: Bearer ************

## config json


Stacktrace: Error: Request failed with status code 400
    at t.exports (***/js/chunk-vendors.e824d8cb.js:5:70543)
    at t.exports (***/js/chunk-vendors.e824d8cb.js:13:56672)
    at XMLHttpRequest.y (***/js/chunk-vendors.e824d8cb.js:27:45748)
```
and when Looking at the logs the only thing that seems strange is

```
[ERROR] 2023/07/18 16:11:29 Unexpected response from daemon: 400
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>openresty</center>
</body>
</html>
```

I can still edit and change existing servers but it seems like I just can't create any new ones.

I'm hoping I've provided enough information.

What could this issue be, and how could I solve it?

**Comment by LordRalex** [comment]
You are using HTTPS, which means there's additional changes you would have done. 
Can you share your web server config + any changes you made to PufferPanel's config and/or settings.

**Comment by GiraffeSummer** [comment]
Oh I found it, it somehow created a duplicate node, I deleted that one and it started working

Thanks anyway for your time
