### ISSUE TITLE
Update tutorial page

### ISSUE THREAD

**Issue by Blueeyestar** [PufferPanel/PufferPanel#1267]
It would be nice if there was also a page on https://docs.pufferpanel.com that describes in detail how to update buffer panels.
I myself have almost no idea of Linux. But thanks to the installation guide:
https://docs.pufferpanel.com/en/latest/installing.html
https://docs.pufferpanel.com/en/latest/installing-docker.html

I could do it myself without any knowledge.
But now I would have to update the version because I'm still on 2.5.2 and I can't find detailed instructions anywhere.

Up to version 1.2.0 there was even no more instructions:
https://docs.pufferpanel.com/en/1.x/upgrade.html

It would be nice if there were something like that so you can update it without being an IT expert.

**Comment by LexFuturorum** [comment]
thats standard package manager usage and going from your questions in the discord and the fairly simple answer provided by nep you just want a place to copy commands from.

so ill provide the even much simpler explanation
you have to run update and upgrade on the apt command

**Comment by Blueeyestar** [comment]
I think I know where the error is now....we have Ubunthu 18.04 and as I've read the latest update doesn't work at all on the version and I have to update Ubunthu first.

**Comment by Blueeyestar** [comment]
I have now updated the system to the latest Ubuntu 20.04. which command must now be entered so that it updates the buffer panel?

**Comment by Blueeyestar** [comment]
STEP 1: Have you installed this repository?

If not, run this installation script command:
curl -s https://packagecloud.io/install/repositories/pufferpanel/pufferpanel/script.deb.sh 

STEP 2: Install the package

sudo apt-get install pufferpanel=2.6.8
