### ISSUE TITLE
Lost access to my server

### ISSUE THREAD

**Issue by tycuu** [PufferPanel/PufferPanel#1271]
Hello. I have lost access to panel (password changed?) so I made a new user. Now I can login to Puffer Panel but the now the issue is different.
I can't see my Minecraft server (which is on) in the board ,,servers''. I see only this message ,,There are no servers you have access to''
but the user that im logged on has a admin group.
Do you have any ideas why my password to panel changed by self and now why I don't see my servers even as an ADMIN?
Greetings

**Comment by LexFuturorum** [comment]
if you're admin take a look at the users tab, youll most likely find out your other user isn't there anymore. if thats the case your database probably got deleted or you messed around in the files and yeeted it yourself.

**Comment by tycuu** [comment]
> if you're admin take a look at the users tab, youll most likely find out your other user isn't there anymore. if thats the case your database probably got deleted or you messed around in the files and yeeted it yourself.

i have a user tab full of the same users as before

**Comment by LexFuturorum** [comment]
take a look in /var/lib/pufferpanel/servers/ and take a look if the server still exists

**Comment by tycuu** [comment]
> take a look in /var/lib/pufferpanel/servers/ and take a look if the server still exists

server does exist because it is still on and we are playing still on it.- but i dont have access by pufferpanel and ftp
