### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by Melodycloudu** [PufferPanel/PufferPanel#1272]
the default node on my server points towards localhost by default should I change this? as nothing is connecting properly from outside connections.

**Comment by LexFuturorum** [comment]
Thats normal, your problem most likely lies in your firewall or port forwarding(most likely this).
this topic has been covered in the discord several times so ill suggest taking a look at it.

**Comment by Melodycloudu** [comment]
well all firewalls are disabled? but I am using the docker version of the puffer panel.. every other connection aside from game connections have been having this issue
