### ISSUE TITLE
Debian 12 "Bookworm"

### ISSUE THREAD

**Issue by Paderman** [PufferPanel/PufferPanel#1276]
Is not compatible with Debian 21 "Bookworm" 😢

> apt update
> Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
> Hit:2 http://deb.debian.org/debian bookworm InRelease
> Hit:3 http://nginx.org/packages/debian bookworm InRelease
> Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
> Hit:5 https://download.docker.com/linux/debian bookworm InRelease
> Ign:6 https://packagecloud.io/pufferpanel/pufferpanel/debian bookworm InRelease
> Err:7 https://packagecloud.io/pufferpanel/pufferpanel/debian bookworm Release
>   404  Not Found [IP: 2600:1f1c:2e5:6900:24f5:d925:2fc7:2e40 443]
> Reading package lists... Done
> E: The repository 'https://packagecloud.io/pufferpanel/pufferpanel/debian bookworm Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

> sudo apt-get install pufferpanel
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package pufferpanel

**Comment by disconsented** [comment]
Bookworm isn't listed as a supported distro version as per https://docs.pufferpanel.com/en/latest/installing.html

It'll likely be added in the next release.

Otherwise, https://docs.pufferpanel.com/en/latest/installing.html#unsupported-os-version
