### ISSUE TITLE
PufferPanel Suddenly Shuts Down on Ubuntu 22.04 LTS Container in Proxmox

### ISSUE THREAD

**Issue by Minionguyjpro** [PufferPanel/PufferPanel#1278]
Please use our [Discord](https://discord.gg/v8dz49e) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider joining our Discord and asking there before opening an issue here.
Please delete these 3 lines before submitting your issue.

**Describe the bug**
After some time, my Minecraft server suddenly shuts down. I saw PufferPanel also shutted down.

**To Reproduce**
1. Setup Proxmox
2. Run an Ubuntu 22.04 LTS container with LXC
3. Run PufferPanel and setup a Minecraft server
4. Play for some time
5. Shuts down at a random momennt

**Expected behavior**
It shouldn't shutdown and continue

**Screenshots**
![afbeelding](https://github.com/PufferPanel/PufferPanel/assets/66115754/300ed853-ea88-4e67-8f73-fcc2871077f8)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 118

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy A12
 - OS: [e.g. iOS8.1] Android 13
 - Browser [e.g. stock browser, safari] Stock browser, Samsung Internet Browser
 - Version [e.g. 22] Don't know

**Additional context**

**Comment by LordRalex** [comment]
oom-kill means your system is running out of memory and is killing things that are using it. This isn't an issue with the panel. You need to increase the memory allocated to your machine or lower the memory used by your servers.

**Comment by Minionguyjpro** [comment]
This is weird though, as Proxmox reports it uses only 1% memory and when I am in the server it only uses like 1/4th of the memory.

**Comment by LordRalex** [comment]
We do not control the oom-killer and it's a system-level thing. There's nothing we can really do about it. 

https://www.kernel.org/doc/gorman/html/understand/understand016.html these rules are kicked in, so if the oom-kill went into effect, then you did hit something that took all the memory. And the kernel chose to kill the panel.

**Comment by Minionguyjpro** [comment]
I did chose to sort of disable oom-killer, and change some memory
overcoming option. I also lowered the memory by 256MB RAM of the server, so
that would be available to the system.

Op do 19 okt. 2023 16:32 schreef Joshua Taylor ***@***.***>:

**Comment by gOOvER** [comment]
are you using lxc or kvm? i cant confirm this with kvm.

running Pufferpanel with Ubuntu 22.04 in a kvm vm on proxmox 8

**Comment by Minionguyjpro** [comment]
> are you using lxc or kvm? i cant confirm this with kvm.
> 
> running Pufferpanel with Ubuntu 22.04 in a kvm vm on proxmox 8

I run it in an LXC container, but sort of disabled it and changed some things.

**Comment by Minionguyjpro** [comment]
I had this issue again, but I hope it is now fixed now I increased the SWAP from 512MB to 2GB.
