### ISSUE TITLE
Sons of the forest template

### ISSUE THREAD

**Issue by SpeeDFireCZE** [PufferPanel/PufferPanel#1281]
Hi,
I am trying to make sons of the forest docker template in Pufferpanel, but I can't make it works. I have already running SoF server in docker but i wanted it to be in pufferpanel. For SoF docker image i used https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server whitch works awesome, but even with help of his configurations I can't make it work in Pufferpanel. 
Is there someone who already tried it and succeeded?
Or maybe if its posible to make template with github repository (docker run) or with docker compose command? 

Thank you.

**Comment by gOOvER** [comment]
is there any wine Image for Pufferpanel?

**Comment by SpeeDFireCZE** [comment]
> is there any wine Image for Pufferpanel?

Docker server (SoF) running/using wine and xvfb. Or how did you mean that ?

There is one more way to do that but I can't make it work as well : https://www.ionos.com/digitalguide/server/know-how/sons-of-the-forest-server-ubuntu-2204/

**Comment by gOOvER** [comment]
You cant use the image above. As  i know, you need special images for Pufferpanel

**Comment by nepcore** [comment]
@gOOvER That is incorrect, you can use any Docker image with PufferPanel, however their default run commands are ignored and always replaced with what is set as the run command in the PufferPanel template

@SpeeDFireCZE Could you please be a bit more explicit about what you tried and in what way it didn't work? It's rather hard to help you figure out the issue without knowing more than _something_ doesn't do what one specific user (you) expects, it could be anything from a misunderstanding to a bug to some unsupported detail and many other things in between

**Comment by gOOvER** [comment]
> @gOOvER That is incorrect, you can use any Docker image with PufferPanel, however their default run commands are ignored and always replaced with what is set as the run command in the PufferPanel template

is there any example for an image?

> @SpeeDFireCZE Could you please be a bit more explicit about what you tried and in what way it didn't work? It's rather hard to help you figure out the issue without knowing more than _something_ doesn't do what one specific user (you) expects, it could be anything from a misunderstanding to a bug to some unsupported detail and many other things in between

He want to run the image above in Pufferpanel :)

https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server

**Comment by nepcore** [comment]
> is there any example for an image?

As said, any Docker image is fine, they'll all work, they just aren't started with their default start command, they're pretty much used as nothing but dependency bundles

> He want to run the image above in Pufferpanel :)

Yes, I got that much, that doesn't tell me anything about how they tried to build their template though and by extension I can't tell where they might have made a wrong assumption or hit something that seems like a bug I'd need to investigate more closely etc

**Comment by SpeeDFireCZE** [comment]
> @SpeeDFireCZE Could you please be a bit more explicit about what you tried and in what way it didn't work? It's rather hard to help you figure out the issue without knowing more than _something_ doesn't do what one specific user (you) expects, it could be anything from a misunderstanding to a bug to some unsupported detail and many other things in between

Hi,
I tried to remake commands from steamcmdinstall.txt (https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/steamcmdinstall.txt): 
force_install_dir /sonsoftheforest
login anonymous
app_update 2465200 validate
quit
(this command works and app is installed but next commands dont).

and dockerfile (https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/Dockerfile) to puffer template. But it looks like when I add command to install which have to install some app (sudo apt install), that this command didnt do anything, it doesnt start install only gets to first apt install command and dont continue to next command (in puffer terminal). 

Next i try to start it using: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh

I think I only desn't 100% understand to template pattern, and i dont know which commands works and which don't in terminal.  

I will make some screens and send it in next answer.

**Comment by SpeeDFireCZE** [comment]
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/3aa39dd4-f64f-44d2-9618-f247bf955d7a)
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/d469d913-de2d-4926-895e-c3caedef3f78)
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/b3ef9ae9-5037-4542-b092-708ce644dfdd)

![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/2d9dc598-eb5a-4c19-b619-ad3a70c979f7)

![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/5c4b5338-979a-47c1-b2f3-55d19a69f170)


As you can see in third image, puffer execute only first command and skip next.

If i delete all commands in second command form then it start installing steam app:
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/1d542a07-8b5a-488e-ae4f-2e93cab01dd5)
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/dddba948-bfa4-47a8-96b1-6a7c780f8a4f)
It install it but cant start because sh script doesnt exist and doesnt have requirements (wine...)

If i add some commands in same commands form right behind install:
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/723ed3de-87aa-44d0-868f-4238ec8e479a)
it start install normaly:
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/678403d8-6deb-426a-b2e0-d8ea2126d615)
after steam app install it again execute only first command:
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/6eb2b259-986d-4d3f-879c-63745f72c3cd)

Its probably some fault on my side, as i said I am not really sure how to import docker run/ docker compose repositories to template. I didnt find any tutorial for it. 

thank you for your help guys.

**Comment by SpeeDFireCZE** [comment]
I think that I finally starting to understand to templates. But now when I get to start server over docker I have problem with permisions. 
![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/f6e73c47-87e4-4e54-b28d-39fc62c22479)
How can I escalate permisions to puffer? Adding puffer user to adm or sudo dont work.
Thanks

**Comment by gOOvER** [comment]
i would use a pure wine stable Image and let Pufferpanel Install the game

**Comment by SpeeDFireCZE** [comment]
> i would use a pure wine stable Image and let Pufferpanel Install the game

I dont know how did you mean it. I want it in docker and I cant install any aplication in created docker with template, puffer dont have rights as you can see in images. Or what was you idea, how did you mean it ?

**Comment by gOOvER** [comment]
I my eye's you CANT use the image you posted above. The image install all.

Use:
scottyhardy/docker-wine:stable

as image and build a template around that. BUT, you must download the Windows version from Steam, else it dont work

**Comment by SpeeDFireCZE** [comment]
> I my eye's you CANT use the image you posted above. The image install all.
> 
> Use: scottyhardy/docker-wine:stable
> 
> as image and build a template around that. BUT, you must download the Windows version from Steam, else it dont work

I dont have connected any display to server so i need to install xvbf but I am again stuck with premissions :/

**Comment by gOOvER** [comment]
> > I my eye's you CANT use the image you posted above. The image install all.
> > Use: scottyhardy/docker-wine:stable
> > as image and build a template around that. BUT, you must download the Windows version from Steam, else it dont work
> 
> I dont have connected any display to server so i need to install xvbf but I am again stuck with premissions :/

you dont need any display for the server.

**Comment by SpeeDFireCZE** [comment]
> > > I my eye's you CANT use the image you posted above. The image install all.
> > > Use: scottyhardy/docker-wine:stable
> > > as image and build a template around that. BUT, you must download the Windows version from Steam, else it dont work. Dont ask me why but you need it 
> > 
> > 
> > I dont have connected any display to server so i need to install xvbf but I am again stuck with premissions :/
> 
> you dont need any display for the server.

specificaly for SoF you need to have connected display or xvbf for fake display. In process of instalation it will fail on display if you dont. Dont ask me why but you need it, maybe on win server its not needed but on linux it is.

**Comment by gOOvER** [comment]
> > > > I my eye's you CANT use the image you posted above. The image install all.
> > > > Use: scottyhardy/docker-wine:stable
> > > > as image and build a template around that. BUT, you must download the Windows version from Steam, else it dont work. Dont ask me why but you need it
> > > 
> > > 
> > > I dont have connected any display to server so i need to install xvbf but I am again stuck with premissions :/
> > 
> > 
> > you dont need any display for the server.
> 
> specificaly for SoF you need to have connected display or xvbf for fake display. In process of instalation it will fail on display if you dont. Dont ask me why but you need it, maybe on win server its not needed but on linux it is.

no, thats wrong. You do not have a display with XVFB. I wrote an egg for Pterodactyl without XVFB

**Comment by nepcore** [comment]
> you dont need any display for the server.

I wouldn't be so sure about that, I've seen games do completely off the rocker stuff like exposing their console via telnet instead of the standard in/out streams, it wouldn't surprise me if someone managed to think that a server absolutely needs a UI, because *oh look, literally any distraction* what were we talking about?  
But I don't know for sure either way, just wouldn't be surprised by it

> Adding puffer user to adm or sudo dont work.

First of all, I'd ***strongly*** recommend undoing that, PufferPanel should not have access to `sudo` or similar  
Also, adding the user to any group won't show effect for dockerized servers as all install commands are run inside a container, therefore isolated from the host system, just like the run command  
Let alone that if you use the Docker image you linked you don't need to run anything noted in its Dockerfile, the Dockerfile is used by Docker to build the image, the resulting image already has those packages installed etc  

> Next i try to start it using: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh

That script is quite heavily hardcoded to use very specific paths in the container, so even if you got it the permissions it wants it would loose save data as PufferPanel removes containers when they're not needed as it expects that the save data lives in the directory it mounts the server files into, which that script doesn't care about

To make it work you'll probably have to take that script and more or less rewrite it as part of the PufferPanel template to get everything to go where it needs to

**Comment by gOOvER** [comment]
> > you dont need any display for the server.
> 
> I wouldn't be so sure about that, I've seen games do completely off the rocker stuff like exposing their console via telnet instead of the standard in/out streams, it wouldn't surprise me if someone managed to think that a server absolutely needs a UI, because _oh look, literally any distraction_ what were we talking about? But I don't know for sure either way, just wouldn't be surprised by it

believe me, i wrote allready an egg for ptero. No display is needed. The server runs fine in a wine stable env, without XVFB

**Comment by SpeeDFireCZE** [comment]
@gOOvER ![image](https://github.com/PufferPanel/PufferPanel/assets/142578797/60d99aa0-170c-48f8-b1f7-a9651fbc306a)

@nepcore and is there any way to use apt install in docker containers made by puffer ? Some way to get rights ?

**Comment by nepcore** [comment]
You don't need to, the image already has it all installed, the commands in the Dockerfile run as part of the image creation process, so if you can use the image the commands have been run already

**Comment by SpeeDFireCZE** [comment]
> You don't need to, the image already has it all installed, the commands in the Dockerfile run as part of the image creation process, so if you can use the image the commands have been run already

Ok thanks I didnt know that. so when i choose docker image it automaticaly install all aplications in that image and i need only to start it ? I dont need to use install, for docker then ?

**Comment by nepcore** [comment]
That is not what I said, a Dockerfile tells Docker what image to use as a starting point, Docker takes that base image and runs all the commands given in the Dockerfile, the result of that is the new image, that means that anything that Dockerfile asked for and anything already in its base image are available in the image without further setup, but e.g. game files usually need to be installed separately, so the install section of a template is still relevant

**Comment by gOOvER** [comment]
> That is not what I said, a Dockerfile tells Docker what image to use as a starting point, Docker takes that base image and runs all the commands given in the Dockerfile, the result of that is the new image, that means that anything that Dockerfile asked for and anything already in its base image are available in the image without further setup, but e.g. game files usually need to be installed separately, so the install section of a template is still relevant

A bit senseles to allow users to use every image;

**Comment by gOOvER** [comment]
> That is not what I said, a Dockerfile tells Docker what image to use as a starting point, Docker takes that base image and runs all the commands given in the Dockerfile, the result of that is the new image, that means that anything that Dockerfile asked for and anything already in its base image are available in the image without further setup, but e.g. game files usually need to be installed separately, so the install section of a template is still relevant

and contradicts what you had said.

Docker is the future in hosting and the pufferpanel team, if it wants to survive, should think about implementing it properly; especially in such a time where a canadian scammer, with Ptero no longer makes ;)

**Comment by nepcore** [comment]
> and contradicts what you had said.

How so? I said what is written in the Dockerfile doesn't need to be done in PufferPanel, everything installed there is already in the image once it's built, most Docker images do however not include the actual game files and instead download them when the container is started if they're not there, so the install section of a template is still relevant since PufferPanel ignores the images preconfigured start command and replaces that with what's in the template because PufferPanel uses Docker images pretty much as dependency bundles that support strong system isolation

---

> A bit senseles to allow users to use every image;

Docker images are meant to be build once, run on anywhere (so long as the CPU arch is supported by the image), there is no reasonable way to differentiate Docker images into different categories, though I don't see what for in the first place  
Since the Docker image a server uses can only be changed by an admin, an arbitrary user cannot use that as a way to run whatever they want (and if that's your concern, good luck with e.g. user provided Minecraft plugins/mods)

> Docker is the future in hosting and the pufferpanel team, if it wants to survive, should think about implementing it properly; especially in such a time where a canadian scammer, with Ptero no longer makes ;)

Docker is one of many approaches. LXC, Podman and friends don't exist for no reason and Docker isn't always flat out the right choice for everything (nothing ever is, use cases are always important to consider), so claiming it to be the only thing that needs to be supported is rather short sighted

But let's keep that, it being off topic here, elsewhere, feel free to talk about it on discord or open a separate issue

**Comment by SpeeDFireCZE** [comment]
I think i Give up for now. I can't make it work, when i pull  jammsen/sons-of-the-forest-dedicated-server I have problems with permissions, and when i pull scottyhardy/docker-wine:stable it has problem with xvfb which I cant install. Now I am trying it with FragSoc/steamcmd-wine-xvfb-docker  but cant make it work for now.

**Comment by gOOvER** [comment]
> I think i Give up for now. I can't make it work, when i pull  jammsen/sons-of-the-forest-dedicated-server I have problems with permissions, and when i pull scottyhardy/docker-wine:stable it has problem with xvfb which I cant install. Now I am trying it with FragSoc/steamcmd-wine-xvfb-docker  but cant make it work for now.

played around a bit with a Templates, but IT looks Like, Pufferpanel is not really designed to run Games with wine.
