### ISSUE TITLE
environment no data available

### ISSUE THREAD

**Issue by oogabrielgodoy** [PufferPanel/PufferPanel#1289]
Hello everyone,

I'm currently setting up a Minecraft server, and I've chosen to use PufferPanel to have a more visually appealing administration panel than just a terminal on my VPS.

However, I'm facing an issue that I can't resolve. While navigating the menu under Servers > (Clicking the button) + > Choosing my template (in my case, it's https://github.com/pufferpanel/templates/blob/v2.6/minecraft-paper/minecraft-paper.json), the "Environment" option shows the message "No data available." From what I've gathered, there should be two options: Docker or Default.

Does anyone have any ideas on how to solve this issue?

![Captura de tela 2023-11-27 064638](https://github.com/pufferpanel/pufferpanel/assets/110994759/ed333012-dd7d-44a3-ae0a-622f4cebed4e)

**Comment by LordRalex** [comment]
How did you install the panel?

**Comment by battlemag3** [comment]
> How did you install the panel?

Sorry for the bump, but facing the exact same issue. Installed using docker. Added example template from https://github.com/pufferpanel/templates/blob/v2.6/minecraft-forge/minecraft-forge-docker.json

**Comment by battlemag3** [comment]
Yeah, it seems I got it working, just had to set variable in the template to standard
