### ISSUE TITLE
Help, I find bug

### ISSUE THREAD

**Issue by MCPLAYER127272** [PufferPanel/PufferPanel#1295]
Please use our [Discord](https://discord.gg/v8dz49e) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider joining our Discord and asking there before opening an issue here.
Please delete these 3 lines before submitting your issue.

**Describe the bug**

**To Reproduce**
1. Go to 'Go to add server > use pattern > next > next'
2. Click on 'Create'
3. Scroll down to 'Nothing'
4. See error: Unknown Error. ![IMG_20240111_232453_023.jpg](https://github.com/pufferpanel/pufferpanel/assets/135996112/eaa03148-5e08-4693-8cef-f5a5b5f86f2d)

![IMG_20240111_232507_441.jpg](https://github.com/pufferpanel/pufferpanel/assets/135996112/ce854d50-924d-44b3-9668-a50254720f1a)

![IMG_20240111_232518_094.jpg](https://github.com/pufferpanel/pufferpanel/assets/135996112/664cb4e7-64c2-4e20-b4fe-f4fa2523827f)

Version OS Ubuntu 22.04
Nginx 1.18.0

Panel download with https://docs.pufferpanel.com/en/latest/installing.html

**Comment by LordRalex** [comment]
Please either open up a thread in Discussions or visit our Discord.
https://github.com/pufferpanel/pufferpanel/discussions
https://discord.com/invite/v8dz49e

Also, provide your logs - https://docs.pufferpanel.com/en/2.x/faq.html#q-where-are-my-logs
