### ISSUE TITLE
cannot access to pufferpanel server adress

### ISSUE THREAD

**Issue by WaspYarp** [PufferPanel/PufferPanel#1297]
**Describe the bug**
the conection to the minecraft server is not available, it says "no futher information", and when i wanna cheq the web does not load, and still not load, so i need to enter to the web for login in the panel, but the web is not loading. so i dont know why, because i was playing it like a year or a little less

pufferpanel panel web
http://144.22.36.95:8080

it cant, i dont know even how iut happens

**Expected behavior**
load the panel and can login to the server

Desktop
 - windows 11
 - opera gx

-used with oracle server

**Comment by LordRalex** [comment]
Please use our Discord, as this is not a panel issue.

**Comment by WaspYarp** [comment]
Sorry for bothering
