### ISSUE TITLE
Q: Authorize requests

### ISSUE THREAD

**Issue by AstralBaby** [PufferPanel/PufferPanel#1304]
I would like to perform requests from my NodeJS server, how would i validate the token? sorry for the question

**Comment by nepcore** [comment]
I don't see what this has to do with PufferPanel, you make requests from a js script the same way as always, PufferPanel doesn't mess with scripts or processes outside of running them as defined in the template used  
Same story goes for validating whatever token it is you're dealing with

Also, for support you're usually better off asking in our [Discord](https://discord.gg/v8dz49e) as there's more activity there and we mostly use issues for tracking things that need changes to PufferPanels code
