### ISSUE TITLE
Can't connect to pufferpanel via FileZilla

### ISSUE THREAD

**Issue by Neonyyy** [PufferPanel/PufferPanel#1316]
I'm trying to add a modpack to my server but when i try to connect via FileZilla it displays this:

Status:	Connecting to localhost:5657...
Status:	Using username "(The username in the SFTP Information tab in pufferpanel)"
Status:	Access denied 
Error:	Authentication failed.
Error:	Critical error: Could not connect to server

I used the correct password and used the username displayed in SFTP Information.

**Comment by pierrbt** [comment]
Send the FileZilla inputs you used @Neonyyy
