### ISSUE TITLE
Support for More JDK Distributions

### ISSUE THREAD

**Issue by Minionguyjpro** [PufferPanel/PufferPanel#1323]
**Is your feature request related to a problem? Please describe.**
Mostly not, but it could be for some people. Some people may want to use a custom JDK distribution with custom features, or want a JDK that can perform better (Oracle GraalVM (NOT GRAALVM Enterprise Edition or Community Edition) is known to be able to perform better than Temurin, though they're both good options)

**Describe the solution you'd like**
Add support to choose from a list of JDKs or use a custom download for a Java URL that's tar.gz and let the panel handle the rest. 

**Describe alternatives you've considered**
Manually copying a self downloaded JDK over. It works and I made symbolic links, but it's not ideal in case an update of the JDK is needed.

**Additional context**
N/A

**Comment by LordRalex** [comment]
This is where I will point to using Docker to run the servers.

There is a lot of concerns about things like binary naming, how to handle mixing, and so on. Docker is designed to handle this a lot smoother and isn't limited by what we do.

**Comment by Minionguyjpro** [comment]
> This is where I will point to using Docker to run the servers.
> 
> There is a lot of concerns about things like binary naming, how to handle mixing, and so on. Docker is designed to handle this a lot smoother and isn't limited by what we do.

I see, then maybe add support to choose a custom Docker JDK image for the Docker templates?

**Comment by LordRalex** [comment]
I consider it an edge case, and one that only advanced would use. You can override the image as an admin, so I don't see why we need to make it a drop down or anything.
