### ISSUE TITLE
Installing FTB Modpack

### ISSUE THREAD

**Issue by Robdragon1** [PufferPanel/PufferPanel#1324]
Hey, I'm trying to install FTB Skies on my Pufferpanel Server.
This is the template JSON I'm using:

{
"name": "undefined",
"display": "FTB - Forge 1.17+",
"type": "minecraft-java",
"install": [
{
"type": "javadl",
"version": "${javaversion}"
},
{
"files": [
"https://api.modpacks.ch/public/modpack/${modpack_id}/${modpack_version}/server/linux"
],
"type": "download"
},
{
"commands": [
"chmod u+x linux",
"./linux ${modpack_id} ${modpack_version} --auto --noscript"
],
"type": "command"
},
{
"target": "eula.txt",
"text": "eula=${eula}",
"type": "writefile"
},
{
"target": "server.properties",
"text": "server-ip=${ip}\nserver-port=${port}\nmotd=${motd}\n",
"type": "writefile"
}
],
"run": {
"stop": "stop",
"command": "java${javaversion} -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Dlog4j2.formatMsgNoLookups=true -Xmx${memory}M -Xms${memory}M -Dterminal.jline=false -Dterminal.ansi=true @libraries/net/minecraftforge/forge/${version}/unix_args.txt nogui",
"workingDirectory": "",
"pre": [],
"post": [],
"environmentVars": {}
},
"data": {
"eula": {
"type": "boolean",
"desc": "Do you (or the server owner) agree to the [Minecraft EULA?](https://account.mojang.com/documents/minecraft_eula)",
"display": "EULA Agreement",
"required": true,
"value": "true"
},
"ip": {
"type": "string",
"desc": "What IP to bind the server to",
"display": "IP",
"required": true,
"value": "0.0.0.0"
},
"javaversion": {
"type": "string",
"desc": "Version of Java to use",
"display": "Java Version",
"required": true,
"value": "21"
},
"memory": {
"type": "integer",
"desc": "How much memory in MB to allocate to the Java Heap",
"display": "Memory (MB)",
"required": true,
"value": "20200"
},
"modpack_id": {
"type": "integer",
"desc": "Get the modpack ID for your preffered modpack in the [Modpacklist](https://www.feed-the-beast.com/modpack).",
"display": "Modpack ID",
"required": true,
"value": "103",
"userEdit": true
},
"modpack_version": {
"type": "integer",
"desc": "Version ID from the versions tab of the selected modpack in the [Modpacklist](https://www.feed-the-beast.com/modpack).",
"display": "Modpack version ID",
"required": true,
"value": "11842",
"userEdit": true
},
"motd": {
"type": "string",
"desc": "This is the message that is displayed in the server list of the client, below the name. The MOTD does support [color and formatting codes](https://minecraft.wiki/w/Formatting_codes).",
"display": "MOTD message of the day",
"required": true,
"value": "A Minecraft Server hosted on PufferPanel"
},
"port": {
"type": "integer",
"desc": "What port to bind the server to",
"display": "Port",
"required": true,
"value": "25565"
},
"version": {
"type": "string",
"desc": "Version of Forge to install with no spaces (may be located [here](http://files.minecraftforge.net/)",
"display": "Version",
"required": true,
"value": "1.19.2-43.3.9"
}
},
"environment": {
"type": "standard"
},
"supportedEnvironments": [
{
"type": "standard"
}
],
"requirements": {
"os": "linux",
"arch": "arm64"
}
}

When I'm trying to install the server it's just not working.
https://private-user-images.githubusercontent.com/168991587/328040518-576f6333-f709-4bb3-ad56-47ff21355caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDE0MTUsIm5iZiI6MTcxNTAwMTExNSwicGF0aCI6Ii8xNjg5OTE1ODcvMzI4MDQwNTE4LTU3NmY2MzMzLWY3MDktNGJiMy1hZDU2LTQ3ZmYyMTM1NWNhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxMzExNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODEwZDI1YzU2YTgyYjc2Njg2NDNkMjYwMTBkYzNmOWE4ZDQ0YjAxZjBiOGM4MGMyMzNjNTlhNjEzN2QzZjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GJrhnYG2mLTjfHTPitOBtBIJ3dWiA4N8bCz09biKB5M

Where did I go wrong?

**Comment by LordRalex** [comment]
Use [Discord](https://discord.com/invite/v8dz49e) or [Discussions](https://github.com/pufferpanel/pufferpanel/discussions) for help with making templates.
