### ISSUE TITLE
Port not work

### ISSUE THREAD

**Issue by MASTERSAYYAN** [PufferPanel/PufferPanel#1325]
Please use our [Discord](https://discord.gg/v8dz49e) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider joining our Discord and asking there before opening an issue here.
Please delete these 3 lines before submitting your issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Port is not work plz solve this
![Screenshot_20240509-163534_Chrome](https://github.com/pufferpanel/pufferpanel/assets/169355120/6f74b860-067b-496d-879e-2b7ca76aa57b)

**Comment by nepcore** [comment]
There is no issue to be solved here, everything works as intended, if you were to actually read the text on your screen you'd be able to figure out that GitHubs ToS do not permit using codespaces to host game servers etc
