### ISSUE TITLE
can't use the database MySQL

### ISSUE THREAD

**Issue by Popov1998** [PufferPanel/PufferPanel#1340]
panel version 3.0.0-alpha.8, server OS Debian 11
![image](https://github.com/user-attachments/assets/6d8945a4-398e-4308-9991-76e3425c4cf4)

**Comment by Popov1998** [comment]
panel version 3.0.0-alpha.8, server OS Debian 11

**Comment by LordRalex** [comment]
What version of MySQL are you using

**Comment by Popov1998** [comment]
MySQL 8, database encoding utf8mb4

**Comment by LordRalex** [comment]
Is this a fresh install or an upgrade?

**Comment by Popov1998** [comment]
New installation, how to upgrade by the way?

**Comment by LordRalex** [comment]
Resolved with https://github.com/pufferpanel/pufferpanel/commit/c5264ac67ed2b10843218135a260c8e68df548ff
