### ISSUE TITLE
Error when deleting a server

### ISSUE THREAD

**Issue by elBelgg** [PufferPanel/PufferPanel#1346]
If you delete a server while its running, it gets deleted but it will also give an error.

![image](https://github.com/user-attachments/assets/fbd6893c-2032-4b0c-8367-10c4d4b848e8)

![image](https://github.com/user-attachments/assets/76c8ea45-64a7-4cc5-962d-59536c6bc30d)

**Comment by LordRalex** [comment]
Fixed via [d2094934afcf98e6859d85262a6598c17eecf6f3](https://github.com/pufferpanel/pufferpanel/commit/d2094934afcf98e6859d85262a6598c17eecf6f3)
