### ISSUE TITLE
[IMPROVEMENT] Remove "Expand" text

### ISSUE THREAD

**Issue by elBelgg** [PufferPanel/PufferPanel#1352]
I think that the "Expand" text when you collapse the menu does not make much sense because you will not see the text (only for the duration of the animation). I think it would be better to let it always show "Collapse"

https://github.com/user-attachments/assets/2f6c411a-26ce-4e8b-90b5-dde342c89b78

**Comment by nepcore** [comment]
For one it doesn't even show on your screen for more than half a second or so, so I don't see why it bothers you. Then there's the fact that screen readers exist and can in fact read that and generally it is a very helpful thing to not label interactable elements with an action they do not perform. Then there also is the fact that themes can do _a lot_, including doing things like e.g. make a collapsed sidebar grow out on hover in which case even the average user would see the full label which would give the implication that they may need to click that every time to re-collapse the sidebar when in fact that button would instead keep it from collapsing when the cursor exists the element until clicked again.
