### ISSUE TITLE
Can not create server on a node

### ISSUE THREAD

**Issue by washaqq** [PufferPanel/PufferPanel#1377]
### Discussed in https://github.com/pufferpanel/pufferpanel/discussions/1376

<div type='discussions-op-text'>

<sup>Originally posted by **washaqq** November 30, 2024</sup>
Hi,
i created a Master and a Node on docker;
![image](https://github.com/user-attachments/assets/da210e8f-0a21-4c89-bfbf-f39f6947fa95)

then i added node on Master with the settings below;
![image](https://github.com/user-attachments/assets/3d9afaaf-7333-4c8d-8b98-d378b213572d)

then uploaded the config file to node, but when i create a game server it gives me unknown error;
![image](https://github.com/user-attachments/assets/97e88f0a-04b8-4ecc-9d69-b324e3bda1ee)

i created a game server with same settings on Master and it works;
![image](https://github.com/user-attachments/assets/6c4ce9ab-f7b9-4ef0-b841-b77fde53f61f)
</div>

**Comment by LordRalex** [comment]
Nodes should not exist on the same machine as a panel. The panel is a node, and if configured correctly, will create docker containers for the servers. So making a node doesn't do anything.

**Comment by washaqq** [comment]
didn't get it, in the picture above master and node two different container, shouldn't be like this? what is the procedure of creating node, i thought create a node (container) first, then go to panel add new node by providing ip address and related info of the created node. Don't mind if nodes exist on same machine this is test env. i am testing and trying to learn it. i couldn't find the guide of creating nodes etc.
