### ISSUE TITLE
API Creation

### ISSUE THREAD

**Issue by DaneEveritt** [PufferPanel/PufferPanel#164]
API support is coming!

Check out http://docs.pufferpanel.com/en/latest/api/authentication/ to see what will be supported, and what is currently available.

The API is built on top of Klein Router which allows for easy path control, and the ability to extend the API to do so many different things that might not be standard. The API is also built to be easily extended, allowing you to run your own functions, including ones not included by default in the panel. Upload your own class files to the system, anywhere on the server, and simply call a single function to include your class and have access.

**Comment by puffrfish** [comment]
@nasonfish is going to help us get a little further with this highly requested feature. I'll work with him on the documentation as we go along. Keeping the 0.8.1 milestone as I believe it's achievable.

**Comment by nasonfish** [comment]
I don't think I'm going to be able to be the one that implements this at the moment, sorry.

[Here](https://github.com/PufferPanel/PufferPanel/commit/14e5f9fc13cb6ed68842b8d9381ec7d01e357478)'s some of the planned documentation we were planning on matching with the API; it's very REST-y, and it uses the method of each request well to make each API request make sense, if anyone is interested in taking this up.

Sorry guys.

**Comment by puffrfish** [comment]
That's okay @nasonfish. If anyone else is willing to work on the API please let me know.

**Comment by BlameDylan** [comment]
@puffrfish I might be able to help out some. While I'm pretty decent at PHP, which is what the API will be primarilty written in, I hope. By the way, is Dane Everitt on holiday? He hasn't had any Github activity within 20 days or so.

**Comment by LordRalex** [comment]
@BlameDylan yes

**Comment by puffrfish** [comment]
The (deleted) docs that nasonfish linked are a good starting place to see what we are talking about. Dane spends his summers AFK so @LordRalex and I are in charge for the summer.

**Comment by BlameDylan** [comment]
@puffrfish got it. I'll take a look when I get a chance.

**Comment by LordRalex** [comment]
Phase #1 of the API planning has started. Please provide any features that you want for the web api here: https://community.pufferpanel.com/topic/92-web-api-phase-1-featuresgoals/
