### ISSUE TITLE
Commercial use licensing issues

### ISSUE THREAD

**Issue by RunasSudo** [PufferPanel/PufferPanel#251]
PufferPanel is described as a ‘hosting panel created for companies who specialize in hosting Minecraft servers’, ‘designed for **large-scale commercial usage**’ (#88).

The GPL licence of PufferPanel allows for this, however PufferPanel itself depends on GSD for most of its functionality, which, as per its LICENSE, may **not be used ‘to provide or as part of commercial hosting** services using (owning, renting, subletting or leasing) in excess of 10 virtual or physical servers without written permission from the author.’

This is a significant hindrance to commercial use of PufferPanel, and makes PufferPanel's focus on commercial use somewhat misleading, currently.

**Comment by RunasSudo** [comment]
Is GSC still being worked on? It hasn't seen any activity since the initial two commits.

**Comment by koo04** [comment]
There has not been much needed to be done, yet. I am mostly waiting for those things to come up. I am working on re-developing the 'plugin' system to be more intuitive and cleaner, but it is not something worth pushing just yet.

**Comment by puffrfish** [comment]
Since we have committed to using an [entirely different daemon](https://github.com/PufferPanel/Scales) which does not have a restrictive license, I think this issue is resolved.
