### ISSUE TITLE
Multicraft Import functionality

### ISSUE THREAD

**Issue by godleydemon** [PufferPanel/PufferPanel#252]
Adding multicraft importing from database would greatly increase the user base using this panel. As it'd make it easier to switch over. Would probably requires reading the multicraft database and translating it all over to the way Puffer reads it's own database. Mostly, this is easy, it's just basically going through and grabbing the variable from the various tables and moving them to there new home. It's just going to be tedious. 

The other problem I could see, is how to translate over where Puffer will read the files and what user name it assigns those files. Possibly, could implement a function to automatically chown these files into the proper user associated to there file name. Since multicraft like's using "mc1, mc2, mc3, ect".

**Comment by DaneEveritt** [comment]
This is something that should be implemented as a non-core function. Once we have an API fully implemented it should be fairly easy for a user to build their own tool to perform these actions.
