### ISSUE TITLE
HTTPS support with WebSockets/AJAX

### ISSUE THREAD

**Issue by RunasSudo** [PufferPanel/PufferPanel#298]
When attempting to access Server Control options (turning the server on/off, accessing the server console, etc.) over HTTPS, PufferPanel attempts a WebSockets/AJAX connection over standard HTTP and is blocked by the browser.

Representative output from the Google Chrome console:
```[blocked] The page at 'https://example.com/node/index.php' was loaded over HTTPS, but ran insecure content from 'http://node.ip:8003/gameservers/0/off': this content should also be loaded over HTTPS.```
```[blocked] The page at 'https://example.com/node/index.php' was loaded over HTTPS, but ran insecure content from 'http://node.ip:8031/socket.io/?token=...&EIO=2&transport=polling&t=...': this content should also be loaded over HTTPS.```

**Comment by DaneEveritt** [comment]
Reference #415.

**Comment by DaneEveritt** [comment]
Reference https://github.com/PufferPanel/gsd/commit/03ba42344cd4de1f65b8a801d6012f260e472d9f

GSD now requires HTTPS connections, so it should work correctly over HTTP or HTTPS connections from the panel. PufferPanel still needs to update everything to send over HTTPS, so this will be closed when that happens.

**Comment by DaneEveritt** [comment]
Closed in https://github.com/PufferPanel/PufferPanel/commit/d48ebbf9057bfe562d4df3c807eac6fae7620712

If anyone has ideas for a cleaner implementation, please let me know.
