### ISSUE TITLE
HASHFILE not registering

### ISSUE THREAD

**Issue by Zlkva** [PufferPanel/PufferPanel#313]
I am attempting to set up PufferPanel and get to the step where you create your AES HASHFILE. I have created the file multiple times however every time I attempt to confirm via the browser "Continue" button it claims that the file does not exist and it gives me a new hash.

The error it gives me is "We were unable to access that file location."

I am installing this on Centos 6.5 with PHP 5.5

**Comment by willies952002** [comment]
I have been having the same issue with the system, possibly still and issue.

**Comment by Dylan3304** [comment]
I edited the /instal/do/hash.php and that worked for me.

**Comment by LordRalex** [comment]
Disable selinux

**Comment by LordRalex** [comment]
However, note this issue is irrelevant in the current installer and the new one

**Comment by Dylan3304** [comment]
I just put in outside of the /panel/ directory of PufferPanel. SeLinux is bae don't disable it :D.
