### ISSUE TITLE
Implement user suspension

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#344]
There are cases you would want a user to not have access but not have their account deleted. Example: late payments

**Comment by BlameDylan** [comment]
@SonarBeserk I'm going to add this in soon. Would you mind if the actual servers get suspended, rather than the user itself? (References #498)

**Comment by SonarBeserk** [comment]
#498 is desired to allow things like archiving servers where they exist but may not be booted. Where as this is for the purpose of locking all servers of a user until they pay up.
