### ISSUE TITLE
Implement a search feature for servers

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#362]
Currently only users have this search feature implemented but both have the same "Find X" naming scheme.

**Comment by BlameDylan** [comment]
Do you mean on the homepage? For end-users also? I would love to see this, and possibly pagination too.

**Comment by SonarBeserk** [comment]
It was intended to be so you can search in the admin panel for a specific server using several options. Based on how the find account page used to work.
