### ISSUE TITLE
SMTP Email Support

### ISSUE THREAD

**Issue by tankerkiller125** [PufferPanel/PufferPanel#366]
It would be nice to include SMTP as an email option. Understandable some of the libs supported have SMTP settings available but it would be nice to have it natively supported by PufferPanel

**Comment by LordRalex** [comment]
This appears to be how the mail() function already works:
"The PHP mail() function usually sends via a local mail server, typically fronted by a sendmail binary on Linux, BSD and OS X platforms".

Unless someone can validate that is not the case, then this support already exists.

**Comment by tankerkiller125** [comment]
Although that information is true it will cause the panel to use whatever
email that PHP is set to use and if PHP isn't already setup it will never
send at all.. Essentially relieying on the fact that PHP is setup correctly
(which isn't always the case) not to mention that mail coming from the
mail() function almost always goes to the spam folder.

**Comment by computerwizjared** [comment]
Well, PufferPanel has a setting for the mail() function email used, and it seems to work fine.

**Comment by DaneEveritt** [comment]
It shouldn't be our responsibility to make sure that someone sets up their email sending correctly, especially given that we offer multiple other ways of sending emails, all of which I prefer over `mail()`, and all of which offer free plans that should work for most personal setups.

**Comment by ET-Bent** [comment]
Sure but setting those up additionally to your existing postfix / dovecot setup for mail only for one web-service is too much hassle for almost nothing. Is it difficult to include basic smtp functionality? This would make it way easier for server owners to send mail that does not get rejected by gmail & co. without having to use another else wise unused service.
