### ISSUE TITLE
Master on/off switch for servers

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#374]
Add a master turn on and off button in the admin panel, this is usefull for maintance and it saves time because you would not have to go into each server controll to do so.

**Comment by Dylan3304** [comment]
Instead of wrapping our head around `for()` loops and such, why not add an ** * notation** in scales for `ACCESS-SERVER`? It would make things a lot easier and allow for multiple tasks to be run in servers, such as commands, etc.

**Comment by DaneEveritt** [comment]
Because then it is a massive pain to deal with status codes and errors, and the. You are just offloading the looping into Scalea. That's a really bad solution for something like this, and something like this isn't even that hard to do in PHP.

**Comment by Dylan3304** [comment]
Hopefully this gets added soon. I had to start like 20 servers manually yesterday 😑.

**Comment by Dylan3304** [comment]
**Drafted up a mockup,** doesn't have any functionality, but I'm just stating my opinion on where it should go.

![screen shot 2015-05-28 at 7 27 50 pm](https://cloud.githubusercontent.com/assets/2935060/7874063/107cac6a-0570-11e5-9ef1-285b17d9f704.png)

**Comment by LordRalex** [comment]
@BlameDylan I am a little concerned about where that is, because the focus of this issue was directed to the admin side of it, for shutting down an entire node really. Your image is targeting the user's servers, which is quite different.

**Comment by DaneEveritt** [comment]
Not going to be added.
