### ISSUE TITLE
Login throttles

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#384]
For extra security, we should have some form of login throttling where we lock access to login from ftp/panel on X failed logins (configurable).

**Comment by LordRalex** [comment]
FTP will not be handled on the panel side since that is going to be GSD related. The login throttle will only affect the auth page.

**Comment by DaneEveritt** [comment]
You can throttle FTP through the panel as well since authentication requests from GSD are passed to the panel.

**Comment by LordRalex** [comment]
That seems a little off that GSD does not do the FTP authentication, but if it is the panel doing it, then okay.

**Comment by DaneEveritt** [comment]
GSD passes the username and password to PufferPanel to check the credentials, and then continues if PufferPanel returns true.

**Comment by LordRalex** [comment]
Apparently resolved as added by the panel already:
https://github.com/PufferPanel/PufferPanel/blob/0.9.0-laravel/app/Http/Controllers/Auth/AuthController.php#L28
http://laravel.com/docs/5.1/authentication#authentication-throttling
