### ISSUE TITLE
Groupname not found

### ISSUE THREAD

**Issue by G1nux** [PufferPanel/PufferPanel#392]
What does this error mean?
![unbenannt](https://cloud.githubusercontent.com/assets/5270413/5580796/5feb8ab8-9050-11e4-9711-27fdd6653c8b.PNG)

It occurs when I try to start the server.

**Comment by G1nux** [comment]
I edited a few files of GSD myself and that caused the error. It wouldn't be supported by you anyway, so for me this Issue is closed :)

I uninstalled my changed version of GSD and reinstalled the original one. I will now start and test PufferPanel and GSD in every direction.

**Comment by DaneEveritt** [comment]
Sounds good. I looked at your changed files. The reason we don't use the same group for all of them is that theoretically any user in that group can access files belonging to someone else in that group.
