### ISSUE TITLE
Can't start the server after a crash

### ISSUE THREAD

**Issue by Lubenica** [PufferPanel/PufferPanel#395]
If the server crashes or if it can't start because eula.txt is not set to true it is not possible to start the server again, I have stop the node daemon and then start it again. Using the latest version of PufferPanel (latest commit). 
Thank you very much!

**Comment by Lubenica** [comment]
Created the folder. I will give you the results when the server crashes.

**Comment by Lubenica** [comment]
Here is my log: http://pastebin.com/rHpx00WN

**Comment by DaneEveritt** [comment]
Intersting, I don't see anything being thrown error wise. Your log is a bit confusing though. It looks like you were attempting to start `mc-srv125_tkgaq` multiple times in a row?

@koo04 could this be due to that loop condition we added to prevent constant restarts? Might not be declaring the server as off when we do that?

**Comment by koo04** [comment]
It sounds like it is trying to restart. I will take a look at why. Does the server have the needed jar file? That is the only thing I can think of right now, that would cause this look to happen.

**Comment by Lubenica** [comment]
Sure, here are file permissions inside the folder of that server:

http://i.imgur.com/50GBaeR.png
http://i.imgur.com/9PB7y5v.png

**Comment by koo04** [comment]
Ah, I don't see the jar file in there. Everything else looks fine.

**Comment by Lubenica** [comment]
It's there (spigot.jar).

**Comment by koo04** [comment]
That is in the root folder? IF it is, it needs to be renamed to 'server.jar'. At this moment. GSD is picky about that.

**Comment by Lubenica** [comment]
Yes, it is root folder. I mentioned in the panel that the server must run from "spigot.jar". Should I change it back to "server.jar"?

**Comment by koo04** [comment]
I would change it back and see what it does. If it still errors out, then we have another issue. I didn't notice that changing the jar file name in the panel actually worked now. I am going to see about replicating the problem.

**Comment by Lubenica** [comment]
Changed back, I will report back how it goes. 
Thanks for the help :)

**Comment by DaneEveritt** [comment]
The jar name should have no impact. if it was the problem it would have been throwing an error about the file not existing. This looks like it might be something with GSD not having the current power state stored correctly causing it to just skip the boot process.

**Comment by koo04** [comment]
I have to agree. I tried to replicate the problem. I can't get it to error out like that.
