### ISSUE TITLE
  Can only Access one server at a time. And adding a user that already exist to server wipes all users from Table

### ISSUE THREAD

**Issue by tankerkiller125** [PufferPanel/PufferPanel#397]
As the Discription states Its a major bug.
Steps to reproduce single server access:
- Login to PufferPanel
- Add a subuser to a server
- Have the user accept
- Add the same user to another server
- Have the user accept (they no longer have access to that other server now)

Steps to reproduce wiping of subuser:
- Add a subuser to a server
- Have them accept
- Repeat a couple times
- Add the one of the user a secound time
- Done all the subusers are wiped from that server now.

**Comment by worldmc** [comment]
Is there a update on this issue?

**Comment by DaneEveritt** [comment]
It has probably been fixed since I rewrote the entire sub-users system for 0.8.0. Will let you know once we have gotten around to really testing out 0.8.0

**Comment by tankerkiller125** [comment]
Good to know :)

**Comment by DaneEveritt** [comment]
Irrelevent due to subusers rewrite.
