### ISSUE TITLE
Add Kick / Ban / Timeban / Pardon - function to PP

### ISSUE THREAD

**Issue by G1nux** [PufferPanel/PufferPanel#399]
I would suggest to implement a Player-Management system, which you can use to Kick / Ban / Timeban and Pardon users on your Server.

**Comment by LordRalex** [comment]
This likely will be a module since it is Minecraft specific. One of the goals is to have the panel support more games, so it being a module would be logical.

**Comment by G1nux** [comment]
So as an owner you will be able to install modules, with wich you can extend pufferpanel and support multiple games?
That sounds awesome.
But where will I get this module? Is this already planned?

**Comment by LordRalex** [comment]
GSD is meant to work with multiple games, and we are trying to keep the panel as "flexible", so having more specific things would end up as modules. We have a repo for them, but none there yet as the panel is not done for it.

So pretty much yes. The panel can be extended is what we are going for.

**Comment by LordRalex** [comment]
Since this is a module desire, create an issue on https://github.com/PufferPanel/API-Modules for now

**Comment by DaneEveritt** [comment]
Ideally these would be modules, although still need to develop a plan for doing modules, I have some ideas floating around. The goal of modules is to allow them to hook into page templates and run their code, or show buttons that link to their code or what not.
