### ISSUE TITLE
Can't start the server after I stop it

### ISSUE THREAD

**Issue by Lubenica** [PufferPanel/PufferPanel#403]
I can't start the server after I stop it. When I stop it, the server correctly stops but the panel still thinks that the server is running (green dot). And then, when I click start button, nothing happens.

**Comment by DaneEveritt** [comment]
Is anything logged by GSD?

**Comment by Lubenica** [comment]
Just that: http://i.imgur.com/eEzzDCY.png ...

**Comment by DaneEveritt** [comment]
What version of GSD?

**Comment by Lubenica** [comment]
0.3.0

**Comment by DaneEveritt** [comment]
Ah, you are on an extremely outdated GSD version. What version of the panel are you running?

**Comment by Lubenica** [comment]
0.7.6.1 Beta (ref: refs/heads/master2) (sha: b0aa4875)

**Comment by DaneEveritt** [comment]
You are running an unsupported version of PufferPanel judging by the version information you have given. The current version should have a SHA of `23ce687`, and the current GSD version is `0.1.4`.

Following the upgrader instructions should have gotten this on the right version, not sure if you followed some other method, or wanted to use master. Either way, if you have already run the upgrader it isn't really possible to run it again without encountering some serious problems.

Have you already run the installer?

**Comment by Lubenica** [comment]
I installed the supported version of PufferPanel now. Will see how it works now.
Thanky!

**Comment by Lubenica** [comment]
Now when I enter /restart command ingame, the server could not be started and I get this message: 
http://i.imgur.com/s06ZpyM.png

**Comment by DaneEveritt** [comment]
This probably occurs because GSD does not realize that the game is handling the restart, so it sees the server being offline when it should still be on, and thinks it has crashed. Why it fails to restart, I do not know. Using the restart button in the panel should prevent this from occuring.

**Comment by DaneEveritt** [comment]
I can't seem to replicate this issue anymore, so I think we fixed it in GSD.
