### ISSUE TITLE
Allow ability to rename servers

### ISSUE THREAD

**Issue by Sorgrum** [PufferPanel/PufferPanel#405]
Pretty simple request. The ability to rename server that have already been created.

**Comment by LordRalex** [comment]
Added this to the 0.8.1 milestone, since it should be simple to do, but give us less to make sure 0.8.0 has.

**Comment by DaneEveritt** [comment]
Is this not currently a feature in `0.7.6.1`? I'm pretty sure I had already added this, and the code seems to show that as well.

**Comment by LordRalex** [comment]
Hmm, my instance shows this is an admin feature, which is what makes sense.

**Comment by Sorgrum** [comment]
Sorry about that. I didn't realize that each column in the Admin panel went to a different section.
