### ISSUE TITLE
Allow One-Click gisting of logs

### ISSUE THREAD

**Issue by DaneEveritt** [PufferPanel/PufferPanel#406]
It would be beneficial for users to be able to click a button in the file manager and automatically create a gist file of their error logs. Just a nice user feature that wouldn't be very hard to implement.

**Comment by SonarBeserk** [comment]
At the same time it is a very convenient way to accidentally leak information like ips and such so i would be careful.

**Comment by sysr-q** [comment]
@SonarBeserk If you don't care about leaking usernames (which, to most extents are "public" in Minecraft), you can run the log through some selection of filters.
Remove stuff that looks like an IP address, for example, before it gets sent to a (private, hopefully) gist.

**Comment by LordRalex** [comment]
Will not be implementing this, as there is little need for now. Maybe in the future we look at gisting the server logs, but it's not really a feature that is needed.
