### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by thetruestarr1337** [PufferPanel/PufferPanel#407]
Hello and thanks for such a nice tool :)

I followed the instructions, but now i have a problem :(

Im using Ubuntu Server 64bit
Here:
root@f435:~# cd /srv/gsd
root@f435:/srv/gsd# npm install
npm WARN package.json trim@0.0.1 No repository field.
|
> userid@0.1.1 install /srv/gsd/node_modules/userid
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/userid
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
/
> pty.js@0.2.4 install /srv/gsd/node_modules/pty.js
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> usage@0.5.0 install /srv/gsd/node_modules/usage
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/usage
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! userid@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the userid@0.1.1 install script.
npm ERR! This is most likely a problem with the userid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls userid
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
root@f435:/srv/gsd# clear
root@f435:/srv/gsd# npm install
npm WARN package.json trim@0.0.1 No repository field.
\
> userid@0.1.1 install /srv/gsd/node_modules/userid
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/userid
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> pty.js@0.2.4 install /srv/gsd/node_modules/pty.js
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/pty.js
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

> usage@0.5.0 install /srv/gsd/node_modules/usage
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               3:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:4                                                                               6:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:1                                                                               6
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd /srv/gsd/node_modules/usage
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! userid@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the userid@0.1.1 install script.
npm ERR! This is most likely a problem with the userid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls userid
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by DaneEveritt** [comment]
`gyp ERR! stack Error: not found: make`

You need to install `make` (and probably `g++`) on your server.
