### ISSUE TITLE
Panel slows down after keeping it in background

### ISSUE THREAD

**Issue by Sorgrum** [PufferPanel/PufferPanel#409]
I normally keep the panel open in the background, and after a while (around an hour or two) the panel seems to slow down for around twenty seconds before it speeds back up or I refresh the page.

**Comment by Sorgrum** [comment]
I recently noticed an odd behavior where when switching to the tab that has PufferPanel running, it doesn't effectively freezes the browser until it has caught up with the server logs. Maybe the ability to do that in the background at all times would help with the slowdown.

**Comment by DaneEveritt** [comment]
I think it is the browser preventing that, not the panel itself.

**Comment by drtweety** [comment]
Must be something to do with the ajax updates consuming memory

**Comment by SonarBeserk** [comment]
Im not sure there is much to be done about this really. Solutions as far as i can tell is simply dont leave it open that long. Otherwise you might start to cause issues for someone watching console for a bit, how do you differentiate between watching console and leaving the console in the background?

**Comment by Sorgrum** [comment]
I'd say watching the console would be keeping it in the active window and leaving it in the background would be having the console page open and running but not in the focused tab/window.

**Comment by SonarBeserk** [comment]
The point was how can you tell that server side?

**Comment by Sorgrum** [comment]
Oh, I was thinking the problem lied in one of the scripts that gets slowed down after a while. It seems to me that every time I change the focus onto the page that the panel has to catch up with all the recent changes. It's during that moment that the intense lag happens.

**Comment by SonarBeserk** [comment]
I dont think it is so much server/panel side as a case of your browser has to process the scripts it has for the most part been ignoring with the panel out of focus. That is speculation of course but i think that is the likely reason.

**Comment by Sorgrum** [comment]
Ok. I still need to test in Chrome because of how differently it manages tabs. If you need to close this up feel free, if not I'll report back with what I find.

**Comment by koo04** [comment]
I was using the panel the other day and noticed that the graphs were slowing down a lot after about half an hour. This was only happening if I had a different tab up or the window minimized, then switched to or opened back up.

Windows 8.1 - Chrome 40.0.2214.85 beta-m (64-bit) - 0.7.6.1-beta PP - 0.1.4 GSD

**Comment by LordRalex** [comment]
The graphs doing it is a known thing. It probably is related to why it happens elsewhere.

**Comment by DaneEveritt** [comment]
I believe if you disable animations on the graph it works fine. Might be the browser holding all those animations until the page is displayed again and then processing them all at once.

**Comment by koo04** [comment]
Okay, I did not notice any lag or slowing down from anywhere else.

**Comment by Sorgrum** [comment]
Where do you disable the animations on the graphs?

**Comment by DaneEveritt** [comment]
Its one of the settings for the Graph plugin, I can't remeber which exactly, but if you look up ChartJS it should link to their documentation which is a good starting point.
