### ISSUE TITLE
User self sign-ups

### ISSUE THREAD

**Issue by drtweety** [PufferPanel/PufferPanel#411]
I am currently working on a billing API module that will allow this but I was wondering if it will be implemented in the panel itself.

**Comment by DaneEveritt** [comment]
Self-signups are implemented within the panel. They are used for adding subusers, but you could totally hook into that for handling billing type things. The API can also create users, so you could do an external signup thing and then pass it through the API.

**Comment by drtweety** [comment]
Is there any planned functionality to add sub-users through the API?

**Comment by DaneEveritt** [comment]
Not really since that is something that individual users handle on their own.

**Comment by LordRalex** [comment]
I would argue some sub user stuff should be exposed on the api. But that should start going another issue since it is not related here.
