### ISSUE TITLE
Can I Use glusterFS?

### ISSUE THREAD

**Issue by drtweety** [PufferPanel/PufferPanel#413]
Can I store my user's minecraft world in a glusterFS directory? Just so that I can link all my nodes together.

[http://en.wikipedia.org/wiki/GlusterFS](http://en.wikipedia.org/wiki/GlusterFS)

GlusterFS is just like RAID storage, just over the network and with servers instead of hard drives.

**Comment by parkervcp** [comment]
In theory it looks like it should just work. Seeing as glusterFS is mountable as a directory. The only issues I see are lag on reads and writes due to networking issues. That is of course if you are using TCP/IP instead of  IB interconnects

**Comment by DaneEveritt** [comment]
This is not going to be implemented due to the amount of work that would be required for implementation and a very small fraction of people who would use it.
