### ISSUE TITLE
add autostart feature 

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#414]
When for example gsd crashes,  it takes all the servers down too. After you restart it does not turn on any of the servers.  Is it possible to get a autostart feature in the panel using checkboxes or a toggle button? 

(Yes, I know this is gsd related and that this can be done via gsd's api but it would be a nice feature for the panel too, and I would prefer that  :)  )

**Comment by SonarBeserk** [comment]
I dont see that getting heavy enough to need integration in the panel. How often are you likely to be restarting gsd?

**Comment by DaneEveritt** [comment]
That is already a feature of GSD, servers have an autoon setting, we just default it to false. We can add an option to set this to true or false on server creation I guess.

Also starting 20+ MC servers at once... good way to crash everything again.

**Comment by koo04** [comment]
Maybe I should do a 'sequenced' start-up of all servers that have this setting on, in GSD.

**Comment by LordRalex** [comment]
Sequential would be best. Or a "start X at a time" type deal. Some nodes should handle starting several at once.

**Comment by koo04** [comment]
Hard part is 'some'. Hence sequential would be good. Start until started or crashed. Then move to next server. Throw 'success' or 'fail' for each server, to the panel.

**Comment by LordRalex** [comment]
If we stick to the GSD implementation,  this just sounds like a lot we would have to make sure GSC  does too (or whatever it is called). This sounds like a nice feature, but probably should be back burned until we decide what the GSD plan will be. Rather avoid committing to this in any form till we decide where we are going.

**Comment by koo04** [comment]
It can be added into GSD anyway. No matter if it is implemented in the panel or not. Since we already have the 'auto-on' setting in GSD. Really, GSD should be doing it with sequencing anyway. I will add the issue and work on it at a later date.
