### ISSUE TITLE
Issues & Errors (Any Fixes?)

### ISSUE THREAD

**Issue by Optigonnn** [PufferPanel/PufferPanel#415]
First Error/Issue

1.Going to the port :8003 it shows this '{"code":"ResourceNotFound","message":"/ does not exist"}'
2.I cannot enter commands, restart, pause or shut down the server. When I enter a command this error appears "Unable to process your request. Please try again." and when I try to restart, pause or shut down the server this happens "Unable to process your request. Please try again. ([Exception... "" nsresult: "0x805e0006 ()" location: "JS frame :: https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js :: .send :: line 4" data: no])" (Note that START works fine and reading the console, although it's not real time, you need to refresh for new messages)
3. This keeps showing up " We were unable to connect to the main server, there may be network issues currently. This message will disappear when we are able to connect, you do not need to refresh." although everything is green.

Specs:

GSD 0.1.4
PufferPanel: 0.7.6.1
OS: Ubuntu
Web: Nginx

**Comment by DaneEveritt** [comment]
1.) That is normal behavior, you cannot just browse right to GSD in the browser, it needs to have authentication tokens passed through headers. Also that is an invalid URL according to GSD anyways. Not a bug.

2. & 3.) Please post the error logs located in `src/logs/exception.log` in your PufferPanel directory. It looks like you have a URL configured incorrectly.

**Comment by Optigonnn** [comment]
I can't find that file at all.

**Comment by Optigonnn** [comment]
There is only info.log and a html file saying 'unable to connect to 8003', which is only said once due to an error I had during setup because I had not started GSD.

**Comment by Optigonnn** [comment]
I'm using https://

**Comment by Optigonnn** [comment]
is it possible I could have your skype so we can fix this in real time? I mean starting server via panel works, viewing console works, but server resources, stop, restart, players online etc does not work.
