### ISSUE TITLE
Authenticate users from the API

### ISSUE THREAD

**Issue by drtweety** [PufferPanel/PufferPanel#417]
Instead of #411, we should be able to send username and password to the API and get a response whether the combination is correct.

**Comment by puffrfish** [comment]
Could you provide an intended use case for this feature? I'm having trouble imagining why you'd want this. Thanks

**Comment by tankerkiller125** [comment]
If OAUTH2 were used for authentication it could possibly be used by hosting companies for SSO logins between the panel and the billing panel/support area

**Comment by DaneEveritt** [comment]
The problem with this would be that most of PufferPanel links things to specific users, so it would be a bit of a pain to work in a fully functioning with server into the API. What would make more sense would be linking the PufferPanel logins to an external system (I.e whmcs) through some toggle options.

**Comment by LordRalex** [comment]
With the new API Phase 1, I am going to close this issue. Should it still be requested, you can visit the thread for the API and suggest it through that: https://community.pufferpanel.com/topic/92-web-api-phase-1-featuresgoals/?do=findComment&comment=428
