### ISSUE TITLE
Server online error, unable to start or stop servers or kill

### ISSUE THREAD

**Issue by th2000125** [PufferPanel/PufferPanel#419]
Hello,

I'm having an issue with the panel, the node appears to be running fine detection wise and is always online and responds immediately when I create a server.
However, when I attempt to start any bungee for Spigot/Bukkit server it behaves erratically, the server appears to be online as indicated by the status, but is unable to start any server.
When attempting to kill/stop/restart it responds to nothing and does not appear to close the "screen session" it has created.
When I was able to start a server "only been able to start a server once" it still would not respond to any commands from the console, none in the slightest.
Thank you for your response! And thank you for helping me!

Configuration file: https://www.zaoby.co.uk/config.json
GSD: 0.1.4
PufferPanel: 0.7.6.1 Beta
Operating system: 14.04.1 Ubuntu LTS
Web application server: LAMP
Java version: 8

**Comment by DaneEveritt** [comment]
Is gamehost empty on purpose in that config, or is it just not set?

Bungee servers haven't been tested with PP yet, so they are probably buggy. Try changing the plugin from `minecraft` to `bungeecord` in the config.json file. That might fix the problem.

**Comment by th2000125** [comment]
So yeah, they are all running apart from the bungee cord, well it is running but I can't access its control panel, this comes up every time
http://puu.sh/fck3Z/66da981489.jpg

**Comment by DaneEveritt** [comment]
Can you get the error out of src/core/exception.log?

**Comment by th2000125** [comment]
puu.sh/feYu3/06321c0cda.png
There is no log file in there

**Comment by th2000125** [comment]
^ and I clicked the wrong button...

**Comment by DaneEveritt** [comment]
Sorry, /src/logs not /src/core

**Comment by th2000125** [comment]
https://www.zaoby.co.uk/exception.log
There we go :)

**Comment by LordRalex** [comment]
Can you also provide this file: exception-2015-01-29-18-57-27-8c4f7c1a9b80052a37640f9ab62885aa.html

**Comment by DaneEveritt** [comment]
You actually **shouldn't** provide that file as it contains environment specific details and may provide access to passwords.

**Comment by th2000125** [comment]
Sorry. I thought it would be better you you had such access. I have removed the file but our file structure is not final anyway we planned to move it to another node after this was sorted out.
by the way thank you for helping me!

**Comment by DaneEveritt** [comment]
Oh sorry, I meant to not provide the actual .html files, the exception log was fine. Sorry for the confusion.
