### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by dannyiscool4** [PufferPanel/PufferPanel#420]
Fatal error: Class 'PufferPanel\Core\Version' not found in /home/u417602285/public_html/PufferPanel-master/src/installer/install/index.php on line 48

**Comment by LordRalex** [comment]
You did not checkout the 0.7.6.1-beta release.

**Comment by dannyiscool4** [comment]
Works that?

**Comment by LordRalex** [comment]
http://docs.pufferpanel.com Follow all the directions. Do not skip any.
