### ISSUE TITLE
Bug occurring when decompressing files through GSD

### ISSUE THREAD

**Issue by DaneEveritt** [PufferPanel/PufferPanel#422]
It seems that if you try to decompress a file through GSD it fails to complete unless GSD was just restarted.

```
{"code":"InternalError","message":"Object /home/mc-ubuntu_lv8jk/world_the_end-Fri-Jan-30-2015-18-12-14 has no method 'extname'"}
```

Seems to work fine if I restart GSD and then decompress the file. But as soon as I delete the file and try to decompress again it fails.

**Comment by koo04** [comment]
Have you attempted with the latest master push? I think I had fixed that.
