### ISSUE TITLE
nothing works for me

### ISSUE THREAD

**Issue by davidclarkkent1** [PufferPanel/PufferPanel#425]
hi.
i cant open the file manager it just says: GSD ERROR: EMFILE, too many open files '/home/mc-server_bm9zx/' also i cant connect using FTP It just says ''username good, password needed'' but i changed the password and tryed again but still doesnt work:/
why? also i want to disable totp settings/2FA
please anyone help me it's urgent

**Comment by drtweety** [comment]
Do you have all the dependencies installed?

**Comment by DaneEveritt** [comment]
Too many open files sounds like something configured on your server that is preventing you from opening enough files.
