### ISSUE TITLE
predict owner mail when creating new server

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#427]
when you setup a new server you have a little box for the owner email, what if the box would predict the mail that you are typing in via a little dropdown? 

picture as example:
![2015-02-07 21_53_37-admin area _ gitlab - firefox developer edition](https://cloud.githubusercontent.com/assets/3273394/6093898/d7b74d2a-af13-11e4-9c33-1c6d5ab0fed1.jpg)
 

(its a small touch, but its nice to have :) )

**Comment by koo04** [comment]
Only issue is privacy. I could go in and start typing letters and get emails of users. Then use that for spam, worse case scenario. Just another reason why I want to use username aliases. >.>

**Comment by LordRalex** [comment]
@koo04 This says new server though, which means there is an admin doing it, so "privacy" at that point could be questionable.

**Comment by koo04** [comment]
Sure, but admins can be dicks too. I just know that things regarding other account emails has been brought up in the past. The admins should just know the emails that are needing to be invited.

Now, this could be nice for PufferPanel admins in the back end. When adding a new server, I would love to either get a full list or get a drop down like the suggestion.

**Comment by DaneEveritt** [comment]
![](http://s3.kelp.in/X7BGa.png)

**Comment by worldmc** [comment]
Nice!

Op wo 11 feb. 2015 20:16 schreef Dane Everitt <notifications@github.com>:
