### ISSUE TITLE
Unable to add locations (Dev 0.8.0)

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#432]
In 0.8.0 you are unable to add a new location. 

The error message I got was  "SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'pufferpanel'@'localhost' for table 'locations'"

Steps to reproduce:
1. Go to the admin section of the panel
2. Go to location settings
3. Add Location

**Comment by DaneEveritt** [comment]
This is an issue with the user you have added to the panel to handle SQL, not the panel itself.
