### ISSUE TITLE
Error on password reset (Dev 0.8.0)

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#435]
When trying to reset your password on 0.8.0 you get an error when you try to reset your password.

The error i received was "SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'pufferpanel'@'localhost' for table 'account_change'"

Steps to reproduce:
1. Forget password
2. Enter a valid email
3. Submit password reset

**Comment by DaneEveritt** [comment]
This is an issue with the user you have added to the panel to handle SQL, not the panel itself.

**Comment by DaneEveritt** [comment]
This is an issue with the user you have added to the panel to handle SQL, not the panel itself.

**Comment by SonarBeserk** [comment]
Were it a sql issue from the user I would expect the sql error message to say it was using a password.

**Comment by DaneEveritt** [comment]
https://github.com/PufferPanel/PufferPanel/commit/81f0315ce98f79d329ab067fcb9c92a69611e92f
