### ISSUE TITLE
Users with root administration are unable to control servers (Dev 0.8.0)

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#447]
Currently with no way to kill servers without downing GSD there is no way to stop a server if you are not assigned to it directly.

**Comment by DaneEveritt** [comment]
You should be able to control servers, but alas, I probably did not do the permissions checking properly.

If I understand right, you make a server for a non-admin user, and then try to access it as an admin and nothing works, or only GSD things work?

**Comment by SonarBeserk** [comment]
Well i cant do anything but watch the console output.
