### ISSUE TITLE
Global Settings uncheck doesn't save

### ISSUE THREAD

**Issue by blockcounter** [PufferPanel/PufferPanel#449]
When logged in as administrator and on the global settings page you uncheck one of the options it doesn't recognize it a a change and doesn't save it.
When you enable a different option en disable this on it will however save it.
So you can't disable anything if you don't also enable something else.

**Comment by LordRalex** [comment]
I just did a fresh install of the latest build we have, and cannot replicate it there. We likely already addressed that issue.

**Comment by blockcounter** [comment]
Okay, I'll update it then. Thank you!

**Comment by LordRalex** [comment]
You will not be able to use the latest version since there is no documentation on how to.

**Comment by blockcounter** [comment]
Ah, yeah. Of course. Thanks anyways

**Comment by DaneEveritt** [comment]
@blockcounter — you can always manually edit the settings table in the database to disable things if you want. What do you want to disable?

**Comment by blockcounter** [comment]
Nah, doesn't really matter. I enabled force-online and then wanted to disable it again. I switched subusers on and disabled force-onlind while doing so. I'm fine with these settings
