### ISSUE TITLE
can't load required language file

### ISSUE THREAD

**Issue by parkervcp** [PufferPanel/PufferPanel#453]
In the latest dev build I am failing to load languages. It's looking for a file called en.json.

>[2015-02-22 06-25-29] Exception: Unable to load the required language file! /var/www/html/PufferPanel/app/languages/en.json in /var/www/html/PufferPanel/src/core/language.php:49  @  http://{redacted}/index  @@  exception-2015-02-22-06-25-29-c1dafa794e811a7a164b2f3b218f6e96.html

**Comment by parkervcp** [comment]
This commit - https://github.com/PufferPanel/PufferPanel/commit/e96cc04fc390a6d4bd735a31c78b9f781fbfc7d4

Seems to be what broke the languages

**Comment by LordRalex** [comment]
The commit you linked was intentional. There is a reason why those files got removed.

How did you install the panel, because the installer handles that.

**Comment by LordRalex** [comment]
Run https://github.com/PufferPanel/Tools/blob/master/language/language-builder passing it "-p <where you installed the panel>"
