### ISSUE TITLE
Centos 6 - GSD using wrong command to delete user, leaving deleted server files on the node

### ISSUE THREAD

**Issue by Maelstrom96** [PufferPanel/PufferPanel#454]
GSD [ERROR] Cound not execute command! deluser --remove-home mc-surviv_hmpsp

good command : userdel --remove User

**Comment by LordRalex** [comment]
Yay, distro differences. This is why we don't get nice things.

**Comment by koo04** [comment]
This may be fixed in Scales. This kind of thing is all the reason why we are trying to remove GSD from the equation.
