### ISSUE TITLE
Prompt for file deletion

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#455]
Very easy to just delete a file on accident, should be confirming if they want to delete a file

**Comment by Maelstrom96** [comment]
And if possible, tickboxes with possibility to reset the directory to clean (with default .jar file)

**Comment by koo04** [comment]
@Maelstrom96 Please make that another issue. Thanks.

**Comment by Omeryl** [comment]
Working on this one next, :).
