### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by HogensHero** [PufferPanel/PufferPanel#458]
I have attempted to install pufferpanel using the directions on the website. It was going good until the end where I got this on the screen. 

http://pastebin.com/n3d3JSNh

The log shows this

http://pastebin.com/6JVG3Nsb

Any help would be greatly appreciated.

**Comment by DaneEveritt** [comment]
Follow the directions [here](http://www.pufferpanel.com/v0.7.6/docs/adding-a-new-node), specifically the section about [FTPS](http://www.pufferpanel.com/v0.7.6/docs/adding-a-new-node#ftps-configuration).

**Comment by HogensHero** [comment]
Well thank you for the very sarcastic response. In the tutorial it states:
 NodeJS Version

GSD will not work with NodeJS version 0.12.0 due to dependency issues. You must install 0.10.33 to use GSD.

And as it clearly states on line 42 of the first pastebin:
42. npm ERR! node -v v0.10.33

And as it clearly states on line 24 of the second pastebin:
24.  15 error node -v v0.10.33

So as it clearly states I have the correct version of NodeJS. Also setting up the cert file listed is very very easy. I am sure there is no way anybody could mess it up.  So I ask again what may be the issue that I am having. 

On a side note instead of responding to people that are trying to help you debug with sarcasm, how about writing a better tutorial and or actually giving some advise.

**Comment by LordRalex** [comment]
Did you even read what he said? Because your reply is quite hateful when it was not even related to what he told you.

>Actually, it appears you might have just installed the wrong version of GSD. 

GSD is not NodeJS. And you were told to read about the FTPS configuration.

**Comment by HogensHero** [comment]
I sorry but how can I install the wrong version by using the installation tutorial at http://www.pufferpanel.com/v0.7.6/docs/how-to-install were is clearly states:

PufferPanel can be automatically downloaded and placed in the correct folder by executing the commands below.

cd /var/www/yoursite.com
git clone https://github.com/PufferPanel/PufferPanel.git .
git checkout tags/0.7.6.1-beta

Now tell me if I am wrong but if this is the wrong GSD to install then the tutorial is wrong.
Again I ask someone with this project to help me find the error with this install as I have followed the tutorial exactly step by step, except where needed to install dependencies, instead of getting rude or sarcastic comments back.

**Comment by LordRalex** [comment]
Are you even bothering to look at the links we posted? Because right now, I have no confidence *at all* that you are. 

You have been linked http://www.pufferpanel.com/v0.7.6/docs/adding-a-new-node

You are not reading the right tutorial at all. And yet you somehow followed one to get GSD installed.

RTFM. Seriously. http://www.pufferpanel.com/v0.7.6/docs/adding-a-new-node#install-game-server-daemon.

**Comment by DaneEveritt** [comment]
Discussion moved to https://github.com/PufferPanel/PufferPanel/issues/459
