### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by HogensHero** [PufferPanel/PufferPanel#459]
Since my comments were locked on a previous issue #458, I will post my reply here.

Well obviously I am reading that page as it is the next step in your tutorial unless you have a different page than the entire world wide web. What part of I followed every step of the tutorial do you not understand. 

First you go to this page to install the puffer panel:
http://www.pufferpanel.com/v0.7.6/docs/how-to-install
Then the next obvious step would be to go to the node instillation page here:
http://www.pufferpanel.com/v0.7.6/docs/adding-a-new-node

Oh wait that is the same page that you posted. I am not an idiot, I know that you follow a tutorial step by step to install something. There is something wrong with your tutorial and or your program. I am asking for help in installing this program and that is it. I am not asking to be badgered by the devs like I am some stupid little kid. If this tutorial is so easy please install a fresh version of Ubuntu 14.04lts and install pufferpanel exactly how the tutorial says and not use your knowledge of the dependencies that are required. Just follow the tutorial and type everything out just like I did.

By the way the next "DEV" version is v.0.8.0 and it does not have any documentation as you said in a previous post.

**Comment by DaneEveritt** [comment]
Your first issue was because you installed v.0.1.5 of GSD, which is **not** PufferPanel. I pointed you to the documentation for installing the correct version of GSD (v0.1.4) for PufferPanel v0.7.6.1, as is mentioned in the documentation.

The documentation above is correct and we have installed it ourselves following that documentation, as well as countless others. There is no documentation out for v0.8.0 of PufferPanel because it is not released, and we want to avoid any confusion. Additionally, since it isn't even done, we don't know what all we even need to be documenting for it yet.

**Comment by HogensHero** [comment]
I guess pufferpanel is a complete waste of my time because you and your devs cannot understand that I followed your tutorial exactly as it is on your website. I don't know what it is going to take to make you understand that there is something wrong with either your tutorial or your program. Time to take it all down and check your code. Somewhere you or your devs made a mistake and its the public's fault because we followed your tutorial. Good luck with your broken program and or tutorial.

**Comment by DaneEveritt** [comment]
Thank you for letting us know where you think the error is so that we can fix it...

You keep saying the documentation is wrong and that we are shorty devs without providing any context for what the problem is.

**Comment by HogensHero** [comment]
Thank you for the response, I assumed that when I stated in every post I made that I followed your tutorial that something might clicked. If I have installed GSD v. 0.1.5 then it is obviously wrong with your tag as I typed in the git command exactly as it is on your tutorial. I apologize if I was rude but you made it seem like I did sometging wrong when I followed your tutorial to the letter, instead of saying hey can you check this or hey maybe we linked the wrong file to that tag. I like the looks of this panel and my company may be interested in using this panel or at least beta testing it. Again all I am asking for is a little help in installing the program and getting it working to test it.

**Comment by DaneEveritt** [comment]
I'd be happy to help, can you go ahead and tell me what error you are currently getting? Thanks!

**Comment by HogensHero** [comment]
The error I am getting is in the very first post of issue 458. You said I have installed the wrong GSD, now I am not sure where to get the correct GSD as I typed in this command. 
cd /srv && git clone https://github.com/PufferPanel/gsd.git 
git checkout tags/0.1.4
That is the command taken form the install node page of the tutorial and the command I typed in. I don't know if your tag links to the newer version of GSD or not, that is why I am asking you for help.

**Comment by LordRalex** [comment]
git rev-parse HEAD

Run that. Give us the code it prints out.

**Comment by HogensHero** [comment]
Thank you for the trouble shooting tip. I ran the command you gave me and the output is as follows:

1004e232516553166879f9b9ea68d0866e513baa

Also I can test the install tutorial again now that it has been updated. Would it be better if i reinstalled the server with a fresh copy of Ubuntu to test?

**Comment by DaneEveritt** [comment]
You should be fine to just run `cd /srv/gsd && git checkout tags/0.1.4` which should get you running with the correct stuff.

**Comment by HogensHero** [comment]
Thank you I will run those command in a moment

**Comment by HogensHero** [comment]
Well by using the commands you provided did not work. What I wound up doing was rm -rf /srv/gsd to remove the entire gsd folder and started over. The new tutorial worked and it started up and the panel found the node. Well done on the solution. 

One last question, can the gsd be run as a service and or under /etc/init.d? If not are there plans to create a script for either  methods?

**Comment by puffrfish** [comment]
Glad you got things working. I don't believe anyone has written an init script for GSD yet, but with Scales replacing GSD soon I'll make sure we have one for Scales when it's ready.

**Comment by DaneEveritt** [comment]
You could also look into using [forever](https://github.com/foreverjs/forever) for now.

**Comment by HogensHero** [comment]
That looks like a good alternative than using screen. I see that there is a monitor for it as well. Thanks for the suggestion, I look forward to seeing what you guys come up with in the next version.
