### ISSUE TITLE
2FA/TOTP problems

### ISSUE THREAD

**Issue by davidclarkkent1** [PufferPanel/PufferPanel#460]
i today i broke my phone that had the TOTP on it so now i cant acces my account and idk how to recover or delete teh 2FA/TOTP option please help me

**Comment by DaneEveritt** [comment]
Edit the `users` table in the database and set `totp_enabled` to `0` for your account.

**Comment by davidclarkkent1** [comment]
and where do i find that things?

**Comment by puffrfish** [comment]
You'll need to manually edit the database using either the MySQL CLI client or some other external MySQL client.

I'm tagging this for enhancement as I'd like to see some kind of script or other method for resetting TOTP on an account. This is not an uncommon problem with TOTP in general.

**Comment by davidclarkkent1** [comment]
can you like send me a download link or anything like that so i can get to that because i cant find anything:/

**Comment by SonarBeserk** [comment]
If you have the database login details, get a mysql client and connect to the database. The will be a users table, you just edit your personal entry and change totp_enabled to false.

**Comment by davidclarkkent1** [comment]
is the mysql login stuff same as the FTP login stuff?

**Comment by SonarBeserk** [comment]
Not at all. It is a separate system. If you didnt setup the mysql database you will need to contact whoever did.

**Comment by davidclarkkent1** [comment]
ok thanks

**Comment by davidclarkkent1** [comment]
so if i dont got the mysql im pretty much done/no acces to my server?

**Comment by worldmc** [comment]
The only way at this moment to reset it is via the database. so yes, other then having a other root admin giving you a new account again you are done for now. (until its pushed in an update to fix it)

**Comment by davidclarkkent1** [comment]
ok but the guy that gave me the account never answer when i message him his name is ''shybella''

**Comment by worldmc** [comment]
We cant do anything for you other then give you advice on what to do. best bet is to message mister "shybella" and ask him if he could do it and link him this issue post.

**Comment by davidclarkkent1** [comment]
ok thanks again

**Comment by LordRalex** [comment]
Just leave it closed

**Comment by DaneEveritt** [comment]
This is not an issue with the panel.
