### ISSUE TITLE
Tokens, try to use when adding a sub-user and i get a "You don't have permission to use this token"

### ISSUE THREAD

**Issue by JDuskey** [PufferPanel/PufferPanel#463]
Any fix?

**Comment by SonarBeserk** [comment]
There are multiple things needed to be known before any fix can be given. The most major being what version are you on?

**Comment by DaneEveritt** [comment]
Sounds like the token doesn't match the account email that is trying to use it.

**Comment by JDuskey** [comment]
I am using version 0.7.6, and I open the link, insert the server token into the box, and it says that I don't have permission to use the token.

**Comment by DaneEveritt** [comment]
Is this when you already have an account or when you go to make one?
