### ISSUE TITLE
TOTP Reset capability

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#466]
Since the other issue was closed by the reporter, this issue serves as a request for the ability to reset admin TOTP from the server itself. Some kind of PHP CLI script is probably the best way to do so.

**Comment by DaneEveritt** [comment]
Semi-related: users can now disable TOTP from their account settings. Doesn't fix a lockout problem, but does at least offer some more control for them. Would you be opposed to having a button that an admin can use in the ACP to disable TOTP on an account?

**Comment by puffrfish** [comment]
I think it makes sense for admins to have the ability to disable TOTP on other (possibly only non-admin) accounts. It is not uncommon for users to lock themselves out and have to contact the administrator to gain access again.

However, when it comes to an administrator who needs TOTP disabled, that should be able to be done from the server itself.

**Comment by LordRalex** [comment]
We will end up making this a tool with the 0.8.1 release installer, but really would be available to the public with the 0.8.2 release.
