### ISSUE TITLE
adding a sub user

### ISSUE THREAD

**Issue by davidclarkkent1** [PufferPanel/PufferPanel#467]
Hi i tried to add a sub user to my console i made the email to that person but he never got it it sad it was successful but he didnt get it in his email inbox, is it on a github inbox or what? i dont udnerstand

**Comment by puffrfish** [comment]
Have any of the emails PufferPanel has sent been delivered successfully? Please verify your email settings if not.

**Comment by DaneEveritt** [comment]
If it said it went through successfully then there are three possible problems:

a.) You entered an invalid email;
b.) PufferPanel is not configured to send emails correctly;
c.) His email service marked it as spam

**Comment by davidclarkkent1** [comment]
i sended on to myself(other email) and it sad it was succesful i checked the email its right also the spam box nothing there either. so i dont really know what else i should do

**Comment by DaneEveritt** [comment]
Emails are configured incorrectly on the server then. You need to go into the ACP and set them up correctly.

**Comment by davidclarkkent1** [comment]
ok well I cant do anything since i need to wait to the next update
