### ISSUE TITLE
Enhancement: bigger console screen

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#469]
Hello, im here again :)

today i were working with pex to setup groups and when doing the "pex groups" command i had to scroll up and down in order to see the entire list. now one could call this being lazy but i want to suggest to make the console screen a bit taller. 
![suggestion for pufferpanel](https://cloud.githubusercontent.com/assets/3273394/6769232/bed3babe-d092-11e4-9189-018c74147a58.png)
(note, i know that this looks different on every screen but an implimentation with some javascript/css magic could make this set at an percantage)
let me know what you think!

**Comment by LordRalex** [comment]
It seems more like this console could be made to be vertically resize-able, would let you make it bigger if you need it, but still not lock it to a certain size.

**Comment by DaneEveritt** [comment]
Browsers should let you do this, I think I just disabled that for some reason. Should be easy to manually modify the CSS file though.
