### ISSUE TITLE
[Question] Java Custom Arguments

### ISSUE THREAD

**Issue by WtGuy** [PufferPanel/PufferPanel#472]
Hey-o.

To preface this, I'm not 100% sure if this is the appropriate section to post this in, so please tell me if this is a stupid place to ask this question and direct me to the appropriate place if this is the wrong place to ask this.

I was wondering if the PufferPanel has the ability to support custom jvm arguments. In particular, for my current scenario, I was looking to increase the maxPermGenSize. I've been mulling around in the code seeing if I could make some edits for my setup, but was unable to locate them. So, is this supported and if so, what are the steps into setting up custom arguments?

Thank you so much for your hard work and taking the time to answer my questions.

Regards,
WtGuy

**Comment by DaneEveritt** [comment]
Last I checked GSD "supports" it, but I don't think it really worked at all. In the coming updates, including the move to Scales, they are better supported. As of Java 1.8 though you don't need any permgen settings, so you could try that too!
