### ISSUE TITLE
Backups with FTP upload

### ISSUE THREAD

**Issue by Cometex** [PufferPanel/PufferPanel#473]
Hello,

it would be great to have the ability to create compressed backups of worlds that the user picked. 
The backups should be stored either on the local harddrive or uploaded on an external FTP server.

And the backups should be automated created at a time set at an schedule. 

Let me now what you think. ;)

**Comment by worldmc** [comment]
I like this idea

Op ma 30 mrt. 2015 13:00 schreef Cometex <notifications@github.com>:

**Comment by computerwizjared** [comment]
Any updates on this? It would be an awesome feature :)

**Comment by LordRalex** [comment]
This would actually need to be a Scales request, as all of that logic would run off Scales.

**Comment by computerwizjared** [comment]
Yeah, it looks like this was created before Scales was available... should I recreate this issue over in the Scales repository then?

**Comment by puffrfish** [comment]
I am fine with this being here still since it's not exclusively for Scales. @computerwizjared for updates on our current development progress please see [this post](https://community.pufferpanel.com/topic/146-pufferpanel-v09-development/).

**Comment by computerwizjared** [comment]
Thank you :)
