### ISSUE TITLE
Schedule for example daily restarts

### ISSUE THREAD

**Issue by Cometex** [PufferPanel/PufferPanel#474]
Hello,

i'm missing the ability for daily restarts. Even better would be a schedule to perform actions like restarts, backups (as requestes in another issue) or custom commands every X minutes/hours/days.

Let me know what you think. ;)

**Comment by puffrfish** [comment]
This would be useful for keeping SRCDS servers up to date as well. Nothing more frustrating than having your client update while the server is out of date.

**Comment by puffrfish** [comment]
This is definitely a highly requested feature at this point. I don't know exactly when this will make it in but it is for sure something we will implement.

**Comment by DaneEveritt** [comment]
Working on it for a 0.8.x release hopefully. :)
