### ISSUE TITLE
Amount of online players

### ISSUE THREAD

**Issue by Cometex** [PufferPanel/PufferPanel#477]
Hello,

the feature to show the heads of the online players is nice but it would be even better to see the amount of the online players in the table at "My Servers".

Let me know what you think. ;)

**Comment by DaneEveritt** [comment]
Its possible, but would require doing some more queries on each of the servers. Don't see why I couldn't though since it just requires some rewrites to access Scales directly rather than funnel through PP (which would make more sense for checking anyways).

**Comment by ET-Bent** [comment]
Maybe there is also a fix needed, the users that are displayed in our panel (v 0.8.1) are showed on the wrong server: if there are foo and bar on server one they are displayed as users on server two.

**Comment by ET-Bent** [comment]
To add to this, in our setup (version 0.8.2) the amount of online players + the player list is shown in the completely wrong servers. For example: Server A has 12 players but those are shown in the overview of server B while the overview of server A shows that there are no players online.

A second thing to add to this would be having a admin panel where you see the total players online on the node.

**Comment by computerwizjared** [comment]
@ET-Bent There's an issue for that at PufferPanel/Scales#34

**Comment by DaneEveritt** [comment]
Closing this issue as discussion should take place in the Scales issue, and I've decided to not implement player counts on the My Servers Page for now.
