### ISSUE TITLE
Only one server as subuser

### ISSUE THREAD

**Issue by Cometex** [PufferPanel/PufferPanel#478]
Hello,

unfortunately a user can only be a sub user at one server.
If i add user X as subuser to Server 1 and after that to Server 2.
He got perms to control Server 2 but at Server 1 it looks like:

![unbenannt1](https://cloud.githubusercontent.com/assets/11718163/6895857/d1ed4270-d6e4-11e4-96d5-22326cef8955.PNG)

And if i click on it:
![unbenannt2](https://cloud.githubusercontent.com/assets/11718163/6895859/d9c3d9f0-d6e4-11e4-9211-8115c896da20.PNG)

The permissions entry in the MySQL Database for the user looks like:
{"XXX":{"key":"XXX","perms":["console.commands","console.power","files.view","files.edit","files.save"],"perms_gsd":["s:console","s:query","s:power","s:files","s:files:get","s:files:put"]}}

Could that be fixed? ;)

**Comment by DaneEveritt** [comment]
Already fixed in 0.8.0, probably related to https://github.com/PufferPanel/PufferPanel/issues/397

**Comment by Cometex** [comment]
Perfect! When will 0.8.0 be available?

**Comment by DaneEveritt** [comment]
Eventually. Still having it tested by some other developers first. Its getting there though.

**Comment by Dylan3304** [comment]
That is what I like to hear @DaneEveritt
