### ISSUE TITLE
changing server name does not give conformation

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#479]
Hello,

i was changing the name of some servers today and there is no little feedback box.

is this something to implement? 
example:
find server > server settings > change server name > hit update > feedback ??? (failed or was succesfull?)

atm it just returns you to the page.

**Comment by DaneEveritt** [comment]
Already fixed in 0.8.0 it seems.

**Comment by worldmc** [comment]
Nice thanks
