### ISSUE TITLE
FTP Uploads Hang.

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#484]
Hello,
On my new PufferPanel installation, when I try to FTP into my server, uploading files is very glitchy. It tries to upload more than one of each file and it takes hours to upload like 10 files. I have 1 Gbps network so this shouldn't be so slow. I'm using the latest version of PufferPanel, and I'm kind of new to this.

**Please let me know of any logs you would like to provide.**

**Comment by DaneEveritt** [comment]
Known issue with other people's installs. Im not going to look into this because we are getting close to releasing 0.8.0 which will solve most of these problems. Sorry about the troubles though, hopefully we can get these fixes out soon.

**Comment by Dylan3304** [comment]
Thanks @DaneEveritt! How long till 0.8.0?

**Comment by DaneEveritt** [comment]
No idea, but hopefully not too long.

**Comment by Dylan3304** [comment]
Could changing the GSD active FTP ranges in config.json work?

**Comment by Dylan3304** [comment]
*PassiveFTP and what about changing this or should I try config.json first?
![image](https://cloud.githubusercontent.com/assets/2935060/6940406/12482bf2-d83c-11e4-9a90-c4a914d6e9c7.jpg)

**Comment by DaneEveritt** [comment]
You can try commenting out the `pasvPortRangeStart` and `pasvPortRangeEnd` (or just remove them) and see if that fixes anything.

**Comment by Dylan3304** [comment]
I commented them out with two `//`, no luck. I then tested it, and tried disabling SSL. No luck. Should I possibly try PassiveFTP?

**Comment by Dylan3304** [comment]
If there is no solution, could you point me to a temporary solution until 0.8.0 is realized? I'm having a few clients of my business test out PufferPanel, nothing for production use, I just wanted them to see how it was going to work.

**Comment by DaneEveritt** [comment]
Unfortunately there is nothing that I can think of to fix it temporarily. The entire setup of GSD is kind of ugly when it comes to FTP, so your guess is as good as mine.

**Comment by Dylan3304** [comment]
Okay, I really need 0.8.0, and fast. Please if you could push the next update quickly, I might be able to donate some cash.

**Comment by DaneEveritt** [comment]
Have you tried using a different FTP client?

**Comment by Dylan3304** [comment]
@DaneEveritt Yes. I've tried cyber duck, FileZilla, and webFTP.

**Comment by Dylan3304** [comment]
@DaneEveritt I would like a response even if it is your clueless...

**Comment by DaneEveritt** [comment]
Looks like you have a network issue possibly. I have no idea what else it could be, and frankly asking over and over isn't going to really do anything because I'm not about to spend forever trying to diagnose an issue that is already fixed in future versions.

```
Error: Connection timed out after 20 seconds of inactivity
Error: File transfer failed
```

Make sure that your firewall is setup correctly to allow connections, other than that I have no idea.

**Comment by Dylan3304** [comment]
Could I get a timeframe for the future update? I don't want to spend hours recoding the GSD myself only to find that the next version will be here in days @DaneEveritt

**Comment by LordRalex** [comment]
Putting ETAs in software that is in a beta state is just not something we
like to do. We could release it next month, we could release it in 6. If
you really want it now, take the time to fix it.

Or run the completely undocumented and unstable builds.
