### ISSUE TITLE
SFTP Settings for server are blank

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#486]
![image](https://cloud.githubusercontent.com/assets/1438668/6933384/21e40220-d7ec-11e4-846f-1b1c1949cef3.png)

**Comment by LordRalex** [comment]
Also applies to Server Settings

**Comment by DaneEveritt** [comment]
I've been unable to replicate this reliably so I am closing this issue for now. We should reopen it if the problems continue to occur.

**Comment by LordRalex** [comment]
WE FIXED IT!

(I blame @DaneEveritt)

**Comment by DaneEveritt** [comment]
My logic was amazing when writing those functions I guess.
