### ISSUE TITLE
Adding a node with no port bindings creates an blank port (Dev 0.8.0)

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#488]
As shown in 
![serk_projects_admin_control_panel_-_add_a_new_serv_2015-04-01_01-08-44](https://cloud.githubusercontent.com/assets/1880661/6935025/036ed386-d80c-11e4-927c-f688fc74a4bd.png)

A blank port is listed and available.

**Comment by SonarBeserk** [comment]
Looks to be that the issue is actually that you can create a node with no ports bound which creates a blank port.

**Comment by LordRalex** [comment]
Closing in favor of #490 which covers several issues on the ip + port check in the add node, including this one
