### ISSUE TITLE
NPM start error

### ISSUE THREAD

**Issue by TNSPredator** [PufferPanel/PufferPanel#492]
Hello, so I booted my server up today and tried to update PufferPanel but I came across this error:
 
npm ERR! GameServerDaemon@0.1.5 start: `node gsd.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the GameServerDaemon@0.1.5 start script.
npm ERR! This is most likely a problem with the GameServerDaemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node gsd.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls GameServerDaemon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/gsd/npm-debug.log
npm ERR! not ok code 0

Does anyone have a solution?

**Comment by Wargog** [comment]
Can you post /srv/gsd/npm-debug.log?

**Comment by TNSPredator** [comment]
Sure:


10 error GameServerDaemon@0.1.5 start: `node gsd.js`
10 error Exit status 8
11 error Failed at the GameServerDaemon@0.1.5 start script.
11 error This is most likely a problem with the GameServerDaemon package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node gsd.js
11 error You can get their info via:
11 error     npm owner ls GameServerDaemon
11 error There is likely additional logging output above.
12 error System Linux 3.2.0-4-amd64
13 error command "/usr/bin/node" "/usr/bin/npm" "start"
14 error cwd /srv/gsd
15 error node -v v0.10.38
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

**Comment by DaneEveritt** [comment]
Please post the output of `sudo node gsd.js verbose`

**Comment by TNSPredator** [comment]
Ah silly me. Thanks for your help DaneEveritt, it is working now.

**Comment by TNSPredator** [comment]
Now I get this error when trying to start a server: 
"Unable to process your request. Please try again. Unable to start server (Cannot read property 'keys' of undefined)"

**Comment by DaneEveritt** [comment]
Sounds like there was a glitch when trying to make the server. Make sure your base config.json is the same as the one provided by PufferPanel.

**Comment by TNSPredator** [comment]
Yes it is the same. Don't worry I will just re-install everything.
