### ISSUE TITLE
Adding Existing User to Server

### ISSUE THREAD

**Issue by computerwizjared** [PufferPanel/PufferPanel#493]
Hi, I've been messing with PufferPanel and it looks great! Something I would love, and I'm sure someone else has noticed this, is adding existing panel users to a server. Currently, I either have to add a user as an admin (which is not pliable for real-world use), or add them a new sub-user for each server that they use. Just thought that I would put this out there. :) Thanks for this awesome software and I can't wait to see where you go with it in the future!

**Comment by DaneEveritt** [comment]
I'm not sure I understand what you are asking for exactly.

**Comment by computerwizjared** [comment]
@DaneEveritt I'm sorry, after looking further at the sub-user features it looks like you can add multiple servers to a user. Sorry.... Thanks for your time.
