### ISSUE TITLE
Resolve issues with the DB in general

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#496]
Since the panel has no foreign keys on key tables (locations, nodes, servers), you cannot enforce data in any real way.

If you delete a location, you leave a node and server on the database, but you won't be able to access them since the panel is missing that location. You should not be able to delete the location if there is data tied to it.

**Comment by DaneEveritt** [comment]
This should be fixed now.

**Comment by LordRalex** [comment]
please don't close this till i am done :(

**Comment by LordRalex** [comment]
Replace varchar with char if the column is same length for all entries

**Comment by worldmc** [comment]
would that not limit in upgradeability later down the line?  (Just a thought,  dont shoot me for It)

**Comment by LordRalex** [comment]
How so? If we need to change it, doing an alter table to make it a varchar should not break it.

**Comment by worldmc** [comment]
i gues, but its extra work down the line and it might brake dowgrading if ever needed.

**Comment by LordRalex** [comment]
Downgrading is usually not something that can ever be recommended really, so not a huge concern to me for that. And not quite sure how it's extra work.

**Comment by DaneEveritt** [comment]
VARCHAR and CHAR are basically the same thing anyways, just a different in extra info that is stored with each. There is nothing hard about switching the datatypes at some later point. And there will never be downgrading in PufferPanel, just not a feasible option (and there won't even be an upgrader for 0.7.6 to 0.8.0).

**Comment by worldmc** [comment]
Ok, nvm then.
