### ISSUE TITLE
Scales requires a plugin in order to create a server

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#497]
If intended, panel should reflect that.

If not, then Scales needs a patch or the panel should send something instead.

https://github.com/PufferPanel/Scales/issues/9

**Comment by DaneEveritt** [comment]
Shouldn't need a plugin to create a node, you do need one to make a server though.

Forgot to add to the installer, but I will be shipping some default server plugins with PufferPanel (that are included with Scales).

**Comment by LordRalex** [comment]
Still, if it is a constraint that exists, the panel should reflect that. If you delete all plugins for example, it should still apply.

**Comment by DaneEveritt** [comment]
It will become quite obvious when you try to add a server and you can't select anything from the drop-down box. Feel free to submit a PR to add in a little notice if you want though.

I still have no idea how you managed to get that error, unless you sent a blank plugin, in which case we need to look at Scales error handling for that.

**Comment by DaneEveritt** [comment]
This issue was "fixed" by changing how Scales handles installing server and such.
