### ISSUE TITLE
suggestion,  lock a server from boot by a root admin

### ISSUE THREAD

**Issue by worldmc** [PufferPanel/PufferPanel#498]
So I was thinking,  I have a few old servers laying around,  their users arent used anymore but I want to keep the server on file.  So I "lock" them from being able to be booted up, and by accident using too much ram.  

Let me know what you think.

**Comment by SonarBeserk** [comment]
Why bother to add them if they wont be booted up?

**Comment by worldmc** [comment]
if for example the server is not needed anymore, and needs to be "parked"

**Comment by tankerkiller125** [comment]
A better example is if I'm a server host and I have a client who hasn't paid for the month and I want to make it so that third server can't come online but I keep the files so that if they do pay me I can just unlock it and start it and they don't have to worry about it.

**Comment by SonarBeserk** [comment]
So #344 but for servers instead?

**Comment by worldmc** [comment]
Yep

**Comment by puffrfish** [comment]
This will be implemented as a suspension feature, particularly in the API so billing software can issue suspensions before deleting a server forever.

**Comment by puffrfish** [comment]
Relates to #344
