### ISSUE TITLE
Re-re-re-re-visit subusers

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#502]
The table is really ineffective and clutter. Probably something we can do about it.

**Comment by DaneEveritt** [comment]
Notes:
* Using a `uuid` where we don't actually need to use one. Should be able to expose the email front-end and link it to a known server value when managing a subuser.
* Setting `user` to `-1` is amusing.

**Comment by LordRalex** [comment]
FKs will not be an issue, because you can use NULL on the link. That's completely valid, and will remove need for a -1, but still keep such a link.
