### ISSUE TITLE
[0.8.0 Dev] Scales status check failing

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#504]
When I try to start my server I see this warning though I know scales is running
![serkprojects_-_manage_your_server_-_waterfox_2015-04-17_22-02-29](https://cloud.githubusercontent.com/assets/1880661/7213461/a45d8d02-e54d-11e4-9bba-b285ce2d3656.png)

**Comment by DaneEveritt** [comment]
Did you follow the link in that message to accept the SSL certificate?

**Comment by SonarBeserk** [comment]
Yep

**Comment by DaneEveritt** [comment]
What happens if you try to ping Scales from the server PufferPanel is running on. This error shows up when `Socket.IO` cannot connect to Scales, so either Scales isn't running, or there is a firewall issue.

**Comment by DaneEveritt** [comment]
I can't reproduce this error at all, any more details about it, perhaps errors from your browser console?
