### ISSUE TITLE
[0.8.0] ${jar} variable required but not required when creating a server

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#505]
You can make a server and not add this variable but Scales has a fit if you leave it out.

"No server jar is defined for {uuid}" is the resulting verbose message.

**Comment by DaneEveritt** [comment]
Ah yeah, thats an issue. Should get fixed soon with the addition of variables for different plugins that will show up when adding a server.

**Comment by DaneEveritt** [comment]
Issue has been fixed in a previous commit.
