### ISSUE TITLE
Error when I start the MC Server.

### ISSUE THREAD

**Issue by AlaDyn172** [PufferPanel/PufferPanel#506]
When I start the minecraft server it shows to me:

Unable to process your request. Please try again. Unable to start server (Cannot read property 'keys' of undefined)

The GSD is running:

> GameServerDaemon@0.1.4 start /srv/gsd
> node gsd.js

[INFO] Loading plugin bungeecord.js
[INFO] Loading plugin gmod.js
[INFO] Loading plugin minecraft.js
[INFO] Loading plugin tf2.js
[INFO] restify listening at http://0.0.0.0:8003

..? What is the problem :(

**Comment by DaneEveritt** [comment]
Sounds like GSD is running fine but the `config.json` file is a bit messed up for the server. Can you please paste in here and remove any keys or sensitive information (just insert random values for them).

To paste the `config.json` file neatly, paste the contents like so (removing the extra spaces in the ` ` `).

```
` ` `json
Contents
Here
` ` `
```

**Comment by AlaDyn172** [comment]
Now I have this error: 
> GameServerDaemon@0.1.4 start /srv/gsd
> node gsd.js

[INFO] Loading plugin bungeecord.js
[INFO] Loading plugin gmod.js
[INFO] Loading plugin minecraft.js
[INFO] Loading plugin tf2.js
[ERROR] FTP Server error

**Comment by AlaDyn172** [comment]
This is my config.json:
````````````````````````````
{
	"daemon": {
		"listenport": 8003,
		"consoleport": 8031
	},
	"tokens": ["14278465-6788-4695-ba3d-ca1410ab"],
	"interfaces":{
		"rest":{
			"authurl": "http://188.214.58.223/PufferPanel/panel/ajax/validate_download.php"
		},
		"console":{},
		"ftp":{
			"authurl": "http://188.214.58.223/PufferPanel/panel/ajax/validate_ftp.php",
			"port": 21,
			"host": "188.214.58.223",
			"use_ssl": true
		}
	},
	"servers": []
}
````````````````````````````

**Comment by DaneEveritt** [comment]
First things first, I edited out your token, you probably want to re-generate that since it just got posted publicly.

Aside from that, there don't appear to be any server installed in the system assuming that is the contents of your `config.json` (and not what is provided in the Admin Area). The FTP Server Error means that something else is running on port 21, either another FTP service, or you didn't properly exit GSD previously.

**Comment by AlaDyn172** [comment]
I had a config.json with my server but, the VPS had a problem and I need to reboot the VPS, and I didn't stopped the GSD, and after I rebooted the VPS, the GSD won't start, and appear a problem with a line. And I read from the internet when I have a problem with a line, I need to put the config.json which appear in nodes from the website to the FTP /srv/gsd/config.json and replace it.
And now I have the server in the PufferPanel, but config.json don't have the server registered.
Now I rebooted again the VPS for no appear again the error with FTP Service.


Now I deleted the server.. and I created other server, and now it working <3

My config.json is this:

```json
{
    "daemon": {
        "listenport": 8003,
        "consoleport": 8031
    },
    "tokens": [
        "AB"
    ],
    "interfaces": {
        "rest": {
            "authurl": "http://188.214.58.223/PufferPanel/panel/ajax/validate_download.php"
        },
        "console": {},
        "ftp": {
            "authurl": "http://188.214.58.223/PufferPanel/panel/ajax/validate_ftp.php",
            "port": 21,
            "host": "188.214.58.223",
            "use_ssl": true
        }
    },
    "servers": [
        {
            "name": "ABC",
            "user": "mc-deluxe_tib73",
            "overide_command_line": "",
            "path": "/home/mc-deluxe_tib73",
            "build": {
                "install_dir": "/mnt/MC/CraftBukkit/",
                "disk": {
                    "hard": 5120,
                    "soft": 4096
                },
                "cpu": 0
            },
            "variables": {
                "-Djline.terminal=": "jline.UnsupportedTerminal",
                "-Xmx": "12800M",
                "-jar": "craftbukkit.jar"
            },
            "keys": {
                "ABC": [
                    "s:ftp",
                    "s:get",
                    "s:power",
                    "s:files",
                    "s:files:get",
                    "s:files:put",
                    "s:files:zip",
                    "s:query",
                    "s:console",
                    "s:console:send"
                ]
            },
            "gameport": 25565,
            "gamehost": "188.214.58.223",
            "plugin": "minecraft",
            "autoon": false
        }
    ]
}
```
I edited the tokens :)

**Comment by DaneEveritt** [comment]
Cool, sounds like the file just got messed up at some point, glad you got it working.

**Comment by AlaDyn172** [comment]
Yeah now, the server is working and I can join it!
Thanks for the help !
