### ISSUE TITLE
 -bash: /etc/HASHFILE: Permission denied

### ISSUE THREAD

**Issue by BlueSoapTurtle** [PufferPanel/PufferPanel#508]
Hi.
During installation I was asked to run this command on my server
sudo echo "AAAAAAAAAAAAAAAAAAAAAAA" > /etc/HASHFILE
(replaced the real hash with AAA since I don't know if it should be kept secret)
and when I run it I get this error:  -bash: /etc/HASHFILE: Permission denied

Any suggestions? :)

**Comment by computerwizjared** [comment]
Try running "sudo su" and then "echo "AAAAAAAAAAAAAAAAAAAAAAA" > /etc/HASHFILE"

**Comment by BlueSoapTurtle** [comment]
Thanks!
Forgot about that command. :)
