### ISSUE TITLE
unable to Login to PufferPanel

### ISSUE THREAD

**Issue by BlueSoapTurtle** [PufferPanel/PufferPanel#509]
I finished the installation and ran the last 3 commands for installing
[$]~ rm -rf panel/install
[$]~ chmod -R 0755 src/core
[$]~ chmod 0444 src/core/configuration.php

now I'm just getting : "Oh snap! The username or password you submitted was incorrect."
even though I'm logging in with the account I just created
I used staff@localhost.com for the mail so I can't send a password reset ;_; and I don't think I've setup smtp to even send mail.

**Comment by computerwizjared** [comment]
PufferPanel requires a mail server to function correctly. I've been using Mandrill for emails, but there is a minor delay in the mail sending. I don't think that version 0.7.6.1 Beta supports SMTP either.

**Comment by BlueSoapTurtle** [comment]
hmm.. Any other solution than installing mail server? I'm using the same pass and login so it should work? o.o Unless it needed a confirmation email...

**Comment by LordRalex** [comment]
The default account does not need validation.
If you just installed it, then the *easiest* way is to do a re-install and redo it.

**Comment by BlueSoapTurtle** [comment]
I tried that and still without success

**Comment by LordRalex** [comment]
Please open up a connection to your database and validate that the account is in the "users" table with the correct email you specified and that it contains a hashed password in there.

**Comment by BlueSoapTurtle** [comment]
Yup. he's under pufferpanel>users
http://i.gyazo.com/cc2b20af8826d37584408a22b3e83fe5.png

**Comment by BlueSoapTurtle** [comment]
oh... Trying to login with staff as email ;_; might have to reinstall and use my own email for it....

**Comment by BlueSoapTurtle** [comment]
Nevermind, changed the email in phpmyadmin to my email and was able to log in,
Thanks for the help :)
