### ISSUE TITLE
"npm start" failing

### ISSUE THREAD

**Issue by BlueSoapTurtle** [PufferPanel/PufferPanel#510]
When I try and start the npm with "npm start" I get this error:

npm ERR! GameServerDaemon@0.1.4 start: `node gsd.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the GameServerDaemon@0.1.4 start script.
npm ERR! This is most likely a problem with the GameServerDaemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node gsd.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls GameServerDaemon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/gsd/npm-debug.log
npm ERR! not ok code 0

**Comment by Dylan3304** [comment]
Did you run `/srv/gsd` first?

**Comment by BlueSoapTurtle** [comment]
Yes.
full error(there also was one when running npm install)

root@MCDaemon1:/srv/gsd# npm install
npm WARN package.json trim@0.0.1 No repository field.
ftpd@0.2.11 node_modules/ftpd
└── dateformat@1.0.7-1.2.3

bukget@0.0.1 node_modules/bukget
├── qs@2.4.1
└── underscore@1.8.3

tar.gz@0.1.1 node_modules/tar.gz
├── commander@1.1.1 (keypress@0.1.0)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.7)
└── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.6, mkdirp@0.5.0, rimraf@2.3.2)
root@MCDaemon1:/srv/gsd# npm start

> GameServerDaemon@0.1.4 start /srv/gsd
> node gsd.js


module.js:485
    throw err;
          ^
SyntaxError: /srv/gsd/config.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:482:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/gsd/gsd.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! GameServerDaemon@0.1.4 start: `node gsd.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the GameServerDaemon@0.1.4 start script.
npm ERR! This is most likely a problem with the GameServerDaemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node gsd.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls GameServerDaemon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/gsd/npm-debug.log
npm ERR! not ok code 0

**Comment by DaneEveritt** [comment]
Your config file is wrong. Run its contents through a JSON parser.

**Comment by BlueSoapTurtle** [comment]
the package.json? or config.json. because the config.json is empty

**Comment by BlueSoapTurtle** [comment]
I tried creating a server which then gave me some code I put in the config.json and now it's working :)
Though now it says
"Unable to process your request. Please try again. Unable to start server (server.jar does not seem to be in the server directory!)"
When I try and start the server...

**Comment by BlueSoapTurtle** [comment]
Nevermind. got it to work. thanks for the help :+1:
