### ISSUE TITLE
Server is currently offline.

### ISSUE THREAD

**Issue by BlueSoapTurtle** [PufferPanel/PufferPanel#511]
When trying to start a new server I get this:
We were unable to connect to the main server, there may be network issues currently. This message will disappear when we are able to connect, you do not need to refresh.

When I now try and make a new server this pops up:
The GSD daemon running on the server is not on or is blocked by your firewall. Please make sure it is accessible before creating a server.

Any fixes?

**Comment by BlueSoapTurtle** [comment]
Never mind the server had shut down and I had to run
cd /srv/gsd
npm start

**Comment by Dylan3304** [comment]
1. Are you running PufferPanel and a node on the same machine?
2. Go to yougetsignal.com and punch in your node's IP and GSD ports, as well as the port you are running minecraft on. It should say "open" for each port. If not, then you have a firewall problem like the error said.

**Comment by BlueSoapTurtle** [comment]
Apparently after 2 minutes the message popped up again:
We were unable to connect to the main server, there may be network issues currently. This message will disappear when we are able to connect, you do not need to refresh.


And when running npm start this appears: 
[INFO] Loading plugin bungeecord.js
[INFO] Loading plugin gmod.js
[INFO] Loading plugin minecraft.js
[INFO] Loading plugin tf2.js
[INFO] restify listening at http://0.0.0.0:8003
[ERROR] FTP Server error
^Cmanager@MCDaemon1:/srv/gsd$ [INFO] Detected hard shutdown!
[INFO] Killing all running java processes on the server!
[INFO] All shutdown parameters complete. Stopping...

**Comment by Dylan3304** [comment]
Okay, disregard that.

**Comment by BlueSoapTurtle** [comment]
I added a group for the ftp that they have to be in to have access to ftp. though I haven't assigned the new users to that group. could that be causing it?
What user is running the server? Is the each "server user"?

**Comment by BlueSoapTurtle** [comment]
Did some testing and It's probably the ftp being broken...
I tried running parts of the install again and this propped up:
root@MCDaemon1:/srv/gsd# npm install
npm WARN package.json trim@0.0.1 No repository field.

**Comment by BlueSoapTurtle** [comment]
More testing:
root@MCDaemon1:/srv/gsd# netstat -tulpn | grep :21
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN      19048/node
udp        0      0 0.0.0.0:21943           0.0.0.0:*                           19048/node
root@MCDaemon1:/srv/gsd#

Does this mean that 2 programs are running on port 21?

Anyhow. I killed the proccess with "sudo kill -9 19048"(the PID)
and ran npm start, now it's just showing 

[INFO] Loading plugin bungeecord.js
[INFO] Loading plugin gmod.js
[INFO] Loading plugin minecraft.js
[INFO] Loading plugin tf2.js
[INFO] restify listening at http://0.0.0.0:8003

and I can't write any command, I'm guessing it's in some console mode?(how do I exit without gilling the npm?)

**Comment by DaneEveritt** [comment]
Ctrl + C is the `SIGINT` command, you are crashing npm every time you use it:

`^Croot@MCDaemon1:/srv/gsd# [INFO] Detected hard shutdown!`

You need to run the command in a program like `screen` if you want it to remain running in the background. You cannot enter raw commands into the console window for GSD, thats not how it works.

**Comment by BlueSoapTurtle** [comment]
Alright, will stop crashing it and run it in screen instead, thanks.

I tried running creating a new server and this appeared in the console:
[ERROR] Cound not execute command! useradd -m -d /home/servers/mc-temp_iajmm6d -s /bin/false mc-temp_iajmm6d
[ { [Error: ENOENT, mkdir '/home/servers/mc-temp_iajmm6d']
    errno: 34,
    code: 'ENOENT',
    path: '/home/servers/mc-temp_iajmm6d' } ]

I'm guessing it could be a problem with permissions. What user gets assigned to running these commands? I'm guessing the one used to install it, so in my case "manager".

**Comment by DaneEveritt** [comment]
Does `/home/servers` exist?

**Comment by BlueSoapTurtle** [comment]
Apparently I didn't have that directory. I created it and ran sudo npm start

After pressing start on the panel this appears:


fs: missing callback Error: ENOENT, open '/home/servers/mc-temp_iajmm6d/server.properties'
Segmentation fault (core dumped)

npm ERR! GameServerDaemon@0.1.4 start: `node gsd.js`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the GameServerDaemon@0.1.4 start script.
npm ERR! This is most likely a problem with the GameServerDaemon package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node gsd.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls GameServerDaemon
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /srv/gsd
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /srv/gsd/npm-debug.log
npm ERR! not ok code 0
root@MCDaemon1:/srv/gsd#

and here's the npm-debug.log file: http://hastebin.com/inerepesiz.log

**Comment by DaneEveritt** [comment]
You need to just reinstall the entire program, and start with fresh servers in PufferPanel. These bugs are not normal, and seem to be caused by either corrupted files, or some really un-intended use of the system.

**Comment by BlueSoapTurtle** [comment]
Alright, will reinstall it. GSD... What would I use instead then? and how do I uninstall the program / GSD without having to reinstall the whole server?

**Comment by computerwizjared** [comment]
Here's the documentation for v0.8.0: http://www.pufferpanel.com/v0.8.0/docs/getting-started

**Comment by BlueSoapTurtle** [comment]
I might have read some other documentation. will just reinstall all of. 
Thanks for all the help!

**Comment by computerwizjared** [comment]
Well, v0.8.0 is not officially out yet, so have caution while using it. v0.7.6 (http://www.pufferpanel.com/v0.7.6/docs/how-to-install) is probably what you were following, which uses GSD instead of Scales.

**Comment by DaneEveritt** [comment]
There is no upgrade from `0.7.6` to `0.8.0` anyways, so at this point you are better off installing `0.8` since we don't have any major changes left before release. At this point we are just beta testing it, and fixing any minor bugs or display things that crop up.

**Comment by computerwizjared** [comment]
@DaneEveritt If there are minor updates to 0.8, will we have to completely reinstall to get them? Or can we just run a command to get them?

**Comment by Dylan3304** [comment]
**To update, you need to run:**
`cd /var/www/pufferpanel/`
`git fetch`
`git merge origin/master`

**For Scales:*
`cd /srv/scales/`
`git fetch`
`git merge origin/master`

**Comment by DaneEveritt** [comment]
What @Dylan3304 said is correct, keep an eye on the Tools Repo to make sure there aren't any SQL updates as well (there shouldn't be though).

**Comment by Dylan3304** [comment]
@DaneEveritt, I'm curious on how to apply the SQL migrations... Any input on that?

**Comment by DaneEveritt** [comment]
Manually. Its not an official release yet, so if you install it and there are changes it's up to you to make those changes. :+1:

**Comment by Dylan3304** [comment]
No, like little dev SQL migrations. Like the commit you made yestersay on the tools repo. Best what to apply that @DaneEveritt?

**Comment by DaneEveritt** [comment]
You'll have to just manually update your database to match. I'm not providing little update anippets for those things, regardless there most likely will not be any updates to the SQL structure.
