### ISSUE TITLE
GSD crashes when 'autoon' is enabled

### ISSUE THREAD

**Issue by RunasSudo** [PufferPanel/PufferPanel#512]
See [Google web cache of gametainers/GSD issue 35](http://webcache.googleusercontent.com/search?q=cache:https://github.com/gametainers/gsd/issues/35)

Using GSD 0.1.4

"When autoon is set to true, startup crashes with this stack

```
TypeError: undefined is not a function
at GameServer.turnon (/srv/gsd/services/gameprocess.js:149:2)
at initServer (/srv/gsd/services/index.js:16:18)
at data (/srv/gsd/services/index.js:6:2)
at Array.forEach (native)
at Object. (/srv/gsd/services/index.js:5:29)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

Which makes sense because initServer calls turnon with no arguments and that function expects a callback."

"Hi

I have same problem, I solved this by editing the file `/srv/gsd/services/gameprocess.js`
and added // in front of the line 147 from to disable the line
`// callback();`

now the autoon function works :-)
however I dont know if this gives any other problemes, but currently I have not seen any."

"It's probably safer to modify the services/index.js and change turnon() to turnon(function () {})"

**Comment by DaneEveritt** [comment]
Closing this because we have moved away from GSD and it is no longer being maintained. Scales does not implement an auto-on options anyways, so it is not something that would apply to that program anyways.

The change you made shouldn't really have any effect on the program as far as I know though.
