### ISSUE TITLE
Installer: Set the MySql Port

### ISSUE THREAD

**Issue by Blackbird1604** [PufferPanel/PufferPanel#513]
Is there any method to set the Mysql Port?

**Comment by Wargog** [comment]
After the it asks for the IP of the SQL server, try using `:[PORT]` replacing [PORT] with your port you have.

**Comment by LordRalex** [comment]
Which installer are you referring to?

**Comment by Blackbyte1604** [comment]
I followed this Tutorial: http://www.pufferpanel.com/v0.8.0/docs/getting-started

**Comment by Blackbyte1604** [comment]
"After the it asks for the IP of the SQL server, try using  :[PORT]  replacing [PORT] with your port you have." Didnt work for me

**Comment by LordRalex** [comment]
The installer does not work when it is not on the standard port, but since the installer is bash, you can directly edit it.
https://github.com/PufferPanel/Tools/blob/master/installer/installer#L149

Alter that line so something like the following, where 3307 is your new port
    if mysql -h ${mysqlhost} -P 3307 -u ${mysqluser} -p${mysqlpass} -e "exit"; then

**Comment by Blackbyte1604** [comment]
Hm yearh but this doesnt work for PufferPanel, PufferPanel wont connect without the Port

**Comment by DaneEveritt** [comment]
Change [this line](https://github.com/PufferPanel/PufferPanel/blob/master/public/router.php#L54) to be:

```php
'connection_string' => 'mysql:host='.Config::config('mysql')->host.';port=3307;dbname='.Config::config('mysql')->database,
```

**Comment by LordRalex** [comment]
Closing this now as it is supported within the panel's config.json file, and is now just an installer enhancement.

**Comment by DaneEveritt** [comment]
Pretty sure it isn't added within the PDO connection string yet.

**Comment by LordRalex** [comment]
Swore I added it in, well, now I did.
