### ISSUE TITLE
Problem while creating new server [v0.8.0]

### ISSUE THREAD

**Issue by computerwizjared** [PufferPanel/PufferPanel#514]
This happens when I go to create a server:
![image](http://i.gyazo.com/b760d30545b6b3179eb18a66f88bfea8.png)
If you will note, a server location is selected, but the "Location Node" dropdown hasn't recognized the location selection. I have verified that I have nodes in that location added and running. If I scroll down and click "Create Server", it will fail to create the server, but will populate the list of nodes. Then I will be able to create the server.

**Comment by DaneEveritt** [comment]
Do you have multiple locations or nodes by chance? Haven't seen this issue occur before.

Can you check your browser console (Right Click -> Development Tools (or similar)) and see if any errors are logged?

**Comment by computerwizjared** [comment]
No, actually I am only running this on a single node at the moment. I don't have any additional locations or nodes added other than the local one. There are no errors in the console.
