### ISSUE TITLE
Server power controls

### ISSUE THREAD

**Issue by Phroa** [PufferPanel/PufferPanel#516]
It might just be me, but I have a few minor suggestions for this area
![image](https://cloud.githubusercontent.com/assets/6373176/7405951/5db71ace-eeaf-11e4-9c54-747f79354458.png)

- I'm not sure I would show the "stop", "kill", "pause", and "restart" buttons when the server is offline.
- If the stop button is red, I'd make the start button green.

**Comment by Dylan3304** [comment]
+1 these would take less than 60 seconds to implement.

**Comment by Dylan3304** [comment]
I'd rather just have the aforemetioned buttons greyed out, and the kill link not shown at all.

**Comment by worldmc** [comment]
I disagree there,  the kill button is a nice feature.

**Comment by Dylan3304** [comment]
I mean just remove it completely when the server is OFFLINE.

On Mon, May 4, 2015 at 6:18 AM, Arjo <notifications@github.com> wrote:

> I disagree there, the kill button is a nice feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PufferPanel/PufferPanel/issues/516#issuecomment-98680229>
> .
>



-- 
-------------------------------
Dylan Seidt
http://minewrath.com
dylan.seidt@gmail.com

**Comment by worldmc** [comment]
Well,  Im not saying that this would happen but what if scales sees the server as offline and its still running?  You dont remove a cars gearbox when its not turnt on.

**Comment by DaneEveritt** [comment]
If Scales sees the server as offline the kill button won't even do anything.

**Comment by Wargog** [comment]
Or simply put the `disabled` tag on it in pure HTML, not that hard. Give Dane a break, jeez.

**Comment by Dylan3304** [comment]
@Wargog its not that easy. You need to write an AJAX query to scales to see if its online.

**Comment by DaneEveritt** [comment]
That's already being done on those pages, and there is a websocket on all pages listening for server events.

**Comment by Phroa** [comment]
I think 6c6099f closed this

**Comment by Dylan3304** [comment]
@Phroa they didn't merge that. I'll revisit it later.

**Comment by Phroa** [comment]
Oops.
