### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by XxSkydevil06xX** [PufferPanel/PufferPanel#519]
I Know This Isn't A Bug But It Does Not Support Windows 8.1 And Installing Ubuntu Is Hard Please Someone Do It For Me Email: jasoncornwall06@gmail.com Website: luckymc.boards.net

**Comment by computerwizjared** [comment]
Sorry, but I don't think PufferPanel will work on Windows very well, if at all. If you cannot install Ubuntu, you probably will not be able to install PufferPanel correctly.

**Comment by LordRalex** [comment]
The issue is not the panel, it is the dependencies. If you can get them to install on Windows 8.1, the panel can run on it. 

If you cannot do that, install a VM. If you cannot do that, get a VPS. If you cannot do that, this panel is just not for you.

We do not install it for others.
