### ISSUE TITLE
Donation Support

### ISSUE THREAD

**Issue by Shybella** [PufferPanel/PufferPanel#520]
Do you guys have a donation link setup? Would love to help!

I couldn't seem to find one unless I'm blind. lol

**Comment by puffrfish** [comment]
We do not accept donations. However, thank you for your support!

**Comment by Dylan3304** [comment]
@puffrfish Do you have a problem if I send the devs a live Puffer Fish?

**Comment by Shybella** [comment]
![PufferFish](http://forumcinemaslv.blob.core.windows.net/1012/Event_5556/gallery/fdf0cc383c.jpg)
