### ISSUE TITLE
BukGet Plugin Installation Support

### ISSUE THREAD

**Issue by computerwizjared** [PufferPanel/PufferPanel#522]
Just some more of my two cents: It would be great if you could add BukGet support so that we could easily download plugins and updates for them. I understand PufferPanel is headed towards a full game server control panel, but it still would be an awesome side feature for Bukkit/Spigot specifically. I also understand that there will be a Sponge plugin API in the future... maybe that could be implemented as well? Thanks!

**Comment by DaneEveritt** [comment]
This will not be implemented currently, especially not without module support.

In the future when we add game modules that can be configured and controlled front-end we might consider adding this. For now, it is adding a very specific feature that takes the panel back to supporting a very specific game.

**Comment by BlameDylan** [comment]
@DaneEveritt @LordRalex @puffrfish do you think the best way to do this would be to detect if the plugin is Minecraft, then output a second tab in the File Manager?

**Comment by puffrfish** [comment]
@BlameDylan We don't plan to implement or include this, especially with work on 0.9.0 starting soon.
