### ISSUE TITLE
Invalid FQDN on Node

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#524]
Hello,
I'm having some trouble using the FQDN. If I use my IP address, the node works fine and dandy. However, I want to use a domain such as, `node.google.com`, instead of `10.0.1.2`. When I input my own FQDN, I see this error:
```
The node Fully Qualified Domain Name is not valid. Domains must resolve to a non-reserved IP.
```
**Any ideas?** Please let me know if there are any logs I could provide.

**Comment by computerwizjared** [comment]
Is your hosts file resolving your domain name to 127.0.0.1? That's the only thing that I could think of :/

**Comment by Dylan3304** [comment]
@computerwizjared how could I check this?

**Comment by computerwizjared** [comment]
Run `sudo nano /etc/hosts` and post the contents (although if you recognize your public IP, obviously blot it out or something)

**Comment by Dylan3304** [comment]
So basicly the vhosts file?

**Comment by Dylan3304** [comment]
Okay, however I don't have a typical apache setup.

**Comment by computerwizjared** [comment]
I'm not talking about apache. Your server may be routing yourdomain.com to 127.0.0.1 instead of your public IP.

**Comment by computerwizjared** [comment]
Are you running the node locally or on a separate server?

**Comment by Dylan3304** [comment]
Will do when I get home. I'm running the panel on OVH VPS, and node on a Dedi.

**Comment by computerwizjared** [comment]
Oh, sorry... I assumed you were running it locally. Your hosts file won't make a difference then, as it probably wouldn't have anything related to the server running the node. Please disregard what I've said above. The only other reason would be if you are running the dedi in a private network with your VPS and accessing it using an internal IP, but it doesn't seem like that's the case. Sorry that I haven't been very helpful.

**Comment by Dylan3304** [comment]
@computerwizjared its okay. Maybe @DaneEveritt would have some insight?

**Comment by DaneEveritt** [comment]
What is the FQDN that you are entering (paste exactly what you are entering)?

**Comment by Dylan3304** [comment]
`s1.minewrath.com`

**Comment by Dylan3304** [comment]
Input on this would be nice :). @DaneEveritt

**Comment by puffrfish** [comment]
Hi @Dylan3304. If you could please stop pinging (@mentioning) the developers we would really appreciate it. Other developers are looking into this issue as it might be related to #525. Thank you for your patience.

**Comment by Dylan3304** [comment]
Sorry, it is a bad habit... I've been asked before to stop, but I keep forgetting. My bad.

**Comment by DaneEveritt** [comment]
There is no reason why this error would be showing up when editing a node unless you were entering a FQDN that did not resolve to a non-reserved address.

`FILTER_FLAG_NO_RES_RANGE`
> Fails validation for the following reserved IPv4 ranges: 0.0.0.0/8, 169.254.0.0/16, 192.0.2.0/24 and 224.0.0.0/4. This flag does not apply to IPv6 addresses.

I just tested it with your FQDN `s1.minewrath.com` and it worked fine.

**Comment by Dylan3304** [comment]
![screen shot 2015-05-02 at 8 51 08 pm 2](https://cloud.githubusercontent.com/assets/2935060/7443399/094ca552-f10d-11e4-97fb-7fa069f3eaae.png)
I am entering `s1.minewrath.com`

**Comment by DaneEveritt** [comment]
![](http://s3.kelp.in/ZYIQK.png)

**Comment by Dylan3304** [comment]
What is going on?

**Comment by DaneEveritt** [comment]
What happens if you do:

`traceroute s1.minewrath.com` on your server?

**Comment by Dylan3304** [comment]
```
[root@admin ~]# traceroute s1.minewrath.com
s1.minewrath.com: Name or service not known
Cannot handle "host" cmdline arg `s1.minewrath.com' on position 1 (argc 1)
```

**Comment by DaneEveritt** [comment]
Can you ping it at all? It looks like something isn't working correctly on your server, could be the firewall is blocking outgoing connections, try turning it off completely and trying again.

**Comment by Dylan3304** [comment]
```
[root@admin ~]# service iptables stop
Redirecting to /bin/systemctl stop  iptables.service
Failed to issue method call: Unit iptables.service not loaded.
```
**IpTables** isn't installed...

**Comment by Dylan3304** [comment]
Changed /etc/resolv.conf from:
```
search ovh.net
nameserver 127.0.0.1
nameserver 213.186.33.99
```
**To:**
```
nameserver 208.67.222.222
nameserver 208.67.220.220
```
And rebooted the VPS. It worked! Issue resolved.

**Comment by DaneEveritt** [comment]
Figured it was a networking issue, which might explain why you were having issues with SSL, did this happen to fix those issues as well?

**Comment by Dylan3304** [comment]
Something else fixed the SSL issue a few days ago.
