### ISSUE TITLE
Packages? Modpacks? Need some help!

### ISSUE THREAD

**Issue by Dylan3304** [PufferPanel/PufferPanel#528]
Hello,
1. I'm wondering if the mod-packs are basically "packages". When will custom packages be implemented?
2. I know how you can build a server with Sponge/Forge/etc, but could you allow users to wipe their server and install it fresh?
3. How do I make my own custom build packages? Or will this be done with the build variables?

**Basically,** how will installing mod-packs or what ever you want to call them work? Could users edit their own mod-pack?

**Comment by DaneEveritt** [comment]
1. Soon™
2. Soon™
3. You don't. We haven't decided how we will be handling this, when they are implemented you will know.

**Comment by DaneEveritt** [comment]
(also, please keep non-bug discussion out of Github. Use the support part of the PufferPanel website)
