### ISSUE TITLE
NPM start FTP Server error

### ISSUE THREAD

**Issue by TNSPredator** [PufferPanel/PufferPanel#529]
Hello when issuing cd /srv/gsd and then npm start the server loads but says there is a FTP Server Error. This is not causing me any issues but I was wondering how I would get rid of this error message?

**Comment by computerwizjared** [comment]
Are you running another FTP server on your node? (By the way, I'm not sure that we support `0.7.6` anymore)

**Comment by TNSPredator** [comment]
Ah yes I am running proftpd. Also what versions are now supported (whats the lasted version)?
Thanks!

**Comment by computerwizjared** [comment]
`0.8.0` is the latest. You can find documentation here: http://www.pufferpanel.com/v0.8.0
0.8.0 uses SFTP, through SSH, so you don't have to modify your existing FTP setup.

**Comment by TNSPredator** [comment]
Ah okay great! Is there a way to update from 0.7.6?

**Comment by computerwizjared** [comment]
No, sorry, you have to re-install :/
