### ISSUE TITLE
Web interface messed up

### ISSUE THREAD

**Issue by TNSPredator** [PufferPanel/PufferPanel#530]
Hello
So I followed all of these steps:  http://www.pufferpanel.com/v0.8.0/docs/getting-started but when I go to IP/PufferPanel this is what I can see:
![image](https://cloud.githubusercontent.com/assets/9033887/7447217/6b4b8344-f1ea-11e4-99f3-78a7880fd7e3.png)

**Comment by DaneEveritt** [comment]
It would appear that something got messed up while setting URLs. Go ahead and follow the link to the admin CP, and then URL Settings. Make sure that the URLs start with `http://` for everything.

pinging @LordRalex or @puffrfish for the installer which needs to patch this.

**Comment by TNSPredator** [comment]
Thanks!

**Comment by DaneEveritt** [comment]
Closed in af30141107c3177238c118acff6b8bb045b82c7d
