### ISSUE TITLE
Bungeecord Installing

### ISSUE THREAD

**Issue by Blackbyte1604** [PufferPanel/PufferPanel#531]
Hi,

im not able to install Bungeecord.
The Installer Progress says finished but im not able to Access the Server in the Control Panel.

**Comment by puffrfish** [comment]
For installation and configuration help, please ask your question on our [Community Forums](https://community.pufferpanel.com). Make sure to provide the log inside /srv/scales/logs. Thanks!

(I have tested and this is working properly in the latest release)
