### ISSUE TITLE
Can't add existing subuser accounts

### ISSUE THREAD

**Issue by Ninn0x4F** [PufferPanel/PufferPanel#533]
When i'm adding existing subusers e.g. core2@localhost to an existing server e.g. srvcore1 it's showing up "Something appears to have gone wrong when trying to add this subuser. Please try again."
Also the same happens when i'm trying to add an non-existent user e.g. core3@localhost to the server.

**Comment by DaneEveritt** [comment]
Being triggered by https://github.com/PufferPanel/PufferPanel/blob/master/src/core/routes/node/users.php#L47
