### ISSUE TITLE
impossible installer 

### ISSUE THREAD

**Issue by MrPalamen** [PufferPanel/PufferPanel#535]
Msg Erreur:

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files
-----
Executing panel version installer
SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
An error occured while installing, halting

**Comment by puffrfish** [comment]
For future notice, installation help should go in the [forums](https://community.pufferpanel.com).

> SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

It appears you are using the wrong password for your MySQL server. This was the password you set when you installed MySQL.

If you have further questions, please open up a thread on the forums. Thanks!

**Comment by MrPalamen** [comment]
c'est quoi l'os qui le plus optimiser ?

**Comment by puffrfish** [comment]
We recommend using Ubuntu 14.04 Server. The guide located [here](http://www.pufferpanel.com/v0.8.0/docs/getting-started) has all the instructions you need to install PufferPanel on Ubuntu.

**Comment by MrPalamen** [comment]
nginx ou Apache pour le serveur Web ?

**Comment by puffrfish** [comment]
nginx is recommended as we have an example config file for it.

**Comment by MrPalamen** [comment]
Merci

**Comment by MrPalamen** [comment]
a la fini de installer mysql la une erreur:

Errors were encountered while processing:
 mysql-server-5.5
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by puffrfish** [comment]
I can't say for sure what the cause is, but try running `apt-get purge mysql-server` and then `apt-get install mysql-server` again. If that does not work, I would suggest searching the error you are receiving and trying some of the solutions that are posted on various forums.
