### ISSUE TITLE
Panel doesnt detect bungeecord running

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/PufferPanel#540]
When starting a bungeecord, the panel shows me memory and cpu usage as well as the console but the dot indicating the status of the server is still red.
![14](https://cloud.githubusercontent.com/assets/4009269/7680913/8aa3e7c2-fd6b-11e4-8eb6-27810fe684ce.PNG)

**Comment by Omeryl** [comment]
The dot sometimes doesn't update, did you try refreshing the page?

**Comment by Paktosan** [comment]
Yes, of course I tried refreshing the page. Also in the server list the dot still is red.

**Comment by DaneEveritt** [comment]
I wonder if Scales didn't detect the server as being fully started since it checks for a specific line in the output. I'll look into this in a bit, but I haven't encountered this issue yet.

**Comment by DaneEveritt** [comment]
Actually, can you also check your Scales and PufferPanel error logs and see if anything is being reported in them?

**Comment by DaneEveritt** [comment]
Just tested this and I cannot reproduce this issue. Are you positive that your BungeeCord server is actually finishing startup and not encountering an error at some point?

**Comment by Omeryl** [comment]
I was testing as well and as Dane I was unable to reproduce with my
production bungee cord.

**Comment by Paktosan** [comment]
I validated again that my bungeecord is working by simply joining it. Here are all logs you may need:

**Comment by DaneEveritt** [comment]
The logs for the panel are located in /bar/www/PufferPanel/src/logs.

**Comment by Paktosan** [comment]
So here is my panel log: http://paste.ubuntu.com/11265545/

**Comment by Paktosan** [comment]
Anything new on this? @DaneEveritt

**Comment by LordRalex** [comment]
@Paktosan can you fix your pastes to use something like gist so they are not lost in time?

**Comment by Omeryl** [comment]
I still can't reproduce this on HEAD.

**Comment by computerwizjared** [comment]
I am running a "production" BungeeCord (depends on your definition of production), and cannot reproduce this. Everything is running very smoothly.

**Comment by Omeryl** [comment]
Well I meant production puffer panel install. Oops heh.

**Comment by xion87** [comment]
for me it dont connect :(
