### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by XxSkydevil06xX** [PufferPanel/PufferPanel#544]
How Do I Set The Permissions On The Configuration File To 0444 And I Got A Failed CHMOD Checks Saying 

/src/core is improperly CHMOD'd. It should be 0777.

/src/cache is improperly CHMOD'd. It should be 0777.

/panel/install/install is improperly CHMOD'd. It should be 0777.

/panel/install/install/do is improperly CHMOD'd. It should be 0777.

Please Show Me Your 0.7.6.1 Beta Code So I Can Fix This

Note: I Know 0.7.6.1 Support Is Close But It Is Easy To Install

**Comment by Dylan3304** [comment]
I understand your concerns. However, 0.7.6 is fully of security bugs, and is lacking several features that 0.8.0 has. It really isn't hard to install, when you put it in context. **However,** to answer your question, you'll need to:
```
cd /path/to/pufferpanel/
chmod 0777 /src/core

**Comment by XxSkydevil06xX** [comment]
It Worked! Thanks :)

**Comment by LordRalex** [comment]
We do not support old versions. If there are issues with the new panel or installer, please report those instead of trying to run old versions.
