### ISSUE TITLE
Installer broken see commit

### ISSUE THREAD

**Issue by ET-Bent** [PufferPanel/PufferPanel#546]
The installer for puffer panel is broken, please review https://github.com/PufferPanel/Tools/commit/b375bd78519808d42c59732487151fd234f24c25

**Comment by LordRalex** [comment]
Don't make issues like this, it does nothing to help.

**Comment by ET-Bent** [comment]
Sorry I just wanted to get this fixed as soon as possible because this broke the whole installer.

**Comment by puffrfish** [comment]
It was already merged. See your PR.

**Comment by ET-Bent** [comment]
Jup saw that seconds after opening the issue.
