### ISSUE TITLE
Implementing a scheduler

### ISSUE THREAD

**Issue by aadeg** [PufferPanel/PufferPanel#551]
I used to use Multicraft and the lack of a scheduler is unfortunately a negative point for PufferPanel. It is important for a user to have a way to have scheduled commands that will be run on one server whenever it's needed. 
If you can implement it in the future updates, PufferPanel will become a real competitor of the no-opensource server managers.

Thank you very much.

**Comment by puffrfish** [comment]
I would also like to see this.
Duplicate of #474, closing.
