### ISSUE TITLE
MOTD Converted to section symbols (§)

### ISSUE THREAD

**Issue by Mstrodl** [PufferPanel/PufferPanel#552]
When using a formatting code in server.properties the '\u00A7' is changed to a '§' at startup (by PufferPanel) which in turn is converted (by Minecraft) to '\u00C2\u00A7'.

The line in question before startup:
```
motd=\u00A7k\u00A7d\u00A7l000\u00A7r \u00A74\u00A7nMy Minecraft Server\!\u00A7r \u00A7k\u00A7d\u00A7l000\u00A7r
```
And after startup:
```
motd=\u00C2\u00A7k\u00C2\u00A7d\u00C2\u00A7l000\u00C2\u00A7r \u00C2\u00A74\u00C2\u00A7nMy Minecraft Server\!\u00C2\u00A7r \u00C2\u00A7k\u00C2\u00A7d\u00C2\u00A7l000\u00C2\u00A7r
```
The interesting thing is that if I catch it *before* Minecraft converts it is that the file reads:
```
motd=§k§d§l000§r §4§nMy Minecraft Server\!§r §k§d§l000§r
```
However, It does not do this if I replace '\u00A7' with '\\\u00a7' but Minecraft shows '\\\u00a7mWaffles' as '\u00a7mWaffles' instead of '~~Waffles~~'

**Comment by Omeryl** [comment]
Hmm, this is an invalid bug for this. It should be opened at PufferPanel/scales instead.

**Comment by SonarBeserk** [comment]
If you dont mind my asking, why not use the typical &# style of formatting codes in any case?

**Comment by Mstrodl** [comment]
I didn't know they existed
