### ISSUE TITLE
When HTTPS is required, subusers doesnt work

### ISSUE THREAD

**Issue by turtledude01** [PufferPanel/PufferPanel#555]
If the setting to require secure is checked, the email sent to a user for them to register as a subuser sends them a link with HTTP instead of HTTPS, causing the link to fail and the user cannot register, but replaceing the HTTP with HTTPS causes it to work.

**Comment by BlameDylan** [comment]
Is your master URL using `https://`? I don't think this is a panel bug ;)

**Comment by turtledude01** [comment]
@BlameDylan Thanks, that was the problem, But to help out with this, there should be a note next to the require https option saying to make sure the master URL needs to be changed for all functions to work.

**Comment by BlameDylan** [comment]
Okay, I'll see what I can do.

**Comment by DaneEveritt** [comment]
The `HTTPs Enabled` selection should ideally trigger a check to ensure that the urls use `https` not `http` as well.

**Comment by BlameDylan** [comment]
That is a good idea @DaneEveritt. By the way, I thought you were gone all summer lol.

**Comment by Omeryl** [comment]
I'm tackling this right now, will send a PR shortly :).
