### ISSUE TITLE
Pufferpanel creates no sftp user

### ISSUE THREAD

**Issue by majoess** [PufferPanel/PufferPanel#557]
Hello,
my "sponsoring" customers have the problem the cant connect via sftp. in FileZlla theres everytime incorrect...

I dont know what i should do

**Comment by majoess** [comment]
ok i fixed it. But i have always in FileZilla the error: Software caused connection abort

**Comment by Omeryl** [comment]
Can you get us any relevant logs? /var/log/secure to /var/log/auth last few lines when you try to authenticate (try 100 or so). The user is definitely created if the server runs.
