### ISSUE TITLE
After some crash, start the server is impossible. Add a way to kill its port!

### ISSUE THREAD

**Issue by ImMaury** [PufferPanel/PufferPanel#561]
Hi there,

I think you all know the the fateful error "**FAILED TO BIND TO PORT**!".
It happens when two or more services (often Minecraft servers) runs on the same port.

This error afflicts Scales too: when a server crashes, Scales may starts a new one, even if the server's port is occupied by the crashed server (the button "kill it" seems not working).

For this purpose, Multicraft Panel has added a feature that allow you to run a certain script directly with the console command input:
```
builtin:script <name>	Runs the script "name". The script has to be defined in the scripts.conf file
```
In that script, for example, you can insert the bash command:
```
fuser -n tcp -k $server_port
```
Where *$server_port* is a variable that points to the server port.

What about adding this features to PufferPanel? (Or, at least, fixing the "kill it" command!)

**Comment by Omeryl** [comment]
Already reported. I'm against this solution because it would be better to fix the root problem, not the symptoms. 

Also, this probably won't work too well because the process is a zombie, and wouldn't respond to being killed like this. 

https://github.com/PufferPanel/Scales/issues/22

**Comment by LordRalex** [comment]
I am going to close this, because the root issue this is wanting to fix needs to be tackled at the source. We don't need to have some "workaround" for an external service that we have access to code for (not to mention this would be a ton of work to implement)
