### ISSUE TITLE
Language files should use a standard delimiter

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#563]
The use of a , is a poor choice for a delimiter. This should either be a | or a =. All raw files need to be updated and the builder-script needs to be updated.

**Comment by Omeryl** [comment]
Is this relevant anymore with PufferPanel using Transifex now? https://www.transifex.com/projects/p/pufferpanel/

**Comment by puffrfish** [comment]
Closing since we use Transifex now.
