### ISSUE TITLE
Spaces in fields get replaced with +

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#565]

**Comment by BlameDylan** [comment]
I see this issue on the server creation page. Could you tell me where else you have seen this?

**Comment by SonarBeserk** [comment]
Only there actually. Didnt comment on where it might be as im not fully sure if there is anywhere else you can find it.

**Comment by turtledude01** [comment]
This only happens for me if i click "Create server" and it gives an error about a field being incorrect.

**Comment by Omeryl** [comment]
I'll take a tackle at this.
