### ISSUE TITLE
Figure out why the installation flag doesnt change after server install

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#577]
Ive noticed, as have many others that when installing the "installed" flag does not change from 0 to 1 even when installation is finished.

**Comment by turtledude01** [comment]
Had this problem, Did a fresh install of the panel (Backing up database of course) and fixed it.  
Note: Reinstalling the panel forced me to restart each scales node.

**Comment by puffrfish** [comment]
I can't seem to reproduce this. Closing for now.

**Comment by DaneEveritt** [comment]
If the flag isn't changing then there is an issue somewhere in the communication between Scales and PufferPanel that is telling the panel that the server is installed. There should be something logged if it isn't being changed.

**Comment by BlameDylan** [comment]
Okay, I did a fresh test of it, and deleted all my logs beforehand, so nothing would interfere. However, nothing was logged on **PufferPanel** nor **Scales**. I really don't know what is going on. Is there anything else I can provide?
