### ISSUE TITLE
6 digit ports

### ISSUE THREAD

**Issue by noorkoteb** [PufferPanel/PufferPanel#578]
for some reason all of my ports are 6 digits http://gyazo.com/538ccf89ba6f40e8855202c31d317c11

**Comment by puffrfish** [comment]
Could you please supply the line you used when setting up the node? The 127.0.0.1|25565,25566 line. Thanks

**Comment by LordRalex** [comment]
This looks like your input contained an extra number. I do not see anything that says there's an actual bug. If you can replicate the issue with a truly 5-digit number, then please reply with the lines that you used.
