### ISSUE TITLE
Power control stop and start doesn't work

### ISSUE THREAD

**Issue by idkw** [PufferPanel/PufferPanel#581]
I'm trying to use the api to stop and start my servers. However only `kill` and `restart` work. But `stop` and `start` have no effect.

**Doesn't work**
curl -k -H "X-Access-Token: xxxxxxxxxxx" -H "X-Access-Server: xxxxxxxxxxxx" https://xx.xx.xx.xx:5656/server/power/start

**Doesn't work**
curl -k -H "X-Access-Token: xxxxxxxxxxx" -H "X-Access-Server: xxxxxxxxxxxx" https://xx.xx.xx.xx:5656/server/power/stop

**Works**
curl -k -H "X-Access-Token: xxxxxxxxxxx" -H "X-Access-Server: xxxxxxxxxxxx" https://xx.xx.xx.xx:5656/server/power/kill

**Works**
curl -k -H "X-Access-Token: xxxxxxxxxxx" -H "X-Access-Server: xxxxxxxxxxxx" https://xx.xx.xx.xx:5656/server/power/restart

**Comment by BlameDylan** [comment]
I've been able to utilize the API to start/stop servers. Have you changed your query to:
`https://xx.xx.xx.xx:5656/server/power/start` and/or `https://xx.xx.xx.xx:5656/server/power/stop`? 

**Note that the stop/start queries may take a little while, depending on what Scales has to start on the server.**

Let me know if this helps at all.

**Comment by idkw** [comment]
Change to what ? It's the same as I've writtent. I don't understand.
Also, nothing happens, even after a few minutes.

**Comment by Omeryl** [comment]
What version of Scales and PufferPanel are you running?

**Comment by idkw** [comment]
Puffer Panel 0.8.1 Beta
And for scales I don't know how to get it

**Comment by Omeryl** [comment]
Please update both scales and puffer panel to their latest versions. The latest Panel is 0.8.2 and the latest scales is 0.1.3.

**Comment by idkw** [comment]
Thanks for the answer.
I followed the instructions here to update https://community.pufferpanel.com/topic/125-pufferpanel-v082-beta-scales-v013/#comment-557

It was successful with no errors.

However, now, after the update .I can't control the servers from the panel anymore.

What should I do ?

Scales log after update : 

```
23:10:02 - info: + ========================================== + meta=undefined
23:10:02 - info: | Scales logs all information, (inc. errors) | meta=undefined
23:10:02 - info: | into the logs/ directory. Please check     | meta=undefined
23:10:02 - info: | there before asking for help with bugs.    | meta=undefined
23:10:02 - info: |                                            | meta=undefined
23:10:02 - info: | Submit bug reports at the following link:  | meta=undefined
23:10:02 - info: | https://github.com/PufferPanel/Scales      | meta=undefined
23:10:02 - info: + ========================================== + meta=undefined
23:10:02 - info: Loading plugin bungeecord.js... meta=undefined
23:10:02 - info: Loading plugin mcserver.js... meta=undefined
23:10:02 - info: Loading plugin minecraft-pre.js... meta=undefined
23:10:02 - info: Loading plugin minecraft.js... meta=undefined
23:10:02 - info: Loading plugin srcds.js... meta=undefined
23:10:02 - info: Scales is now listening on port 5656 meta=undefined
23:10:02 - info: Scales is now listening to Socket.IO on port 5657 meta=undefined
23:10:02 - info: Scales is now listening for uploads on port 5658 meta=undefined
23:10:02 - verbose: All scripts in /lib/scripts successfully had their permissions updated. meta=undefined
23:10:02 - verbose: Loaded server configuration for 3335b4fb-2dc3-454f-9b1d-6641ee9084a8 meta=undefined
23:10:02 - verbose: Loaded server configuration for 3f9b99ea-cdd2-4f70-8751-0bbaaf41a246 meta=undefined
23:10:02 - verbose: Loaded server configuration for 47fc4b7d-9933-4f96-af36-7b0d8a87b805 meta=undefined
23:10:02 - verbose: Loaded server configuration for 586c3936-8fa0-410e-829e-ab07cf2c1b33 meta=undefined
23:10:02 - verbose: Loaded server configuration for b5b7860d-0bc8-4399-a5f7-ebfe1012928f meta=undefined
23:10:02 - verbose: Loaded server configuration for e1b0bbf0-f4bf-4d81-9670-b06ba41d02e0 meta=undefined
```

**Comment by puffrfish** [comment]
This is because to turn the server on or off you need to use `on` and `off` instead of stop and start. The documentation was incorrect and has been updated.

**Comment by idkw** [comment]
Works great with on and off . Thank you !
