### ISSUE TITLE
500 error after after 5 - 10 minutes

### ISSUE THREAD

**Issue by Luukth** [PufferPanel/PufferPanel#582]
I get the 500 error after using the panel for more then 5 minutes. I cant find any errors and everything just looks fine. 

When I restart my vps the problem is solved. But when I start to use it it will give the 500 error after 5 - 10 minutes.

**Comment by Wargog** [comment]
An error in the 500 series is the server saying 'Oops, that's my fault', so, simply put, your server is probably overloaded.

**Comment by Luukth** [comment]
I know it has something to do with mysql. So I think I will reinstall that.

**Comment by Luukth** [comment]
Another error

150710 19:18:25  InnoDB: Operating system error number 11 in a file operation.
InnoDB: Error number 11 means 'Resource temporarily unavailable'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.5/en/operating-system-error-codes.html
150710 19:18:25 InnoDB: Could not open or create data files.
150710 19:18:25 InnoDB: If you tried to add new data files, and it failed here,
150710 19:18:25 InnoDB: you should now edit innodb_data_file_path in my.cnf back
150710 19:18:25 InnoDB: to what it was, and remove the new ibdata files InnoDB created
150710 19:18:25 InnoDB: in this failed attempt. InnoDB only wrote those files full of
150710 19:18:25 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
150710 19:18:25 InnoDB: remove old data files which contain your precious data!
150710 19:18:25 [ERROR] Plugin 'InnoDB' init function returned error.
150710 19:18:25 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
150710 19:18:25 [ERROR] Unknown/unsupported storage engine: InnoDB
150710 19:18:25 [ERROR] Aborting

**Comment by Omeryl** [comment]
This is still user error and have nothing to do with PufferPanel. Post on the forums, but this isn't a PufferPanel or Scales bug.
