### ISSUE TITLE
sftp users can acces all files

### ISSUE THREAD

**Issue by Luukth** [PufferPanel/PufferPanel#583]
When a user logs in using sftp he can acces all the files on my vps. I think this is a bug.

**Comment by BlameDylan** [comment]
Could you give us some steps to reproduce? Thanks for the report :)

**Comment by Luukth** [comment]
yes you just use the login information: http://gyazo.com/c51e493eac003d0c4e4da8111d645a0e

And then use an sftp file client to acces the files

**Comment by Omeryl** [comment]
You didn't follow the instructions correctly. 

http://scales.pufferpanel.com/v0.1.3/docs

Quote:

Then we need to modify `Subsystem sftp` ... to be `Subsystem sftp internal-sftp`. After doing that scroll to the bottom and add the following lines.

```
Match group scalesuser
    ChrootDirectory %h
    X11Forwarding no
    AllowTcpForwarding no
    ForceCommand internal-sftp
```
