### ISSUE TITLE
Upload a folder through the panel

### ISSUE THREAD

**Issue by idkw** [PufferPanel/PufferPanel#584]
When I try to upload a folder by drag and drop through the panel I get the following error 

`The BinaryJS data stream was closed by the server. Please refresh the page and try again.`

It would be nice to be able to upload folders. A common use case would be to upload a map folder.

Because of this error I have only two solutions
- Upload a zip with the panel and then unzip ip while connected in ssh
- Connect with FileZilla and upload the folder

**Comment by LordRalex** [comment]
The file manager is not meant to be a replacement for a SFTP client. It is meant to work as a quick SFTP client to let you make some small changes.

**Comment by idkw** [comment]
Ok maybe for a future version then.
It can only be a good thing if you can manager entirely your servers from the panel, right ?

**Comment by puffrfish** [comment]
It would take a lot to implement this properly, I think adding unzip support is a more feasible solution.
