### ISSUE TITLE
execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by FaZeBook** [PufferPanel/PufferPanel#588]
Hi,

My server can't start. I get this error:

Server is starting...
execvp(3) failed.: No such file or directory
[WARNING] This server has been detected as crashed by the management daemon. Restarting now...execvp(3) failed.: No such file or directory
[WARNING] This server has been detected as crashed by the management daemon. The restart process is being skipped due to the frequency at which this server is crashing (< 60 seconds between crashes).

What can I do?

Kind Regards,
Stefan Fransen

**Comment by Omeryl** [comment]
I don't think this particularly makes sense on GH:Issues. I think you should go over to our community forums to ask for support: https://community.pufferpanel.com/

Be sure to give as much information as possible, any logs from Scales will help immensely in solving your issue.

**Comment by BlameDylan** [comment]
Hello,
You need to install Java. Just run the following command on your Scales node.

**On Ubuntu:** `apt-get install default-jre-headless`
**On CentOS:** `yum install java-1.7.0-openjdk`
