### ISSUE TITLE
Doc URLs are not correctly made

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#590]
We point to whatever version was active at the time.

Should be using www.pufferpanel.com/docs/ instead of www.pufferpanel.com/v0.8.0/docs

**Comment by puffrfish** [comment]
I'll submit an issue to readme. It doesn't make sense that it 404s when we turn that version off. It should just redirect to the latest.

**Comment by puffrfish** [comment]
Just an update, still no response from ReadMe.

**Comment by puffrfish** [comment]
ReadMe has responded and said they are working on improving this.

**Comment by puffrfish** [comment]
ReadMe has corrected this issue and added a deprecated version feature. Users will be prompted to go the current version if they end up on a deprecated version.
