### ISSUE TITLE
[question] What type of SSL certificate is needed for PufferPanel to stop complaining

### ISSUE THREAD

**Issue by Mstrodl** [PufferPanel/PufferPanel#591]
That's about it... I don't want to get too much or too little (These things are expensive, Holy Cow!)

**Comment by puffrfish** [comment]
Nothing fancy, just a regular signed SSL cert will do. StartSSL provides free ones that will work. Hopefully soon let's encrypt will be up and running as well. It's not so much that PufferPanel is complaining it's the browser.

**Comment by Mstrodl** [comment]
So, Just verification certs?

**Comment by puffrfish** [comment]
I'm not sure what you mean by that. Any standard (approx $9/year) domain validation signed SSL cert will work.

**Comment by Mstrodl** [comment]
ok thanks
