### ISSUE TITLE
Ram never freed

### ISSUE THREAD

**Issue by idkw** [PufferPanel/PufferPanel#592]
The RAM is not freed completely when stopping a server.
After several restarts, it leaks memory.
I have only 7GB/32GB free although I have stopped all the servers and nothing else on the computer can et that much RAM.

**Comment by LordRalex** [comment]
How are you checking your free'd RAM?

**Comment by computerwizjared** [comment]
I believe that he is referring to PufferPanel/Scales#22. This has been an issue for me when trying to use Sponge at times. Everything seems to be fine with Bukkit/Spigot.

**Comment by idkw** [comment]
I use top to check the free RAM

**Comment by LordRalex** [comment]
If this is still an issue using Scales 0.1.4 (use "git checkout tags/0.1.4 && npm update" to update), then please comment saying so.
