### ISSUE TITLE
Cannot start server "No Startup file is defined for this server"

### ISSUE THREAD

**Issue by idkw** [PufferPanel/PufferPanel#593]
After changing startup command variables I cannot launch my servers anymore, I get the message :  

    Server is starting...
    [ERROR] No startup file is defined for this server. Please contact support and let them know about this error.

I changed the start command variables from :  
`spigotjar|/home/hardcraft/servers/jars/spigot-1.8.7.jar`
to :  
`spigotjar|/home/hardcraft/servers/jars/spigot-1.8.8.jar`

And the two files exist on the file system.
I tried to changed back to 1.8.7 but it displays the same error message, although it used to workd before I changed to 1.8.8.

What can I do ?

**Comment by BlameDylan** [comment]
I have two possible answers for this:

**1.** What is your startup command? You have provided us with the startup variables.

**2.** Check the permissions on the two files and make sure Scales has read, write, execute access.

Also, the way you're running PufferPanel seems odd, why not just put the spigot.jar in your server?

**Comment by idkw** [comment]
I meant  startup variables, these are the startup variables.

I do it that way to have one jar in one place, to avoid the need to copy it in every server when I need to update.

I'll check you 2nd suggestion but I doubt it because when I put back to 1.8.7 it didn't work although it worked before I changed to 1.8.8

**Comment by idkw** [comment]
The permissions are the same on the two files and I didn't changed them. It's not a permissions problem. 
What does `No startup file is defined for this server` mean ? What script ?

**Comment by idkw** [comment]
Ok this was a bug of the panel adding a space in front of the startup variables.
It happens from time to time, not a blocker, but you need to pay attention if it added a space or not.
