### ISSUE TITLE
Try again

### ISSUE THREAD

**Issue by ShayBox** [PufferPanel/PufferPanel#595]
This panel made me loose my data, i dont expect to get that data back. whatever...
but even after reinstalling ubuntu serve 14.04.3 LTS x64, following the install instructions EXACTLY, 3 times over with 3 diffrent install's it still doesnt work, i mean i dont know if it works... nowhere on scales, pufferpanel or any of the wiki/community pages does it say the url it will be under. Ex. my website is shaybox.com. but whats it under? shaybox.com/panel? nope. i dont know. the config doesnt tell you, the apache2.conf text i had to add doesnt tell me it just sais /srv/PufferPanel/public.

Note: any hate comments will be ignored

**Comment by turtledude01** [comment]
The docs do actually tell you how to configure apache.

**Comment by Omeryl** [comment]
Like in your previous issue, #594 the data loss was your fault alone. 

Please re-read the documentation and you'll be able to figure it out.

**Comment by ShayBox** [comment]
I know, i added the few lines to the apache2.conf but that still didnt fix it. i should also note that i used the automatic installer insted of downloading the files off github

**Comment by Omeryl** [comment]
We honestly suggest using nginx, not Apache.

**Comment by BlameDylan** [comment]
Well what domain did you put during the installer? Or did you even run the installer lol

**Comment by ShayBox** [comment]
i entered panel.shaybox.com because that redirects to the server that i was using, the main domain is on github pages.

**Comment by Omeryl** [comment]
Please open an issue at http://community.pufferpanel.com/, the GitHub is primarily for bug reports, feature requests not getting support.

**Comment by ShayBox** [comment]
has anyone made a video on installing PufferPanel yet? i havnt been able to find one

**Comment by ShayBox** [comment]
why'd you do that?

**Comment by Omeryl** [comment]
Please open an issue at http://community.pufferpanel.com/, the GitHub is primarily for bug reports, feature requests not getting support.
