### ISSUE TITLE
Problem server.properties

### ISSUE THREAD

**Issue by Andre32** [PufferPanel/PufferPanel#596]
Hi, often will auto reset the server.properties than one server on my list, I tried to update all the components of the panel but the problem remains how can I resolve?

**Comment by BlameDylan** [comment]
My apologizes, but I'm having a hard time understanding what you are trying to accomplish. Could you be more specific? Thanks!

**Comment by Andre32** [comment]
Hi, sometimes on restart scales reset the .properties of some servers

**Comment by Andre32** [comment]
UP

**Comment by Andre32** [comment]
How can I fix?

**Comment by Andre32** [comment]
?

**Comment by computerwizjared** [comment]
@Andre32 I think that this type of question is more suited for the forums at https://community.pufferpanel.com/.

**Comment by Andre32** [comment]
dobe, https://community.pufferpanel.com/topic/168-problem-serverproperties/

**Comment by DaneEveritt** [comment]
This could potentially be a bug with Scales, can you provide the properties file from before and after where scales has reset it?

**Comment by Andre32** [comment]
Before (http://pastebin.com/s9jRZkKN)
After (http://pastebin.com/BjWbAMfP)

**Comment by DaneEveritt** [comment]
That is not a bug. You are modifying startup values that are controlled by PufferPanel. If you want too use a different port then you need to change that in the panel, not in the server.properties file.

**Comment by Andre32** [comment]
Before (http://pastebin.com/s9jRZkKN)
After (http://pastebin.com/de8dHg5G)

**Comment by DaneEveritt** [comment]
I'm not sure I see what is wrong with either of those files. Could you please explain what Scales is doing to them?

**Comment by Andre32** [comment]
Scales turned on nether, achievement broadcast and online mode, and it also changed the max players amount. Other times it disables mob spawning. I think it's exchanging the properties of two server

**Comment by Andre32** [comment]
No, it is exchanging the file between servers, for example the .properties of the Hub with the .properties of PvP, because it exchanges also the max player amount, not only boolean variables.

**Comment by Andre32** [comment]
News @DaneEveritt ?

**Comment by Omeryl** [comment]
I can't reproduce this, @Andre32.

**Comment by LordPyrak** [comment]
I also have this problem :/
