### ISSUE TITLE
File Manager in Microsoft Edge

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/PufferPanel#597]
When using MS Edge it is inpossible to upload files because you are unable to drag and drop it onto the browser window. It only Shows the forbidden Icon when hovering with something over the upload field.
Possible solution: Add a search button that opens a dialog where you can browse for the file which should be uploaded.

**Comment by computerwizjared** [comment]
Yes, this is an issue that I have experienced. I have to use an SFTP client or Internet Explorer instead. Maybe simply make the drag and drop box clickable for a dialog, instead of adding a separate button? I think that would be handy.

**Comment by DaneEveritt** [comment]
closed in c3561a2d9
