### ISSUE TITLE
Why extra user?

### ISSUE THREAD

**Issue by lifehome** [PufferPanel/PufferPanel#600]
## Opinion-based issue
Sometimes setting up DB user with `create` `update` `select` and `drop` would be enough, more things like `truncate` or `alter` could be even requested though, but creating user or even database creation without prior permission request? It's a fairly "general" way to build an installer, but could we get a "chance" to put existing users **AND** databases for the installation?

Note: It's safe to install PufferPanel with the script, but just not everyone like "extra users" for "extra services".

**Comment by Omeryl** [comment]
Honestly, we're just forcing a sane standard using the installation script. One user per service to prevent damage when a single user may be compromised. If you want a nonstandard setup, you can just as easily install pufferpanel manually.

**Comment by lifehome** [comment]
Speaking of `compromised`, if I put the MySQL "root" password into the installer script, so do the PufferPanel user uses that password. Does that count as a security measurement to prevent compromise?

**Comment by lifehome** [comment]
Seems maybe the nonstandard way is kinda suits me somehow. :meh:
