### ISSUE TITLE
Can't connect to sftp

### ISSUE THREAD

**Issue by caxerx** [PufferPanel/PufferPanel#601]
When i use WinSCP to connect, the session close immediately.
When i use FileZilla to connest SFTP, I got "Received unexpected end-of-file from SFTP server"

**Comment by Omeryl** [comment]
Where do your server folders go into, /home? What's `/var/log/auth` or `/var/log/secure` say?

**Comment by DaneEveritt** [comment]
This is not a bug with PufferPanel, it is a bug with your configuration. Please create a topic on our [community support forums](https://community.pufferpanel.com/) for assistance.
