### ISSUE TITLE
Whmcs Module / Dead

### ISSUE THREAD

**Issue by Jackis16** [PufferPanel/PufferPanel#608]
Has this project died?

If not when will a WHMCS module be out?

Thanks

**Comment by Omeryl** [comment]
The project is far from dead. Take a look at the kraken branch. It's in the
process of a full rewrite out of PHP.

**Comment by Omeryl** [comment]
That said. There's definitely no ETA and I think the general consensus is
don't use the project until 1.0 for any commercial usage like that so that
we have a stable code base to go off of.
