### ISSUE TITLE
Auto Updating breaks the console restart button

### ISSUE THREAD

**Issue by jdlovins** [PufferPanel/PufferPanel#611]
Adding -autoupdate -steam_dir  -steamcmd_script to the srcds start up command breaks the restart button.
Using _restart works as it simulates a crash, and the crash handler handles that, but hitting restart does something else. It just outputs "quit" to console and then never restarts, I've tried doing it without "quit" at the end of the script thinking that may have been the cause it.

the script that i use is
login anonymous
force_install_dir ..
app_update 232250
quit

**Comment by DaneEveritt** [comment]
Unable to replicate on `0.2.2.` considering this fixed.
