### ISSUE TITLE
Command not found?

### ISSUE THREAD

**Issue by dannysmc95** [PufferPanel/PufferPanel#612]
I tried adding this but it does not work, just tells me "command not found" on Ubuntu Server 14.04.

Any help or thoughts would be appreciated

**Comment by parkervcp** [comment]
Which command are you running that it is saying not found? This is very vague.

**Comment by dannysmc95** [comment]
Oh sorry, I download the release and then attempt sudo ./installer.sh (what the file is called), and it says command not found.

**Comment by parkervcp** [comment]
Which OS.

**Comment by computerwizjared** [comment]
He said "Ubuntu Server 14.04" @parkervcp. @dannysmc95 Try running ```su -c "apt-get install sudo"``` to install sudo and then try running the installer again.

**Comment by dannysmc95** [comment]
@computerwizjared I have sudo? I use sudo for all other programs? It is just this file that does not work.

**Comment by computerwizjared** [comment]
Try running ```sudo sh installer.sh```

**Comment by dannysmc95** [comment]
@computerwizjared 

Syntax error near unexpected token '>' (line 24) and 'exec &> > (tee "/tmp/ppinstaller.log")' (same line)

Hope this helps, I like the look of this panel :P

**Comment by computerwizjared** [comment]
Oh try doing ```sudo bash installer.sh```

**Comment by puffrfish** [comment]
If you have further questions please use the community forum at https://community.pufferpanel.com
