### ISSUE TITLE
Scales FreeBSD support

### ISSUE THREAD

**Issue by iancorbitt** [PufferPanel/PufferPanel#613]
So I'm working to try and get Scales working on FreeBSD, but I've hit a road block in my testing. I've edited to user creation script to utilized pw but I get the following error in the logs:

>20:43:51 - error: Error occured trying to execute a command to add a user. meta=./lib/scripts/create_user.sh: not found

I've gone so far as to hardcode the script path into the process.js and it still fails.

**Comment by DaneEveritt** [comment]
This issue should be made in the PufferPanel/Scales repository.
