### ISSUE TITLE
Binding to 127.0.0.1 crashes scales

### ISSUE THREAD

**Issue by LordPyrak** [PufferPanel/PufferPanel#624]
While trying to setup Puffer Panel to handle a Bungeecord setup, I attempted to bind servers to 127.0.0.1 to prevent a malicious Bungeecord server from connecting to my child servers. This causes scales to crash. Although I do have IP tables setup to only allow traffic on port 25565, this would be helpful and add an extra layer of security. I'm relatively new to PufferPanel/scales/docker, so one of these servers might be designed to not allow this (I have no idea :D).

**Comment by Omeryl** [comment]
Honestly, just using iptables is enough. Binding to 127.0.0.1 won't work because each server gets its own interface and isn't the same "127.0.0.1" as another one

**Comment by DaneEveritt** [comment]
Can you provide logs from the time of the crash and exact steps for how to reproduce?

**Comment by DaneEveritt** [comment]
Closed due to lack of reply.
