### ISSUE TITLE
altering Startup Parameters (SRCDS) results into a non working game instance

### ISSUE THREAD

**Issue by cwmp** [PufferPanel/PufferPanel#626]
I altered (extended) the startup parameters to include

http://www.pufferpanel.com/docs/autoupdating-source-dedicated-server-game

which didnt work.

After chaneging back to the default 

http://www.pufferpanel.com/docs/adding-a-new-source-dedicated-server
(-game ${game} -strictportbind -port ${port} -console +map ${map} -maxplayers ${players} -norestart)

the server variables are not identified anymore..

Server is starting...
ERROR: Invalid game type '${game}' sepecified.
Sun Nov  8 20:08:40 UTC 2015: Server Failed
[Scales] [WARNING] This server has been detected as crashed by the management daemon. Restarting now...

Issue Update:

the initial parameters like

SRCDS Game ${game}
Map ${map}
Maximum Players ${players}
SRCDS Application ID ${build_params}

are not visible when you edit a deployed gameserver instance.

Create new gameserver

http://i.imgur.com/BlJlxBI.png

Edit deployed gameserver:

http://i.imgur.com/fafor7R.png

**Comment by worldmc** [comment]
I dont know if this is the right place to put this, but if it fails to launch a server on a startup parameter, why should it consider to even reboot at all? It knows it wont make it past reboot. Isnt it better to turn it off (saves a ton of starting and stopping) and request intervention from the admins? (Via mail or notify?)

**Comment by LordRalex** [comment]
@worldmc it's probably because it's not (easily) possible to tell why it failed. I doubt the error codes will reveal it and unless you do a good log parsing (which is probably not going to work well imo). For some stuff, yeah, you can tell, but it would be nearly impossible for us to easily detect why it crashed like that.

**Comment by DaneEveritt** [comment]
Scales is marking it as crashed because the process is exiting and nothing told Scales that the server was stopping, causing the reboot cycle.

**Comment by cwmp** [comment]
perhaps adding a regex (/ERROR: Invalid.+/) to detect start up errors caused like "ERROR: Invalid game type" could help

**Comment by DaneEveritt** [comment]
Unable to replicate this.

**Comment by cwmp** [comment]
I guess I accidentally deleted them. after recreating them manually it started to work again.

Maybe another plausibility check on those ones and a warning when mandatory data fields are missing for a succesful gameserver startup?
