### ISSUE TITLE
Cant install Pufferpanel Claims Git not installed

### ISSUE THREAD

**Issue by adamwbb** [PufferPanel/PufferPanel#627]
Unable to install pufferpanel on centos6
it claims Git is not installed even though it is.

![gitpuffer](https://cloud.githubusercontent.com/assets/2437446/11159530/56f1c8cc-8a2e-11e5-8c22-f09ce471350a.png)

**Comment by LordRalex** [comment]
Please use the forum for assistance with using the software: https://community.pufferpanel.com/

**Comment by adamwbb** [comment]
There is nothing in the forums about git
I cant get to even the installer it claims that git is not on the machine. but as you can see in the screenshot the machine does have git as you can tell from the git --version command

**Comment by LordRalex** [comment]
You need to install git into your server's PATH, not just using the binary from the source you built. To your system, git is not installed (and really, it's not if you are just using binaries you downloaded from the internet without installing them correctly).

Use your package manager to install git. You don't need to download the binaries from git or build it from source.

**Comment by LordRalex** [comment]
And you make a thread on the forum for help.
