### ISSUE TITLE
Ports selection on New Server doesn't line up with default IP.

### ISSUE THREAD

**Issue by Omeryl** [PufferPanel/PufferPanel#628]
I've got two IPs, two different sets of ports for them. 
* 23.1.2.3
* 172.17.42.1

When I load the New Server page, it shows the 23.1.2.3 IP with the ports for 172.17.42.1. To get it to fix, simply selecting the 172.17.42.1 then selecting the 23.1.2.3 will toggle the correct set of ports to show up.

**Comment by DaneEveritt** [comment]
Confirmed.

**Comment by Omeryl** [comment]
Could probably just have the trigger that happens when you switch the IP selection field run on page load complete.

**Comment by DaneEveritt** [comment]
It does, but appears to be running wrong.

**Comment by DaneEveritt** [comment]
This update can be applied to `0.8.3` by running the following command: `git cherry-pick 2885f9f68`.
