### ISSUE TITLE
500 (Internal Server Error) cant-create-new-server-editable-fields-arent-showing-up

### ISSUE THREAD

**Issue by cwmp** [PufferPanel/PufferPanel#633]
I am having exactly the same issue as posted: 

https://community.pufferpanel.com/topic/296-cant-create-new-server-editable-fields-arent-showing-up/

Applied the latest patch but did not correct the issue.

**Comment by DaneEveritt** [comment]
Did this just suddenly start happening? System information? Errors from the logs?

**Comment by cwmp** [comment]
I just upgraded to 0.8.3 as described. I am seeing this behavior when trying to create a new server

**Comment by cwmp** [comment]
http://pastebin.com/w858njts

**Comment by DaneEveritt** [comment]
Is there anything logged in `info.log` rather than `exception.log`? I really can't think of any reason why this would be happening, and the error log provided isn't really helpful at all.

**Comment by cwmp** [comment]
here we go :)

http://pastebin.com/a0kQUbU3

**Comment by DaneEveritt** [comment]
It is saying there is a server error, but it is also returning the correct information...

What.

**Comment by cwmp** [comment]
it seems like a nice conundrum :)

**Comment by demon-goxa** [comment]
I have the same issue  :cold_sweat:

**Comment by DaneEveritt** [comment]
https://community.pufferpanel.com/topic/304-error-while-creating-new-server/

**Comment by DaneEveritt** [comment]
@cwmp @demon-goxa — can you try doing the commands below and then check your info and exception logs after reproducing the bug?

```
cd /srv/PufferPanel
git fetch
git cherry-pick 13c4122
```

**Comment by demon-goxa** [comment]
The Same error  :imp:
http://pastebin.com/vSkjbkVT

**Comment by DaneEveritt** [comment]
Can you message me `exception--2015-11-30--06-16--17f50b615f.html` on the forums please?

**Comment by cwmp** [comment]
error: could not apply 13c4122... potential fix for #633
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

git status:

On branch master
Your branch is up-to-date with 'origin/master'.
You are currently cherry-picking commit 13c4122.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   src/routes/admin/server/routes.php

no changes added to commit (use "git add" and/or "git commit -a")

Ive removed 

<<<<<<< HEAD
=======
>>>>>>> 13c4122... potential fix for #633

but the issue is the same.. same error...

**Comment by DaneEveritt** [comment]
@cwmp — it appears your cherry-pick did not work as you might have edited the routes.php file that it is attempting to change.

**Comment by DaneEveritt** [comment]
Also, I need the `info.log` not the exception.log

**Comment by cwmp** [comment]
I reset it back to master and tried checky picked the change..and getting this. Ive never manually touched the routes.php file before.

Sorry, I have no info.log at all

**Comment by DaneEveritt** [comment]
That is strange, there should be an info log returned. @demon-goxa did you also encounter this after upgrading, or was it after doing a fresh install?

The problem I am having with this bug is that a.) I can't replicate it at all and b.) the stack traces are not leading to any specific file that would be causing it, which is why I was hoping there was an info.log. The `Debugger::log` function logs to that file, and not to exception.log as far as I know, so it seems like something else is triggering the error. And as @cwmp seemed to have confirmed, there is a response being sent back to the browser, it just have a 500 code attached for some reason.

**Comment by DaneEveritt** [comment]
@cwmp — I'm wondering if this could be caused by APC. I haven't used it enough to know if that could be the issue, and I'd be surprised if it was. Can you try disabling it and see if that resolves the issue?

**Comment by cwmp** [comment]
I actually see alot of ..PHP Notice:  Undefined property: stdClass::$debugging in... errors in the apache log

more:
http://pastebin.com/BnbeFjXD

**Comment by cwmp** [comment]
Im sorry, but what you mean with APC?

**Comment by DaneEveritt** [comment]
The notices are an issue with some of the configuration code, but that wouldn't be causing the error your are seeing. [APC](http://php.net/manual/en/book.apc.php) (Alternative PHP Cache) is enabled on your system, try disabling it.

I doubt it is the reason for these problems, but it wouldn't hurt to go ahead and disable it.

**Comment by cwmp** [comment]
Ill give you an overview of the servers php info

http://pastebin.com/2dY548pp

**Comment by DaneEveritt** [comment]
Can you try running a fresh install of PP on this system and see if the error still occurs?

**Comment by cwmp** [comment]
I did a complete new installation (deleting Pufferpanel Directory and sql Pufferpanel DB) and have the same error.
because I am using a virtual host on apache on non standard port and with https, I needed to alter the
1.master_url
2.assets_url
3.main_website

to <httpS> instead of <http> in the sql DB because the URL Settings in Pufferpanel irgnores and resets the changes.

After that, I went straight to the <New Server> tab and received the same <500 (Internal Server Error)>


 to give

**Comment by DaneEveritt** [comment]
The AJAX call uses a relative path, it doesn't matter that it is HTTPS.

I'll investigate this more, no idea why it is happening though.

**Comment by tecnobrat** [comment]
I am also experiencing the same thing, totally reinstalled everything.  Same exact behaviour.

**Comment by tecnobrat** [comment]
If it helps, I'm on Ubuntu 14.04.

**Comment by tecnobrat** [comment]
I cherry-picked down your changes, and now I have an info.log with this:

```
[2015-12-02 21-13-52] Klein\Exceptions\ResponseAlreadySentException: Response has already been sent in /srv/PufferPanel/vendor/klein/klein/src/Klein/AbstractResponse.php:397  @  http://mc.tecnobrat.com/admin/server/new/plugin-variables  @@  exception--2015-12-02--21-13--66dc4cca9b.html
```

**Comment by tecnobrat** [comment]
Please see the above mentioned PR. Fixes it for me.

**Comment by LordRalex** [comment]
Please validate the fix works @cwmp

**Comment by cwmp** [comment]
confirmed! It is working as expected now! Thanks so much! no more errors

git checkout master
git pull
