### ISSUE TITLE
Game variable string error when adding a space

### ISSUE THREAD

**Issue by chKaze** [PufferPanel/PufferPanel#636]
ERROR: Invalid game type 'Counter-Strike' sepecified.

I set the gamevariable to "Counter-Strike Source" as per http://forums.srcds.com/viewtopic/12473
but it seems like it cuts off the part after Strike which results in an invalid game type error.

Reproduce the bug with entering a game string with an empty space and it will cut it off.

**Comment by puffrfish** [comment]
It's actually `csgo`, not sure why that says otherwise. I'll look into finding a better list.

**Comment by LordRalex** [comment]
The fix is going to be simply adjusting a value in the SQL table, and I'm getting the update command in a second

(future me, fix goes at https://github.com/PufferPanel/PufferPanel/blob/master/install/install.sql#L197)

**Comment by LordRalex** [comment]
UPDATE `pufferpanel`.`plugins` SET `default_startup` = '-game \"${game}\" -console +map ${map} -maxplayers ${players} -norestar' WHERE `slug` = 'srcds'

**Comment by DaneEveritt** [comment]
You actually want:
```mysql
UPDATE pufferpanel.plugins SET default_startup = '-game \"${game}\" -console +map ${map} -maxplayers ${players} -norestart' WHERE slug = 'srcds'
```

You can also just change the command line for that specific server to use `-game "${game}"` rather than `-game ${game}`.

**Comment by chKaze** [comment]
-game "${game}" -console +map ${map} -maxplayers ${players} -norestart

startup variables
players|20
map|de_dust2
game|Counter-Strike Source
build_params|232330

returns the same error.
-game "Counter-Strike Source" -console +map ${map} -maxplayers ${players} -norestart
cuts it off as well. I assume the issue would be on my end?

**Comment by DaneEveritt** [comment]
Try doing "Counter-Strike Source" for game, not `-game "${game}"`.

```
players|20
map|de_dust2
game|"Counter-Strike Source"
build_params|232330
```

**Comment by chKaze** [comment]
ERROR: Invalid game type '"Counter-Strike' sepecified.
Wed Dec  2 22:00:51 UTC 2015: Server Failed

seems odd that it cuts it off regardless of syntax

**Comment by DaneEveritt** [comment]
Yep, I actually know exactly why that is occurring. Scales is splitting the string spaces for startup params, and ignoring the fact that the space is within quotes. You won't be able to fix this without going into Scales and modifying some stuff with how it handles startups.

Gotta love Valve doing non-standard things like this...

**Comment by chKaze** [comment]
I see. Valve doing non-standard things? Can't imagine that (looks at half life and tf2/hatsimulator) ^^

If you need anything else let me know.

**Comment by DaneEveritt** [comment]
Its unfortunately just not going to work for awhile. I have a lot going on right now, so I don't have much time to play around with it.

**Comment by chKaze** [comment]
No worries! Wish I could help more but my programming is pretty much limited to basic java and c++

**Comment by DaneEveritt** [comment]
The line in question is [this](https://github.com/PufferPanel/Scales/blob/master/lib/plugins/srcds/main.js#L77) which is breaking your command into the blow, where each new line is an array element:

```
-game
Counter-Strike
Source
-console
+map
somemap
-maxplayers
12
-norestart
```

**Comment by DaneEveritt** [comment]
We can try making it `return startupArray.match(/[^" ]+|("[^"]*")/g)` which should work.

**Comment by chKaze** [comment]
This seemed to break the node/ssl certificate I will try reverting. I do not require a css server that badly (mostly just wanted to test and check it out) so I dont mind waiting.

**Comment by LordRalex** [comment]
I am closing this issue, as Scales will not be receiving updates to resolve any non-critical bugs. The new daemon will take this into account and be handled correctly.
