### ISSUE TITLE
Outdated link in server startup configuration

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#638]
The ["located here"](http://i.imgur.com/8IYkLIG.png) points to an outdated link. It should be updated to http://www.pufferpanel.com/docs/adding-a-new-minecraft-server#build-parameters

**Comment by derrickmehaffy** [comment]
It would seem pufferpanel.com is now redirecting to the github, is the site down?

**Comment by computerwizjared** [comment]
@derrickmehaffy I believe that they are moving to https://pterodactyl.io/

**Comment by Omeryl** [comment]
Incorrect, a developer left the project and went there. We're alive and will continue to be active. 






On Mon, Dec 7, 2015 at 5:15 AM -0800, "Jared Bates" <notifications@github.com> wrote:












@derrickmehaffy I believe that they are moving to https://pterodactyl.io/

**Comment by computerwizjared** [comment]
@Omeryl Oh, I apologize

**Comment by DaneEveritt** [comment]
Old documentation can still be found at http://PufferPanel.readme.io for the time being until the URL stuff is worked out.

**Comment by Matthew-Kilpatrick** [comment]
@DaneEveritt When I click the URL that you mentioned should have the documentation on, I am sent to a page saying 'Not Yet Active'. Are you aware of this not working?

**Comment by puffrfish** [comment]
We're waiting on Readme.io to reactivate our account, sorry for the inconvenience.

**Comment by Matthew-Kilpatrick** [comment]
@puffrfish It's ok, not urgent, however slightly worrying how it says inactive when I went on the page.

**Comment by puffrfish** [comment]
Pointing it back to the repo until they activate it. My apologies once again.

**Comment by puffrfish** [comment]
It's activated again but unfortunately the CNAME no longer works under the open source plan, so right now I have pufferpanel.com redirecting to pufferpanel.readme.io
