### ISSUE TITLE
Commands/messages from console look weird

### ISSUE THREAD

**Issue by xion87** [PufferPanel/PufferPanel#645]
As title say it look weird, because when i write something for  example: /say questo è un test
It output this:

> sa
> y quest
> è un te
> st

[11:55:57 INFO]: [Server] questo è un test

Using Pufferpanel 0.8.4 and scales 0.2.3

Move it to scales if is a scales issue..

**Comment by xion87** [comment]
Issue still persist 0.8.5 Pufferpanel

**Comment by LordRalex** [comment]
Do you have a screen shot from puffer panel for this

**Comment by xion87** [comment]
http://imgur.com/wcTo6fo

**Comment by LordRalex** [comment]
Do you issue those commands from the panel or on the server?

**Comment by xion87** [comment]
From console

**Comment by LordRalex** [comment]
I've not been able to reproduce this, and cannot see how it would happen.

**Comment by xion87** [comment]
you tried to type any command from console?

**Comment by LordRalex** [comment]
I tried your exact command. http://i.imgur.com/nefEQyE.png

**Comment by xion87** [comment]
derp, did you tried to use java 8?

**Comment by LordRalex** [comment]
Tested on both Java 7u91 and Java 8u65

**Comment by xion87** [comment]
derp, ubuntu 14?

**Comment by LordRalex** [comment]
The Java 7 was Ubuntu, Java 8 was CentOS. At this point, I cannot believe it to be an issue with the panel.

**Comment by xion87** [comment]
is true... i tried to use commands from a spigot server without plugins, and it look fine, instead if i use chatcontrol plugin it show like that.... >.< you can close the ticket if needed but i will ask the author if is possible to fix this

**Comment by xion87** [comment]
Hey @LordRalex  i tried again, without plugin, try to write 5 times a command with more worlds like "/say test test test, 1 of 3 will become break, this is definitily a pufferpanel/scales issue:
http://i.imgur.com/RPy7ZEg.png
Notice the plugins that i am runing

**Comment by LordRalex** [comment]
The only reason that I can see this happening is if the browser is doing something. I used Chrome and could not replicate it. You do not have any extensions with Firefox, correct?

**Comment by xion87** [comment]
no extension, i tried also chrome, same result:
![1](http://i.imgur.com/LzHJRpD.png)

**Comment by ryanguy426** [comment]
Also have this issue, very annoying. One console command ends up taking the entire screen space. I'm willing to help do testing to figure this out as well. Ubuntu 14.04 x64, Java 8, Spigot 1.8. 

If you refresh the page, the issue goes away for a minute but it'll always come back

**Comment by AsaPlaysMC** [comment]
seems to be an issue with latest versions of browsers, when I was using a Chrome version from back in Jan of 2015, it worked perfectly fine

**Comment by LordRalex** [comment]
Had it been that, it should have occurred when I was testing it at the time, since Chrome would have been roughly the same version, or we would have more reports on this.

**Comment by NLDev** [comment]
Have the same issue. Only if I execute a "say" command tho.
Here a screenshot: http://imgur.com/a/85yAp

**Comment by lucasdidur** [comment]
Try to add this on your server startup 

`-Djline.terminal=jline.UnsupportedTerminal`

**Comment by LordRalex** [comment]
I think i identified the cause:

When Scales is told to send a message to the web console, it will always force a newline to be appended. This in turn caused this behavior we saw.

pufeferd is not doing this, so this issue should be resolved.
