### ISSUE TITLE
Install Successfully - Receive 500 Error

### ISSUE THREAD

**Issue by catwithbowtie** [PufferPanel/PufferPanel#646]
Everything has installed successfully but I receive a 500 error via Nginx. Running OpenVZ Cent OS 6 container. I followed the instructions on the site, PHP 5.6 and nginx is working fine. Currently don't have a domain connected to it, currently using an IP. 

Puffer config file:

server {
    listen 80;
    root /srv/PufferPanel;
    index index.php;

    server_name my.vps.ip;

    client_max_body_size 20m;
    client_body_timeout 120s;

    location / {
        try_files /public/router.php =404;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index router.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }

    location /assets {
        try_files /app/$uri =404;
    }

}

Logs:

PHP Notice: Undefined property: stdClass::$debugging in /srv/PufferPanel/src/core/config/jsonconfig.php$g.php on line 45" while reading response header from upstream

Sorry for posting here but you guys have no contact form on the website nor anywhere to post. Anyone help?

**Comment by puffrfish** [comment]
If you are still having issues please open a thread on [https://community.pufferpanel.com](https://community.pufferpanel.com). Thanks!
