### ISSUE TITLE
Plesk php-fpm issue

### ISSUE THREAD

**Issue by ModdyLP** [PufferPanel/PufferPanel#648]
Hello

i have a issue with the php version. I use plesk and the puffer installer tells me that php 5.0+ is missing. I had version 5.5 - 5.6 installed. I dont know how i can solve this issue.

Best regards
moddyLP

**Comment by parkervcp** [comment]
What does ``php -v`` return?

**Comment by ModdyLP** [comment]
here the output:
PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies with the ionCube PHP Loader v4.6.0, Copyright (c) 2002-2014, by ionCube Ltd.

I had set in plesk 5.6.16
My PHP handler i had installed in Plesk: 
![php handler](https://cloud.githubusercontent.com/assets/15385020/11780126/f1521946-a25f-11e5-91ce-96a0176c336f.PNG)

Setting on my first domain where puffer will be installed:
![plesk domain php](https://cloud.githubusercontent.com/assets/15385020/11780145/1613662c-a260-11e5-9c6a-d7da81a9d7ab.PNG)

**Comment by LordRalex** [comment]
We use php-cli to validate that you have installed PHP 5.5 correctly. You will need to determine how to update php-cli to at least 5.5.

**Comment by ModdyLP** [comment]
i had an php handler from plesk i had version 5.4.16, 5.5.30 and 5.6.16. But i get with the command php-v only the lowest. I had ask the plesk support, but i get only a weird answer.

**Comment by ModdyLP** [comment]
Can you please make me a version where the php version 5.4 is requried one? I take over all erros are coming if there are compatibility problems with that version. The other option is that i can install the panel directly on my webserver without a way over the shell console.

**Comment by LordRalex** [comment]
No. We require the panel to use in the end PHP 5.5+. If stuff like that is not installed, then the install won't work as intended and we cannot guarantee anything will work right. PHP 5.4 is also 3 years old, and is not recommended.

**Comment by Omeryl** [comment]
It's also end of life.

**Comment by ModdyLP** [comment]
Can you give me some instruction or the direct installfiles so i can modify and install it on myself?? I cant change the version becouse of inkompatibilty with plesk. I want to use plesk and your panel, so may i can have the direct install files and a little instruction how to install it from these files???
I would be very nice if you can do that for me.

**Comment by ModdyLP** [comment]
I had complete the installation with editing the install file and change the proofment from php to 5.4. that works.

**Comment by LordRalex** [comment]
Then you will have to deny any assistance from here-on out, because we require what we require in order for the panel to function. Should things break, we cannot assist you.
