### ISSUE TITLE
Startup command does not replace additional occurrences of variable

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#655]
For example, if you have both -Xms${memory}M and -Xmx${memory}M, it will only put the contents of the memory variable in the -Xms option and leave the other as "-Xmx${memory}M"

**Comment by Omeryl** [comment]
Hey I wrote this didn't I? :p

**Comment by LordRalex** [comment]
``
str = str.replace(escapeRegExp('${memory}') + '/g', memory);

function escapeRegExp(str) {
    return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
``

Writing for when I get time to fix it.

**Comment by Omeryl** [comment]
I don't think that'll exactly do it. I think you need something like this:

```
str = str.replace(new RegExp("/" + escapeRegExp('${memory}') + '/g'), memory);
```
