### ISSUE TITLE
Error: Service Temporarily Unavaliable

### ISSUE THREAD

**Issue by Syleron** [PufferPanel/PufferPanel#656]
After creating a new server I get "Install completed successfully." but as soon as I go onto the server control page I get a loading bar with the error "Error: Service Temporarily Unavaliable - The requested server is still completing the install process. Please check back in a few minutes, you should recieve an email as soon as this process is completed.".

Any idea on how to resolve this? I looked at docker ps on the scales server and the created server is not listed.. not sure why.

Cheers!

**Comment by puffrfish** [comment]
Check out the Scales logs in /srv/scales/logs and see what it says

**Comment by puffrfish** [comment]
Please open a thread on the community forums if you have further issues. Thanks!
