### ISSUE TITLE
Can't add nodes

### ISSUE THREAD

**Issue by IlPicasso** [PufferPanel/PufferPanel#661]
Hello, I am not able to add nodes to my Panel, when I add them and press on Create Node it will refresh the page , delete the data and it won't create anything

**Comment by IlPicasso** [comment]
After A few tries I was able to do it

**Comment by Chris2fourlaw** [comment]
V0.8.6 still applies

**Comment by Chris2fourlaw** [comment]
My bad v0.8.5. Updating now

**Comment by Chris2fourlaw** [comment]
CAN CONFIRM ON v0.8.6
