### ISSUE TITLE
[kraken] install script fails on SQL creation

### ISSUE THREAD

**Issue by phlupp** [PufferPanel/PufferPanel#664]
I am installing the kraken with installer script, it fails on creating the SQL database.

The email field in 'users' has 'not null' flag, the install.php script wants to input "$params['adminEmail']" but this variable is not forwardet to the script

**Comment by LordRalex** [comment]
Please provide the full error.

Also note that the script is not recommended for kraken unless you know what you are doing, and may not correctly work for kraken.

**Comment by LordRalex** [comment]
This does not seem to occur anymore (if it did)
