### ISSUE TITLE
Can't add ports to node after the installation 0.2.4

### ISSUE THREAD

**Issue by iaxedu** [PufferPanel/PufferPanel#668]
Like the title says I'm trying to add additional ports it says successful but they are not added. I click on add port and type down my part and click on the enter button: http://i.imgur.com/MSHEISG.png

This is the message but it doesn't add the port.
http://i.imgur.com/cYu6yQK.png

Also tried: 24700-24800

It did work by adding the same IP-Address again and type: 24777,25500-25600

**Comment by LordRalex** [comment]
We cannot replicate this on our end.

We were able to add a range of ports by using both formats without problems. What browser are you using?

**Comment by Omeryl** [comment]
Just tried to on a number of different browsers and I couldn't reproduce.

**Comment by xion87** [comment]
Omery is the node primary? or secondary?
