### ISSUE TITLE
Billing/Current API

### ISSUE THREAD

**Issue by 20zinnm** [PufferPanel/PufferPanel#669]
What's the current progress of the API? I'm thinking of writing a billing system extention or something but if the API is going to rapidly change it's not worth it at present.

**Comment by Omeryl** [comment]
There's going to be a complete and hopefully last big change for 0.9. So just hold off I think.

**Comment by 20zinnm** [comment]
@Omeryl Thanks for the speedy reply! I will hold off, thanks. Been checking the .9 branch out and it's exciting to see the progress.

**Comment by LordRalex** [comment]
That branch is Legacy, it is not what 0.9 will be

**Comment by LordRalex** [comment]
That branch is Legacy and is just there for history. It is not what 0.9 will be
