### ISSUE TITLE
Feature to assign multiple ports to a server

### ISSUE THREAD

**Issue by sahaka** [PufferPanel/PufferPanel#672]
Most of the servers I have in the panel use more than 3 ports for a variety of plugins. It would be great to be able to tag more than one port to a server so that when managing other servers or adding new ones, you can easily see which ports are used where and which ports are available. It could also allow for setting up a deployment template that always give blocks of 3(or however many set) ports.

If this is possible it would be nice to have the option of giving some details about what the port is for. Like 25565 is the main server, 25566 is telnet, 25567 is status monitoring plugin, etc.

**Comment by puffrfish** [comment]
Definitely something we will implement for containerized servers in the new version.
