### ISSUE TITLE
[1.0.0/pufferd] Versioning

### ISSUE THREAD

**Issue by 20zinnm** [PufferPanel/PufferPanel#673]
I propose the PufferPanel rewrite follow the Semantic Versioning (http://semver.org/) style for versioning to add better compatibility, add support for a future auto-updater, and generally make the setup less confusing. Now is the perfect time to start, seeing as it's a major release (fully breaking) and any subsequent update would be minor or bug fixing.

**Comment by Omeryl** [comment]
Hey,

Pretty sure that was already the plan.

**Comment by 20zinnm** [comment]
Always good to make it an issue so no one forgets it. I’d like to implement an automatic updater (think a nice banner telling you there’s an update and a button that can guide you through the process of database updates) but if bug fixes required database changes and the updater didn’t take that into account… better to stress SemVer than accidentally forget.

**Comment by LordRalex** [comment]
We are focusing on this, because 0.8 should not have happened the way it did. It was a *very* poor decision by the main dev to do it that way, and it is why we are starting from 1.0.0 now.

**Comment by puffrfish** [comment]
Closing since this is a non-issue and was already planned.
