### ISSUE TITLE
need help asap having issues with installation

### ISSUE THREAD

**Issue by MRGanboo** [PufferPanel/PufferPanel#674]
the installation went perfectly except the fact that i have multiple web graphical interfaces and etc and it said i just had ot go to my server ip to load it up but i need help to move it so i have to go to my serverip/pufferpanel then login and also it doesnt work when i go to my server ip

**Comment by puffrfish** [comment]
Sorry, I don't understand what you are asking. If you need installation help please ask on the forums and include any logs or errors you are receiving.
