### ISSUE TITLE
Weird Console Output Formatting

### ISSUE THREAD

**Issue by littlemarc2011** [PufferPanel/PufferPanel#675]
Hi, I was wondering if there could be any reason my console output looks like:

[17:39:08] [Server thread/INFO]: [0;37;22m[[0;31;1mTheCoreMC[0;37;22m] [0;31;1mItems Will Be Removed In [0;37;22m60 [0;31;1mSeconds![m
[17:39:48] [Server thread/INFO]: [0;37;22m[[0;31;1mTheCoreMC[0;37;22m] [0;31;1mItems Will Be Removed In [0;37;22m20 [0;31;1mSeconds![m
[17:40:08] [Server thread/INFO]: [0;37;22m[[0;31;1mTheCoreMC[0;37;22m] 0 Entities Were Removed![m

I believe on all other panels/consoles I've used it just would say something like:

[17:39:08] [Server thread/INFO]: [TheCoreMC] Items Will Be Removed In 60 Seconds!

Is there a setting I can change? I believe it's because of chat colors but I can't deal with the console looking like that... I can't even read what my players are saying because of prefixes!

Have A Great Day! -Marc

Edit: (Sorry Github makes the message look weird... but you get the point)
Edit 2: Using version 0.8.5.2 Beta (sha: Invalid)

**Comment by littlemarc2011** [comment]
Wow... that's just sad, the author is active changing code(12hrs ago) but my issue has been open for 15hrs.... does the author just not care?

**Comment by DaneEveritt** [comment]
Yes, because they should drop everything and answer you right away. Chances are they are looking into the issue, you shouldn't expect an immediate reply and acting entitled is a great way to be ignored. 🌞

**Comment by LordRalex** [comment]
I'm sorry if you think that I should have dropped everything when you opened your issue and completely ignored the issue that would actually in some cases cause users to lose **SSH** access to their server just to help with an issue that's relatively minor compared to that (and that issue being open for several days). I am then sorry that I am only human and must sleep at certain times of the day. I am sorry that you don't pay for this software and yet still expect me to drop everything to help.

You are given this software for free, and we expect nothing from you except a little respect. I do not like any issue with the panel, and look into each one **before** I reply. I saw your issue the moment you first posted it, however I have not been free to look into it. You have now gotten a reply the moment I woke up from only 5 hours of sleep. Is that not enough care for you?

**Comment by littlemarc2011** [comment]
Well after doing some deeeeeeeep research and looking into the source, it is the servers fault and it's how spigot/paperspigot logs colors. In order to fix this, or for anyone with this issue... Try adding either 1 or both of their parameters to the server startup parameters "--log-strip-color --nojline" (make sure it is at the end or at least after <jarname>.jar)

Also sorry for the disrespect, just figured I would see a comment saying "I'll look into it" or "I will solve this when I get the chance"

**Comment by LordRalex** [comment]
And that is where I am worried, because I have also been looking at our source, and we are stripping the ASCII codes, which only gets rid of part. It still means I have to create an updated StripAscii function, but since it's not a crippling bug and has a workaround, will not likely get resolved on Scales due to the deprecation of that daemon.

**Comment by nerdtron123** [comment]
Maybe it has the § character in it which is causing it to display like that, try cutting that character out if not already filtered.
