### ISSUE TITLE
Simply Does Not Work

### ISSUE THREAD

**Issue by PeterEstephan** [PufferPanel/PufferPanel#678]
Hey,
Whole Logs folder: [logs.zip](https://github.com/PufferPanel/PufferPanel/files/153861/logs.zip)

So after my ridiculous amounts of times trying to install PufferPanel and get it working there has finally been a fix that has been working, and thank you for that and now my scales and pufferpanel can install. However with every server I have got and used I have gotten 0 to work. Here are the steps I do when I install on a server (Ubuntu - fresh out of the box):
(All Servers)
1) Run: apt-get update, upgrade, dist-upgrade, autoclean, update, clean
2) Run: apt-get install curl, zip, unzip
(PufferPanel)
3) Then I run the following:
`
sudo apt-get update
sudo apt-get install -y openssl curl nginx git mysql-client mysql-server php5-fpm php5-cli php5-curl php5-mysql php5-mcrypt

sudo php5enmod mcrypt
sudo service php5-fpm restart`

4) Then After that I run: 
`# Please run these with either sudo in front of them, or as the root user (sudo -i)
mkdir -p /srv && cd /srv
curl -L -o pufferpanel.tar.gz https://git.io/vzpYF
tar -xf pufferpanel.tar.gz
cd pufferpanel
./pufferpanel install`

5) Afterwards, I go to install Scales on my other server. (Im using AWS to host my pufferpanel server, and im using 2 google servers to run scales on. )

6) Afterwards, I make a location, node, and click Generate Auto-Deployment Script. I run this on the first node that I want just to test it out. (Note I'm only installing scales on one server for now... and I ran the commands from above on the server - under the All Servers Section)

7) After Scales Installs and starts listening on port 5656, I go to the pufferpanel section and I see that pufferpanel knows that scales is running on my other server. 

8) From there I go to create my first server. I put in the name, ram, and under build parameters I put: -p spigot

9) After the server installs, I click on the Server Control and hit Start. 

10) After minutes of waiting nothing seems to happen. So I go to the scales log on the server and I 
see it trying to run on the server by it saying:

It just plainly says Powering on Server in the proc1.log - note I to not see a proc.log file I see a proc1.log and a proc.log.gz, and installer folder with install logs. (I have attached the log files. )

At this point Im not too sure what the cause of this is. I have opened 5656, and any necessary minecraft ports. Im not too sure what other ports scales needs to run but Im quite stumpt on what the cause of this is. Thank You for Your Help. 

Server Specs: 

Intel Xeon Proccessors E5 and up
Ubuntu 15.10 (latest updated version)
All the necessary amount of RAM
And Way over 150 GB

- Thanks. I am also willing to give you access to the server and pufferpanel if that helps fix the issue.

**Comment by LordRalex** [comment]
Can you have the server logs in a pastebin/gist.github.com or some other form of sharing so that the nextlines are not lost?

**Comment by PeterEstephan** [comment]
Here are the pastebin files that I have uploaded (Sorry for the multiple parts as the file was over 500 KB):
Also here is the whole logs folder which I downloaded and zip'd: [logs.zip](https://github.com/PufferPanel/PufferPanel/files/153861/logs.zip)
proc1.log:
    Part 1: http://pastebin.com/DRN0VYvj
    Part 2: http://pastebin.com/Tn7uLPA2
installer log (7d5b7213-c65b-4adb-9c8d-a4bd4590ad53-2016.03.01.16.57.27): 
    Part 1 of the log: http://pastebin.com/8ZVAQsSc
    Part 2 of the Log: http://pastebin.com/4zwW3Cgm

**Comment by PeterEstephan** [comment]
So is their any way to fix this?

**Comment by LordRalex** [comment]
The fact it installed correctly is good, but something is killing it from starting. What settings did you set for the process? (You can probably upload the data/7d5b7213-c65b-4adb-9c8d-a4bd4590ad53.json file, removing the keys part from it to not allow access to it via others)

**Comment by PeterEstephan** [comment]
Here is the 7d5b7213-c65b-4adb-9c8d-a4bd4590ad53.json:
`
  "name": "7d5b7213-c65b-4adb-9c8d-a4bd4590ad53",
  "user": "pp-backup_zk2vk",
  "build": {
    "disk": {
      "hard": 32,
      "soft": 32
    },
    "cpu": 0,
    "memory": 4096,
    "io": 500
  },
  "startup": {
    "command": "-Xms${memory}M -Xmx${memory}M -server -jar ${jar}",
    "variables": {
      "jar": "server.jar",
      "build_params": "-p spigot"
    }
  },
  "keys": {
    "4d97fc2f-4f52-490d-995c-ef1d973a15ab": [
      "s:ftp",
      "s:get",
      "s:power",
      "s:files",
      "s:files:get",
      "s:files:delete",
      "s:files:put",
      "s:files:zip",
      "s:query",
      "s:console",
      "s:console:send"
    ]
  },
  "gameport": 25570,
  "gamehost": "137.186.228.11",
  "plugin": "minecraft"
}

`

**Comment by LordRalex** [comment]
That file appears correct, so not the problem

Can you run `java -version` by itself? What is the output

**Comment by PeterEstephan** [comment]
Here is the output:

```
root@ubuntu-Peter:~# java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by puffrfish** [comment]
If you are still experiencing an issue please open up a thread on our [community forums](https://community.pufferpanel.com). Thanks!
