### ISSUE TITLE
Email support: Drop Mandril support and add Mailjet support

### ISSUE THREAD

**Issue by xion87** [PufferPanel/PufferPanel#682]
Hi, as i know Mandrill will be not anymore free ( http://blog.mandrill.com/important-changes-to-mandrill.html) and Mailchimp owned, i suggest to remove this and add the support to Mailjet instead (i am using it with my xenforo, and is working perfect) https://www.mailjet.com/

**Comment by puffrfish** [comment]
If people wish to use and pay for Mandrill we're probably not going to take that option away (although its future in v1.0.0 is questionable). I don't think we're going to be adding more providers in the current codebase, but most of them provide an SMTP relay service which lets you use it regardless of if the provider is supported by the panel. We'll look at putting Mailjet and may others in v1.0.0.
