### ISSUE TITLE
./pufferpanel: line 142: uuidgen: command not found

### ISSUE THREAD

**Issue by nuttah** [PufferPanel/PufferPanel#688]
while installing pufferpanel base the above notice came up.
I've just entered a name an went further. Don't know if somethin is missing beause of that missing command.
Happened with unubtu trusty and wily

```
Please enter the following information for the new admin user
./pufferpanel: line 142: uuidgen: command not found
Username:

```

**Comment by puffrfish** [comment]
This should be in the default install of Ubuntu 14.04 and 15.10, but if you run:
```
sudo apt-get install uuid-runtime
```
This error should be fixed.
