### ISSUE TITLE
Bug with scales

### ISSUE THREAD

**Issue by akiva3577** [PufferPanel/PufferPanel#691]
When i turn off scales (./scales stop).
It turns off on the control panel but the game servers on that node are still running.
Although its not a damaging bug, its kind of annoying because it leaves the server port taken not allowing the server bind to the assigned port.
Even if i turn scales back on, the game server status wont update.
The only temporary fix I figured out is rebooting the entire machine and it works properly again.

**Comment by puffrfish** [comment]
Please file this bug on the Scales issue tracker. Thanks!
