### ISSUE TITLE
Can't add ports to secondary nodes.

### ISSUE THREAD

**Issue by Incrementing** [PufferPanel/PufferPanel#699]
I'm having the same issue @xion87 was taking about in this [issue report](https://github.com/PufferPanel/PufferPanel/issues/668).

I can add new ports to my primary node but I can't add ports to an other nodes.
I get the message saying they have been added but upon refreshing the page the port list hasn't changed.

![image](https://cloud.githubusercontent.com/assets/16342485/15436865/cdc7cf88-1ebb-11e6-9087-14a7b2bcd551.png)
![image](https://cloud.githubusercontent.com/assets/16342485/15436878/e39ea75a-1ebb-11e6-97ed-c603e00392b7.png)

**Comment by xion87** [comment]
i confirm bug still persist, i tried to add new port on secondary node, it will be not added

**Comment by Incrementing** [comment]
I just noticed my issue is a copy of issue #644.
When googling for a fix I only saw post #668, Sorry for missing that.

**Comment by LordRalex** [comment]
Closing then as this is a dupe
