### ISSUE TITLE
Error occurs while running Auto-Deploy script.

### ISSUE THREAD

**Issue by jasoryeh** [PufferPanel/PufferPanel#703]
Hellollo, when I try to run the Auto-Deploy, on both scales and docker version it says it is already running and halts everything and says An error occured while installing, halting... in red.
`
-For scales... 
Starting Scales
Process already running: 32650
An error occured while installing, halting...
and for docker...
Configuring Docker for: root
start: Job is already running: docker
An error occured while installing, halting...
``

**Comment by jasoryeh** [comment]
These are what it stopped with, I don't know why it stops for both docker and scales, cant get past it.

**Comment by jasoryeh** [comment]
Ok, I fixed the issue, all I had to do was ./scales stop and then re-run/generate the Auto-Deploy command

**Comment by puffrfish** [comment]
In the future, please use the [PufferPanel community forum](https://community.pufferpanel.com) for issues you may have with PufferPanel. This issue tracker is only for confirmed bug reports.
