### ISSUE TITLE
Cant create a server

### ISSUE THREAD

**Issue by TheHtaccess** [PufferPanel/PufferPanel#705]
So for some reason, whenever I try to add a server, it just refreshes the page and doesn't add it. I've done the thing with scales, but it still doesn't work. I've tried restarting my server and reactivating scales immediately after but it still doesn't want to add it.

**Comment by LordRalex** [comment]
Please use the [community forums](https://community.pufferpanel.com) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports
