### ISSUE TITLE
Error in the installing script

### ISSUE THREAD

**Issue by Pandry** [PufferPanel/PufferPanel#709]
Hi
I'm new in this project (coming from the [easy-wi](github.com/easy-wi/developer) panel)
I've installed the panel, but having some issues...
The installing script is a bit bugged...
I've installed the panel and I immediatly gos some issues...
The first problem is that the nginx config is not replaced, but that's not so harmful
The second one it is...
The script problaly hash the MySQL password (I didn't gave it a look), so every thing is fucked because the password is not checked, so it fucks some things...
My idea is easy:
You make install php5, so, to check the password you run a easy php scrpt that check if the connection can be estabilished :D
(Sorry for my bad English but I'm from my phone)
(If I'll have time I'll add the check :smile: )

**Comment by LordRalex** [comment]
Please use the [community forums](https://community.pufferpanel.com) for issues, questions, or help with installation or configuration of PufferPanel.
This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here.
