### ISSUE TITLE
Mass Power

### ISSUE THREAD

**Issue by nerdtron123** [PufferPanel/PufferPanel#713]
On the mass commands page, you should change it to "Mass Actions" and make it that it has mass start, stop, restart, and send command.

**Comment by LordRalex** [comment]
Discussion about new features (for PufferPanel v1.0.0) belongs on the community forums. Please use the community forums for issues, questions, or help with installation or configuration of PufferPanel. This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here.
