### ISSUE TITLE
Showing RAM accolated for all servers. (Possibly API too)

### ISSUE THREAD

**Issue by Azoraqua** [PufferPanel/PufferPanel#716]
Showing the RAM accolated for all servers on a node.

**Comment by LordRalex** [comment]
Discussion about new features (for PufferPanel v1.0.0) belongs on the community forums. Please use the community forums for issues, questions, or help with installation or configuration of PufferPanel. This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here
