### ISSUE TITLE
Deleting a node dondun Work(that means it donesnt work btw}

### ISSUE THREAD

**Issue by Villagedeal** [PufferPanel/PufferPanel#717]
i press the delete a node button then i press the im sure or whatever then the popup comes up and i press ok the something flashes on the screen i cant read fast enough then nothing happens.

**Comment by puffrfish** [comment]
This issue tracker is for confirmed bug reports. For support with PufferPanel please open a thread on our [community forums](https://community.pufferpanel.com) in the Support category. Thanks!
