### ISSUE TITLE
Known Interface Bugs (kraken)

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#719]
- [ ] Status icon next to server name remains a spinner
- [x] Start/Stop/Install buttons unable to be used after pressing one of them unless page is refreshed - visual problem only

**Comment by HexelDev** [comment]
- [ ] The version number is currently 0.8.7

**Comment by LordRalex** [comment]
- [ ] UI does not properly indicate if daemon is unavailable on Add Server

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/PufferPanel/blob/master/app/views/admin/server/view.html#L229
Code missed which uses the socket, this is no longer used
[ ]
