### ISSUE TITLE
Bungeecord Proxy status not updating

### ISSUE THREAD

**Issue by NLDev** [PufferPanel/PufferPanel#720]
If you run a Bungee Server in puffer, the status of the proxy won't update to "Running". It will remain "Oflline" event tho you can stop/kill the server. So I think puffer knows that bungee is running but still displays it as offline.
I don't know if its a problem with Puffer, or if Bungee simply doesnt return a status.

**Comment by phlupp** [comment]
What is the system language on your system, i had a similar problem. Java is using system lenguage for console output so scales doesn't recognize that Bungee has startet well. I don't how to change locales for java, i have changed the "config.json" in scales for the Bungee plugin:

first you have to look into the Bungee logs and find the line containing

`Listening on `

take a look how this line is formatted, in my case the line is:

`... [INFO] Listening on ...`

then open "/path/to/scales/lib/plugins/bungeecord/config.json" and edit the line "started" according to your line.

**Comment by phlupp** [comment]
Sorry, i have forgotten, you have to restart scales to take effect.

**Comment by NLDev** [comment]
It's english and thank you that worked perfectly!

**Comment by NLDev** [comment]
Wait no it doesnt work, Do I have to write the "..." aswell? Like

`... [INFORMATION] Listening on ...`

**Comment by phlupp** [comment]
no without the dots. the line must be like:

`"started": "[INFORMATION] Listening on "`

**Comment by NLDev** [comment]
The proxy prints out following line when enabled

`19:41:26 [INFORMATION] Listening on /{My IP}:25565`

so I went to the config where you told me to and changed it like that:

` "started": "[INFO] Listening on "`

**Comment by NLDev** [comment]
Ok I found the reason why it doesnt work. I changed the line and then tried to do ./scales stop & ./scales start. Its just that this doesnt work "Error: port 25565 already in use" so I restarted the whole server (ubuntu: reload) but the config.json seems to be resetted after every reboot

**Comment by NLDev** [comment]
Sorry, the problem has been solved. Seems like th eproxy was running in the background

**Comment by NLDev** [comment]
Thank you very much! :)
Are you experienced with Puffer?
