### ISSUE TITLE
Installation issues with database

### ISSUE THREAD

**Issue by bouab002** [PufferPanel/PufferPanel#725]
MySQL Configuration
Enter the MySQL host [localhost]: db.domain.com
Enter the MySQL port [3306]: 
Enter the MySQL username (MUST HAVE GRANT) [root]: 
Enter the MySQL account password: 
Creating pufferpanel account and installing database...
MySQL has been configured and the database was installed
Switching to new user for further commands
------------
Configuring site details
Please enter the domain or IP (if you do not have a domain) for your site (do NOT include http(s)://): game.domain.com
ERROR 1045 (28000): Access denied for user 'pufferpanel'@'srv01.domain.com' (using password: YES)
Settings saved to database
------------
Please enter the following information for the new admin user
./pufferpanel: ligne 142: uuidgen : commande introuvable
Username: zidane
Email: bz@domain.com
Password: 
Installing user...
ERROR 1045 (28000): Access denied for user 'pufferpanel'@'srv01.asnet.pro' (using password: YES)
Installing nginx config (if possible)
An existing configuration exists in /etc/nginx/sites-enabled
------------
Would you like to thank us? Each thanks gives us the motivation to provide this software to you. [Y/n]: Y

**Comment by LordRalex** [comment]
Your connection to the MySQL server is trying to use 2 different domains to connect to it, and MySQL can't allow it, because we only allowed one. Our installer cannot detect this kind of setup.

**Comment by mitymarcus** [comment]
Please use pastebin.com or pastie.org to post logs.
