### ISSUE TITLE
Preflight

### ISSUE THREAD

**Issue by mitymarcus** [PufferPanel/PufferPanel#726]
Ocassionally, when I start a new server, it hangs in preflight. When I refresh the page, it simply goes back to Server is currently offline.
Even though I can run other servers, this will sometimes happen.

![image](https://cloud.githubusercontent.com/assets/7784585/21578744/f0f73328-cf59-11e6-9d70-dcc224d77f00.png)
![image](https://cloud.githubusercontent.com/assets/7784585/21578746/fb9121fe-cf59-11e6-9982-dc6b2d38c7ea.png)

**Comment by Hwiggy** [comment]
To anyone else with this issue, I suggest making sure your node allocation is set to use your server's INTERNAL IP, as seen here: http://prntscr.com/dq4pmg

**Comment by mitymarcus** [comment]
As @Hwiggy said, it was a problem of assigning my node allocation to the external ip, when it should have been the internal.
