### ISSUE TITLE
Error 500 when I try to create a Node on 0.9

### ISSUE THREAD

**Issue by ARatfat** [PufferPanel/PufferPanel#727]
hello 

Thanks to make plublic the 0.9 version 
I run Puffer 0.9 on CentoOS 7.2 when I try to create a Node I have an error 500

during last step of installation I've this erre 
"ERROR 1054 (42S22) at line 2: Unknown column 'daemon_base_dir' in 'field list'"

**Comment by LordRalex** [comment]
0.9 is not meant for public use, but this will be fixed.
