### ISSUE TITLE
New user cannot log in after account creation

### ISSUE THREAD

**Issue by RalphORama** [PufferPanel/PufferPanel#728]
I recently installed PufferPanel on my server, and a new user account I created cannot log in. I get the following error in `pufferpanel/logs/exception.log`:

```
[2017-01-10 02-11-52] PHP Notice: Undefined property: stdClass::$assets_url in /var/www/cp.corerp.co/src/routes/admin/settings/routes.php:83  @  https://cp.corerp.co/admin/settings/global/general
```
and
```
[2017-01-10 04-15-43] Compile Error: Cannot use lexical variable $eventName as a parameter name in /var/www/cp.corerp.co/vendor/guzzlehttp/guzzle/src/Event/Emitter.php:48  @  https://cp.corerp.co/auth/login  @@  exception--2017-01-10--04-15--f5d6c8af12.html
```

Some more information I've found: from https://www.drupal.org/node/2811063, it appears "PHP 7.1 throws fatal errors for double argument names"

I'm running PufferPanel v0.8.5.3 Beta on Ubuntu 16.04.
The output of `uname -a` is `Linux <hostname removed> 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
The output of `php --version` is `PHP 7.1.0-5+deb.sury.org~xenial+1 (cli) ( NTS )`

**Comment by LordRalex** [comment]
The asset_url error is a known issue, but will not break logins.

The second looks like it relates to the library we have there, which I do recall is also considered deprecated. I will look into this and see what we have to do to fix it, but I was not aware of others having issues with PHP 7.0 before.

**Comment by RalphORama** [comment]
I'll do some more testing and see if I can find any more errors related to signups on my box, if you'd like

**Comment by LordRalex** [comment]
Ah, I did not even see 7.1 was released at the start of December, it's not been pushed through the main repos yet for me so never saw it, been using 7.0 for some time.

I'll for now leave the library, since something else depended on it and see what needs to happen to get the panel to support 7.1 correctly.

**Comment by LordRalex** [comment]
Closing since this will be fixed when https://github.com/PufferPanel/PufferPanel/issues/732 is resolved
