### ISSUE TITLE
Include submodules (vendor)

### ISSUE THREAD

**Issue by erdoking** [PufferPanel/PufferPanel#731]
Please add the vendor-repository and reference to the single projects.
https://git-scm.com/book/en/v2/Git-Tools-Submodules

you can see an example on https://github.com/stuporglue/TreeTrumpet/tree/master/src/lib
After that you can checkout the COMPLETE repo with:

git clone https://github.com/PufferPanel/PufferPanel/
cd PufferPanel
git submodule init
git submodule update --init --recursive

**Comment by LordRalex** [comment]
We use composer for our library dependencies, similar to how other projects can use Gradle/Maven/bowser/npm

Using sub-modules like this would mean we have to keep a commit tracking system to just say "oh, we fixed this version", which gets cumbersome, and would change the build process of the project. 

Their reasoning for using this doesn't really line up with what I agree with, and it's just "yet another library management standard".
