### ISSUE TITLE
How do I get sftp setup and working?

### ISSUE THREAD

**Issue by GazbonicAcid** [PufferPanel/PufferPanel#741]
I am completely unable to post on community support page as the Category selection dropdown is completely empty with NO options.
As such it won't let me post without a category.

Now for my actuall support request...

How do I get sftp setup and working?
I followed the instructions but it's just slow and I get disconnected because of a timeout in filezilla.
And this is my ssh log.
https://hastebin.com/korebugono.cs
I don't know how to remotely upload the sshd config if you needed it.
CentOS 7.? (I don't know exactly what's after the ?"
I changed the "Subsystem sftp" entry to "Subsystem sftp internal-sftp", and set usepam to no,
as was suggested by others in other posts experiancing the same time-out can't log into sftp issue.
But I have yet to actually find a fix for this issue.

**Comment by LordRalex** [comment]
We do not use the sshd service anymore, use port 5657 for SFTP.

**Comment by IndrajeethY** [comment]
> We do not use the sshd service anymore, use port 5657 for SFTP.

can we change it?
