### ISSUE TITLE
Issue Installing pufferpanel inside docker

### ISSUE THREAD

**Issue by lycano** [PufferPanel/PufferPanel#744]
Hi,

im currently installing pufferpanel inside docker with a linked mysql container.

I can connect to the linked container from the pufferpanel docker container with root user and password. After the installer created the database user pufferpanel all following queries will fail i.e. nothing is written to the database after that.

I also tested if the pufferpanel user created by root could connect from that container (fetched from config.json). This only works if i re-create the user with the correct host.

To fix this the installer script needs to be updated.

In L83 of pufferpanel install script ( https://github.com/PufferPanel/PufferPanel/blob/master/pufferpanel#L83 ) the host is fetched via processlist and is transformed via head and tail to fetch the desired result.

This is not needed since "SELECT USER()" would give you "<current_user>@<host>".

L83 can be replaced with the following two lines to get the host:

`newHost=$(mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -sN -e "SELECT USER()")`
`newHost=${newHost/${mysqlUser}@}`

After changing this i was able to run the install script without database connection errors.

Best wishes,
luricos

**Comment by lycano** [comment]
Thanks for merging the pull request. I guess this can be closed then.

**Comment by puffrfish** [comment]
Thanks!
