### ISSUE TITLE
Can't control other people's server as administrator

### ISSUE THREAD

**Issue by DJGummikuh** [PufferPanel/PufferPanel#749]
I'm currently running PufferPanel 1.0.2 on my machine. Basically everything seems to work like it should (I'm kind of hacking pufferpanel and pufferd together since I want to docker the entire infrastructure), however after creating a Server as administrator for a User different than myself, trying to access the Server Control Panel results in an internal Server Error. These are the exception documents created by PufferPanel:
http://static.djgummikuh.de/exceptions/exception--2017-03-07--10-19--a55e36a3ec.html
http://static.djgummikuh.de/exceptions/exception--2017-03-07--10-20--f352443723.html

Unfortunately I'm not firm enough in PHP to efficiently diagnose this topic any further, can you please give me a hint on what might be going on here?

Kind regards,
Johannes Frank

**Comment by DJGummikuh** [comment]
Since I still was running on PHP5, I switched to PHP7, still with the same result, so it appears to have nothing to do with the php version in use.

**Comment by DJGummikuh** [comment]
Ok I sunk another couple of hours into that, built the pufferpanel the desired way, still I have the exact same issues. Nobody else notices these problems? They prevent me from actually going life with 1.0.2 and since my last version was 0.5.8 and I just did a server move I'm stuck inbetween with users breathing down my neck :-/

**Comment by LordRalex** [comment]
This is a known issue and I've already pushed code that in theory resolves it, but I have not tested it properly and it still has a migration issue from older versions.

**Comment by LordRalex** [comment]
I am working on fixing pufferd and getting the SFTP issues resolved there since it's a more "crippling" issue than this, but this is the next thing on my place to get tested and resolved.

**Comment by DJGummikuh** [comment]
Oh. Is there a way for me to circumvent that problem in the meantime? I'm not migrating but building anew (since my old docker images were WAY hackier than the new ones, thanks a ton for having pufferd now instead of scales, I even get away without running PufferPanel in privileged mode xD)

**Comment by LordRalex** [comment]
The issue with admins is that the underlying OAuth2 token usage isn't set up to handle the admin users correctly.

You'd have to insert a new oauth_client record with the admin's user id and the server id they need to access, following the convention set there were the name is .internal_<userid>_<serverid>. The client id should be set to be similar, secret doesn't *need* to change.

This is what the fix does is actually populate that table correctly for admins.

**Comment by DJGummikuh** [comment]
can you give me a *rough* estimate (no worries, won't hold you accountable for it xD) on when you will be able to tackle that issue?

**Comment by LordRalex** [comment]
I've been hoping the SFTP would be quick to solve, but it's proving to be more than that. I am about to release it with the known bug, and just fix it at a later date.

This issue requires me to go into testing, which while I have the server set up, it's not deployed yet. Assuming no issues, probably within a week of the pufferd release.

**Comment by DJGummikuh** [comment]
cool! If I can help you somehow tell me :-)

**Comment by LordRalex** [comment]
We keep constant builds of our software on https://dl.pufferpanel.com/pufferpanel/nightly/ which has the theoretical fix, but it's not been tested, and is always going to use the nightly daemon core.

You can attempt to install that version and see how it plays out, reporting any issues that you find. That would help locate issues I may not realize/

**Comment by DJGummikuh** [comment]
It seems you have (among other things) an issue with your build server, the "nightly" build is from february 26th.. :-)

**Comment by LordRalex** [comment]
It runs a build every 30 minutes, but only will deploy a new file if the git sha is different. 

PufferPanel has not had a commit to that repo for 11 days, so it's not been putting out anything new.
pufferd has had more recent commits, so that project has been building with newer dates on it.

You can look at the version.txt to see what the git sha for the commit that produced that download is.

**Comment by DJGummikuh** [comment]
ah cool! Will do! thanks! Will write more this evening (EST).

**Comment by puffrfish** [comment]
Resolved in v1.0.3
