### ISSUE TITLE
[Bug] Delete users

### ISSUE THREAD

**Issue by sYCH3L** [PufferPanel/PufferPanel#750]
After update 1.0.3 cannot seem to delete users from the panel.
Does not matter if admin account or not.

**Comment by Moutard3** [comment]
Same here, got error 500 when deleting user

**Comment by Trimilur** [comment]
Same here for deleting subuser but different error: 

Unable to revoke permissions for this user. (An error occurred when trying to update the server.)

**Comment by LordRalex** [comment]
This will be fixed when we do an update to the DB for 1.1.

I have already started the fix locally, but have to create the migration tool for 1.0 users.

**Comment by GoadingGoat** [comment]
Having issues deleting users in v1.1

Error generated trying to delete users in /srv/pufferpanel/logs is:

[2017-05-03 10-20-09] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'oauth_access_tokens.user_id' in 'where clause' #42S22 in /srv/pufferpanel/vendor/j4mie/idiorm/idiorm.php:503 @ http://******.com/admin/account/view/4/delete @@ exception--2017-05-03--10-20--338f402406.html

**Comment by puffrfish** [comment]
Here is the exception.html for this issue.
https://pste.eu/p/bjd8.html
