### ISSUE TITLE
Rough Usage & Installation on Alpine Linux 

### ISSUE THREAD

**Issue by MarkehMe** [PufferPanel/PufferPanel#752]
Alpine Linux is the ideal server for game servers - lightweight and high security. It has only recently gained the recognition it has deserved!

I've updated the docs to add some information for basic installation on Alpine Linux. 

However the auto-deploy does not support the apk package manager, I'm currently working it out - would a pull request be accepted?

**Comment by LordRalex** [comment]
Any and all PRs are acceptable.
