### ISSUE TITLE
Saving URL Settings does not work as intended

### ISSUE THREAD

**Issue by sahaka** [PufferPanel/PufferPanel#753]
When pressing "Update Settings" in the URL Settings page it will clear the PufferPanel Master URL and save the blank value to the database requiring the user to change the database manually. It will also change "https" to "http" in the Main Website URL field.

**Comment by LordRalex** [comment]
Ah, I have located the issue.

The concept of the 2 URLs was removed, but the UI does not reflect this correctly anymore.

We will have to simply update the UI to not show the unused URL path.

**Comment by sahaka** [comment]
Ok that makes sense. I was wondering what the second URL did, but when I saw them both written to the DB I thought it must be used somewhere.
