### ISSUE TITLE
Rewrite installer 

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#760]
When the installer was originally written, the use of bash was not a bad choice, because it was small.

It has now become a behemoth, and has lost a lot of its maintainability as a result. The installer should be re-written in another language such that all features that it handles are covered, instead of the mix of languages that it currently uses.

**Comment by lapisangularis** [comment]
What about moving back to Docker and additionally Ansible recipe? The installation script with it will be clear, and easy to maintain.

**Comment by Ubun1** [comment]
is it possible to make a silent installation? i want to make a Dockerfile for easy set up with defaults and possible customisation via environment variables.

**Comment by LordRalex** [comment]
@lapisangularis we never officially supported installing via docker. We also don't believe that requiring docker is going to help, but rather cause more issues for users, and as such, want to keep compatibility with as much as possible. 

@Ubun1 You could use a text file to do that, and pipe it into the installer. I do that locally. I have a text file with my system config and I just run a "install.sh" that sends that as input into the installer.

A silent installer might be nice, but we'll see. It might just end up being "you can send config options through the CLI", but in the case of all passwords we ask, I am not happy with that.

**Comment by khionu** [comment]
I'd like to suggest that, in the new installer, the initial account creation be done via a quick web panel. I like my passwords to use a full range of characters, and that can be problematic with a CLI. I have mine generated by KeePassX.
