### ISSUE TITLE
Forgot Password fails on submission due to captcha

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#763]
The forgot password system requires that you fill in a captcha, but this only works if you actually fill the information in through the admin panel beforehand.

We should not be showing this if it's not configured

**Comment by Pandry** [comment]
What would be the better solution for you?
Removing the captcha in case it's not configured, or making the page unaccessible?

**Comment by LordRalex** [comment]
It would be removing captcha if it's not configured. It doesn't make sense to not allow forgot password resets if that's not set up.
