### ISSUE TITLE
Autorestart

### ISSUE THREAD

**Issue by zikycz** [PufferPanel/PufferPanel#773]
Good day, I wanted to ask, how do I install the PufferPanel auto restart the server every day.

**Comment by Pandry** [comment]
So you would like to restart a server every day, am I right?

**Comment by zikycz** [comment]
Yes

**Comment by Pandry** [comment]
It a kind of weird thing, and I think there are things that have a higher priority at the moment...
You could try to accomplish what you're trying to do using the cronjobs I guess...

**Comment by GoadingGoat** [comment]
Haven't tested this myself but, have a look at this.
https://community.pufferpanel.com/topic/426/request-all-server-restart-script/2
