### ISSUE TITLE
"undefined" notification when starting servers

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#775]
Users are experiencing an issue where a notification pops up upon starting a server, displaying an "undefined" message. I will add a screenshot once I can replicate.

**Comment by GoadingGoat** [comment]
Can help with screenshots.
For Starting a server:
![undefined](https://cloud.githubusercontent.com/assets/11308755/26151795/6b567600-3b58-11e7-9f85-59b319ebdef8.PNG)

And on restart:
![onrestart](https://cloud.githubusercontent.com/assets/11308755/26151826/942611c6-3b58-11e7-9f77-659984b08cbb.PNG)

**Comment by puffrfish** [comment]
Thanks for the screenshots. I cannot replicate this issue with the latest (nightly) pufferd, but if I downgrade I'm able to again. I think it is safe to call this closed for now, unless there's a certain browser having issues or I'm missing something.

**Comment by puffrfish** [comment]
v1.1.1 of pufferd seems to work fine too. @GoadingGoat make sure your pufferd is up to date, if it is already I might have to look into this a bit more. https://www.pufferpanel.com/docs/updating-pufferd

**Comment by puffrfish** [comment]
Okay, I was finally able to replicate this issue on a fresh install of v1.1.0. I cannot replicate it on v1.1.1, so this issue has thankfully been fixed.
