### ISSUE TITLE
Missing Class for Mailgun

### ISSUE THREAD

**Issue by sahaka** [PufferPanel/PufferPanel#777]
Running Version v1.1.0

Class 'PufferPanel\Core\Mailgun' not found 

<img width="774" alt="screenshot 2017-05-16 12 58 16" src="https://cloud.githubusercontent.com/assets/4749006/26118296/6627dbd2-3a37-11e7-852b-16e16000d83d.png">

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/PufferPanel/issues/770
