### ISSUE TITLE
Cannot Delete Users

### ISSUE THREAD

**Issue by sahaka** [PufferPanel/PufferPanel#779]
Running Version v1.1.0

PDOException #42S02
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pufferpanel.actions_log' doesn't exist

<img width="945" alt="screenshot 2017-05-16 13 01 24" src="https://cloud.githubusercontent.com/assets/4749006/26118449/f39cf060-3a37-11e7-9d08-2ba6e3234102.png">

Upon trying to delete users that had 2FA to recreate them to not use 2FA, this error came up and the user was not deleted.

**Comment by puffrfish** [comment]
Unfortunately, I believe this issue is related to the database issues you were having previously. We can speak more on Discord about resolving this issue for you.
