### ISSUE TITLE
File Manager - Delete files not working

### ISSUE THREAD

**Issue by puffrfish** [PufferPanel/PufferPanel#781]
When trying to delete a file using the file manager the following error appears.
![zjrsfj2](https://cloud.githubusercontent.com/assets/3316865/26376171/9dfcd52e-3fd9-11e7-82ae-6fe8298f1907.png)

**Comment by LordRalex** [comment]
We did not include this scope with the 1.1 build (server.file.delete)

Scope has been changed to server.file.put to compensate for this, but we'll fix this properly with the 1.2 release

https://github.com/PufferPanel/pufferd/commit/2c25d75bc7606cff78c66d5f4af10817c5f843ee
