### ISSUE TITLE
404 not found after a clean install

### ISSUE THREAD

**Issue by bruxo00** [PufferPanel/PufferPanel#784]
Hey!

I'm getting

> Not Found
> 
> The requested URL /index was not found on this server.

 There are only 2 files on public: **index.php** and **router.php**. It is supposed to be like that?

I'm using:

CentOS Linux 7.3.1611
PHP 7.1.5 (cli) (Zend Engine v3.1.0)
MySQL/MariaDB 5.5.52
PufferPanel 1.1.3
Apache 2.4.6

**Comment by LordRalex** [comment]
Type sudo a2enmod rewrite in your terminal following it with sudo service apache2 restart
