### ISSUE TITLE
File Manager - Some folders don't open

### ISSUE THREAD

**Issue by bruxo00** [PufferPanel/PufferPanel#785]
Example:

I have [this](https://i.gyazo.com/fb9eb4654311e1d42a6fcaf7b3de1389.png) server. If I open the folder named **csgo**, the panel returns a error named **[object Object]** like [this](https://i.gyazo.com/4095e931699524ebc84b4927138764b6.png).

The browser console is returning this error:

> jquery.js:8630 GET http://mydomain.com/daemon/server/e52a8c38-8fae-46b3-a23d-793b98aa74bb/file/csgo/ net::ERR_INVALID_CHUNKED_ENCODING
> send	@	jquery.js:8630
> ajax	@	jquery.js:8166
> makeDaemonCall	@	files:315
> getFileList	@	files:266
> loadFolder	@	files:379
> onclick	@	files:1

CentOS Linux 7.3.1611
PHP 7.1.5 (cli) (Zend Engine v3.1.0)
MySQL/MariaDB 5.5.52
PufferPanel 1.1.3
Apache 2.4.6

**Comment by LordRalex** [comment]
Based on a google of that answer, it indicates that some proxy is altering the results.

https://superuser.com/questions/893908/err-invalid-chunked-encoding-from-chrome

Since it's not easily reproducible, I think some proxy somewhere in your route is causing an issue.
