### ISSUE TITLE
File manager shows [object Object] instead of errors

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#789]
When pufferd returns an error for the file manager, or some error occurs while talking to the daemon, instead of a message being printed that explains what happened, a [object Object] is shown, which has no useful information.

We should display the error correctly.

**Comment by brad-marshall** [comment]
I tried this patch against 1.1.3 and all it did was removed the Object object part of the error, it didn't make things any clearer at all.  This is still occuring for me regularly, on multiple different installations.

**Comment by LordRalex** [comment]
This tried to not hide the error, but there's 1 error that will occur and won't display right.

Check the javascript console, if you are getting a CHUNK_ENCODING error or something, that's the case we are still looking into.

**Comment by Autopoietico** [comment]
I have this error in 1.1.3 version also, how do I check the javascript console?

**Comment by LordRalex** [comment]
Ctrl + J in chrome

**Comment by Autopoietico** [comment]
The error that I have in the javascript console is:
`Failed to load resource: net::ERR_INVALID_CHUNKED_ENCODING`

**Comment by LordRalex** [comment]
That has been a reported error, but we have yet to determine the cause.

Please follow the directions on https://github.com/PufferPanel/PufferPanel/issues/795 to help us.
