### ISSUE TITLE
File manager shows no message and console shows INVALID_CHUNK_ENCODING

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#795]
Some issue where the response is being altered along the path and so browsers do not read it correctly.

Please fill out the following information when replying to this bug report:
1) Browser
2) Server OS (distro)
3) Web server
3) Pufferd location (localhost or remote is acceptable)
4) Pufferd OS (if remote)
5) Type of game server used
6) At what point did you start seeing this error? (i.e after re-installing the server, uploading X file)

**Comment by Autopoietico** [comment]
1. Chrome and Firefox
2. Ubuntu 15.10
3. SoYouStart (OVH)
4. localhost
5. Pufferd 1.1.3
6. Minecraft Forge
7. When the servers are Forge and have a certain amount of files becames to fail and give me this error, I have a server only with Forge and works perfectly.

**Comment by brad-marshall** [comment]
1. Chrome & Firefox
2. Ubuntu 16.04
3. Apache 
4. localhost
5. Local - so Ubuntu 16.04
6. Minecraft Spigot
7. Pretty much after installation of the server, I believe.

I'll be doing some more testing with this, spinning up some new servers etc and will see if I find anything useful.

**Comment by brad-marshall** [comment]
I've just done a fresh install with the latest PufferPanel and used a Spigot server.  The filemanager worked immediately after installation, but failed after I hit start.  So there's something in the process of starting the server that breaks it.

**Comment by LordRalex** [comment]
Have now replicated this using the step brad indicated. Standard LAMP install with a spigot server.

**Comment by Autopoietico** [comment]
Now is working. THANKSSSS!!!! ;D
