### ISSUE TITLE
Missing deps does not stop installer

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#796]
When missing php-curl, the installer will state the dep is missing, but then state the force flag was present, so it will continue.

**Comment by Pandry** [comment]
I belive it's possible to check if the extension exists at the start of the file.
Here's a snippet:
```
if(!extension_loaded ("php-curl")){
    die("PHP-Curl extension missing!<br/>Please enable it or the installer won't work.");
}
```
I do belive that's enough

**Comment by LordRalex** [comment]
We already do this check, you mis-read the actual issue.

There is a flag we support to ignore that dependencies are missing. That flag is being set incorrectly, so our installer thinks it's there when it is not.
