### ISSUE TITLE
Error 500 Due to Logs not accessible

### ISSUE THREAD

**Issue by awilliamson** [PufferPanel/PufferPanel#799]
During the installation, it is possible to fail to capture the PHP user for ownership of the log directory. If this is the case, `logs` will not be correctly owned, resulting in a generic `Error 500` on the landing page.

**Comment by puffrfish** [comment]
Do you know why in your case the PHP user was not captured?

The relevant function is https://github.com/PufferPanel/PufferPanel/blob/master/pufferpanel#L324-L350

We are checking the following directories for a www.conf:
/etc/php/7.0/fpm/pool.d/www.conf
/etc/php/*/fpm/pool.d/www.conf
/etc/php-fpm.d/www.conf

**Comment by awilliamson** [comment]
Apologies, I should have appended more information to the original issue. The PHP path being invalid for Arch Linux is indeed the cause of this log directory ownership problem, displaying symptoms as Error 500. However, this is more of a design point-of-view. If the correct operation of PufferPanel relies upon logs being correctly owned, then if ownership cannot be carried out during install, it should be a fatal error halting installation. It should not print and continue.

This is one of the issues I hope to fix with my upcoming changes for Arch Linux support; refactoring the PHP folder detection, as it currently suffers from [indent hadouken](http://i.imgur.com/BtjZedW.jpg) and appears in several places. I intend to refactor this into a utility function similar to load config, and also append the Arch Linux `/etc/php/php-fpm.d/www.conf` path to the ones being checked.
