### ISSUE TITLE
New Administrators cannot access server console

### ISSUE THREAD

**Issue by awilliamson** [PufferPanel/PufferPanel#801]
After adding two administrators, we added a third, which resulted in this person not being able to see server consoles at all. With 403 forbidden when trying to access the websocket.

This is caused by their scopes not being set in the database. For whatever reason the new administrators lack `server.start server.stop server.install server.file.get server.file.put server.file.delete server.kill server.log server.console server.console.send server.stats server.network sftp server.create server.delete server.edit server.reload node.stop` in their `oauth_clients` and `oauth_access_tokens` table entries. Not quite sure why this is the case, I've only done limited debugging to find the scope issue.

**Comment by LordRalex** [comment]
Fixed via https://github.com/PufferPanel/pufferd/commit/061568d3b012e5e3ad218779578c4372a295586b
