### ISSUE TITLE
Order the server list.

### ISSUE THREAD

**Issue by Incrementing** [PufferPanel/PufferPanel#803]
Based on [this](https://community.pufferpanel.com/topic/680/unordered-server-list) post.
The list of servers should be ordered as opposed to being listed in a random order every reload.

**Comment by bkraul** [comment]
That sounds sweet! Can the sort order be stored between logins?

**Comment by LordRalex** [comment]
It's not a saved setting, so it'd reset each time you visit the page, but the library I chose for this also exposes a search and better paging for it, so it should look a lot better. This also applies to the admin server list and the admin user list, so it's a lot more of an improvement.

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/PufferPanel/commit/01b3451103d040bb0297ed317e2eabb9fc72d2bc
