### ISSUE TITLE
Game Server Edit causes console issue

### ISSUE THREAD

**Issue by mapl** [PufferPanel/PufferPanel#805]
When editing, in my case the map to load, on a Tf2 Game Server Linux instance, the console mode switches from TTY to standard in the Game Server .json configuration file leading to unexpected results and causes various console issues on the Pufferpanel Webinterface.

**Comment by LordRalex** [comment]
Resolved 
https://github.com/PufferPanel/pufferd/commit/1a7a8fea216300b97101d73f82c76a8b31db3c82
