### ISSUE TITLE
Admin Edit Server Data empty page.

### ISSUE THREAD

**Issue by baxandrei** [PufferPanel/PufferPanel#806]
When i go to Edit Server Data, i don`t see any filed that can be edited.

https://i62.servimg.com/u/f62/17/31/96/85/screen11.png

**Comment by LordRalex** [comment]
Please use the community forums for issues, questions, or help with installation or configuration of PufferPanel. This issue tracker is only for confirmed bug reports. Please consider opening a thread on the community forums before opening an issue here.

**Comment by baxandrei** [comment]
seriously?
