### ISSUE TITLE
PocketMine-MP Outdated

### ISSUE THREAD

**Issue by alexbgameson** [PufferPanel/PufferPanel#810]
The link for the pocketmine phar is outdated. please update

**Comment by LordRalex** [comment]
Then you could give us the link to the new one, instead of a "fix it".

**Comment by alexbgameson** [comment]
Yes, but I dont have link to any github page. Just a link to a mediafire build thats always up to date.

http://download43.mediafire.com/gy19rxbrn5rg/kwdcto1nmio5071/PocketMine-MP.phar

**Comment by Omeryl** [comment]
@alexbgameson but isn't pocketmine-mp opensource? Where's the repo, and why aren't there releases on it?

**Comment by alexbgameson** [comment]
Yes PocketMine-MP is open source but the domain for thier releases changes every time they issue a new release on thier jenkins server.

**Comment by LordRalex** [comment]
Is https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh not valid anymore

**Comment by alexbgameson** [comment]
No its not. That link gives version 1.2.6 when 1.2.7 is the latest.

**Comment by LordRalex** [comment]
That is our URL which uses their Jenkins server which has 1.2.7. this is not in the current pufferd.

**Comment by LordRalex** [comment]
Or it is.

Either way, they need to get a good script that won't break. If they broke it, they need to fix it. I refuse to use MediaFire downloads for such things.

**Comment by LordRalex** [comment]
I have looked at their code and how this works.

Our URL is valid. They have not marked 1.2.7 as alpha. There is nothing we need to change.

**Comment by alexbgameson** [comment]
Oh ok! Thanks for checking!

**Comment by alexbgameson** [comment]
Can you please add Turanic software? https://github.com/TuranicTeam/Turanic
