### ISSUE TITLE
Add support to global multi user (moderators)

### ISSUE THREAD

**Issue by lucasdidur** [PufferPanel/PufferPanel#814]
Can you add support for user that can globally manager servers? Like subusers by server, but globally.

Sou then I add a user, and configure the servers that he has permissions and then what permissions they have (file manager, start, stop).

Thank you

**Comment by LordRalex** [comment]
I don't see what this makes it a "global", it's just a sub-user who's on multiple servers. This is already supported in that sense.

**Comment by lucasdidur** [comment]
I want that a single user can manage manny servers, like a global groups or single permissions.

**Comment by TeamGameRevolution** [comment]
You can do that with subusers. Just use the same mail for multiple servers, really.
