### ISSUE TITLE
Server won’t create

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [PufferPanel/PufferPanel#816]
error:
An error occurred while trying to connect to the remote node. Please check that the daemon is running and try again.
An error occurred trying to add a server. () []

Idk how to fix it

**Comment by ApertureDevelopment** [comment]
Wait, how did you fix it?

**Comment by Omeryl** [comment]
As we've mentioned in the past, the issues are meant for verifiable bugs. If you need support, please use the forums @ApertureDevelopment.

**Comment by ApertureDevelopment** [comment]
You: Shush. Noone replied on the forums, and I have every right to ask how he fixed the issue on a *closed* issue. https://community.pufferpanel.com/topic/773/can-t-create-new-server

**Comment by Omeryl** [comment]
@ApertureDevelopment You literally posted 17 minutes ago, to a forum topic, instead of opening your own. Please open your own topic, with as much information as possible, and someone can definitely help you. Patience is a virtue, and so is following the issue submission guidelines.

**Comment by ApertureDevelopment** [comment]
https://community.pufferpanel.com/topic/800/cannot-create-servers Already did, and since he had the same issue and never got a answere, despite 174 Views. Yeah definitely someone will help

**Comment by LordRalex** [comment]
If you have an issue using the panel, make a thread on the forum. Just because it's the same "error" doesn't mean it's the same issue.

Be patient when waiting for a response, especially when you bump a thread that's a year old.
