### ISSUE TITLE
Enable support for alternate databases

### ISSUE THREAD

**Issue by disconsented** [PufferPanel/PufferPanel#822]
Likely a niche change but something to consider, people may appreciate being able to use databases like Postgres or SQLite rather than just MariaDB/MySql (I believe it is technically possible now based on the conversations had)

**Comment by LordRalex** [comment]
src/routes/node/users/routes.php
src/core/oauth2.php
src/routes/daemon/routes.php
src/core/permissions.php

Places within the panel itself raw queries are used. 

Naturally installer would have no idea and won't work right, but we can tackle that another way.
