### ISSUE TITLE
MariaDB Issue and php errors

### ISSUE THREAD

**Issue by ApertureDevelopment** [PufferPanel/PufferPanel#830]
Our server is running the ISPConfig standard installation and we are havng a lot of toubles with PufferPanel.

First of the SQL script seems to not be operable by default. It throws this error message:
``Error Code: 1071. Specified key was too long; max key length is 767 bytes`` when creating the users table.

then next when I did a workaround for the first error I continued with the installer and everything seemed to work fine, until I opened the page and got greeted by a error 500. Here is the log for it:
```
[Wed Jul 11 13:04:38.777892 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: PHP Fatal error:  Uncaught Exception: The config file config.json does not exist. in /var/www/clients/client1/web1/web/src/core/con$
[Wed Jul 11 13:04:38.777951 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: Stack trace:
[Wed Jul 11 13:04:38.777959 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: #0 /var/www/clients/client1/web1/web/src/core/config.php(57): PufferPanel\\Core\\Config\\JsonConfig->__construct('config.json')
[Wed Jul 11 13:04:38.777966 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: #1 /var/www/clients/client1/web1/web/src/core/config.php(36): PufferPanel\\Core\\Config::checkStatus()
[Wed Jul 11 13:04:38.777972 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: #2 /var/www/clients/client1/web1/web/public/router.php(35): PufferPanel\\Core\\Config::config('logsDirectory')
[Wed Jul 11 13:04:38.777997 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr: #3 {main}
[Wed Jul 11 13:04:38.778004 2018] [fcgid:warn] [pid 15015] [client <removed>:4462] mod_fcgid: stderr:   thrown in /var/www/clients/client1/web1/web/src/core/config/jsonconfig.php on line 37
```

As a secure operation, each webspace has it's own user, to prevent anything being able to act outside of the assigned webspace. This is a Security standard which I would like to keep. 

As I saw that PufferFish creates config files outside of it's webspace folder, please don't do that. Stay within the webspace.

**Comment by LordRalex** [comment]
The panel is contained within it's own workspace for the panel code itself. What made you think it wasn't?

**Comment by ApertureDevelopment** [comment]
Hello,

When I run the installer it tries to write/change a config file in /etc.
Can you explain me how I can install the script without using the installer? The installer does some things I personally dislike

**Comment by LordRalex** [comment]
It does that for the daemon, which is an entirely different software. You can pass --withoutDaemon to the installer to not install that software.

Otherwise, the installer works in the directory you are running it in.

**Comment by ApertureDevelopment** [comment]
What about the SQL problem? I did a workaround, but the SQL querys have some problems

**Comment by LordRalex** [comment]
That issue I am aware of, and have already tried to fix it. It is only an issue when you are using an older MySQL version which defaults the ROW_FORMAT option to a different value than we expected.

What queries have problems otherwise. Your last error there is "there is no config.json where pufferpanel is installed at".

**Comment by ApertureDevelopment** [comment]
Actually the issue is described as just problematic with new versions of MySQL, as they changed the behaviour of the database. I am using the current verion of MariaDB which is more used then MySQL *coughts* MySQL is a security issue itself *coughts*

**Comment by ApertureDevelopment** [comment]
If you are a real system administrator you know how to secure ISPConfig, but there is no fix for the backdoors in MySQL.

Also LordRalex, I told you about the installation bug with the SQL. Test it with the actual version of Debian + MariaDB

**Comment by LordRalex** [comment]
If MySQL has backdoors, then you should be reporting them to Oracle, because they would be fixing them. 

Regardless,

**Comment by Omeryl** [comment]
@ApertureDevelopment I have been a professional systems admin for many, many years now. If you "are a real one," as you so pointed out, you typically have the know how not to need either PufferPanel or ISPConfig. But alas, here we are.

**Comment by ApertureDevelopment** [comment]
It got reported, and that over and over and over. 

@Omeryl Ok you "Professional" easy management is nothing to be ashamed of, but I guess you preffer being the whole day in the console writing scripts or running commands because that seems to be part of being a "Professional". ISPConfig does everything right in webspace generation, each website it's own user and per client a group. If you tell me you preffer sitting there the whole day like a idiot entering commands, instead of pressing 2 buttons, then okay. Guess you are a "Professional" and I have no idea what I am talking about. Guess I am no professional, because I use a webpanel to make my life easier. Guess I am not trained and certified, but hey you "Professional" you prop know better, so good work.

**Comment by LordRalex** [comment]
This is not the place to have this kind of argument.

**Comment by ApertureDevelopment** [comment]
For me this discussion is dropped *drops mic* I am out
