### ISSUE TITLE
Cannot permamently delete server

### ISSUE THREAD

**Issue by IdkMan2** [PufferPanel/PufferPanel#833]
I cannot remove server from panel, it looks like this:
https://image.ibb.co/hXJ6CT/2018_07_13_5.png
https://image.ibb.co/hmmRCT/2018_07_13_6.png

Both buttons gives me the same result - error.
If it matter: it was Spigot Docker Server.

PS: I have installed PufferPanel today, have mercy if it is my fault :)

**Comment by LordRalex** [comment]
Please use the [community forums](https://community.pufferpanel.com) for issues, questions, or help with installation or configuration of PufferPanel.

You will have to fix your log folder for pufferpanel to log the error correctly, people can explain that on the forum.
