### ISSUE TITLE
Question about Remote Requests

### ISSUE THREAD

**Issue by baxandrei** [PufferPanel/PufferPanel#834]
How I can use **Remote Requests**? I searched everywhere on the documentation site and found nothing about **Remote Requests**. I found [this page](https://community.pufferpanel.com/topic/110/send-console-commands-using-curl) on forum, but it does not work. How I can send the comand "tell user1 hi" for example, through **Remote Requests**?

On **X-Access-Server** I put server id (Server Id - 84319bc6-aa75-4175-ad0f-e2axxxxxxxxx). On **X-Access-Token** I put secret generated key (Secret key generated: 01e9c2c5e003ebxxxxxxxxxae4c12edc).

What is the problem, why doesn't it work, what am I doing wrong?

**Comment by LordRalex** [comment]
https://speca.io/PufferPanel/pufferd

The links you have are for the old Scales software, which hasn't been used in a long time.

**Comment by baxandrei** [comment]
And with this API, is it possible to create a php script to execute commands to the server?

**Comment by LordRalex** [comment]
Yes, however I've not fully documented all endpoints yet.

**Comment by baxandrei** [comment]
ok, i will wait, thanx.
