### ISSUE TITLE
Panel should display the readme.md for templates

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#836]
As part of the 1.3 refactor, templates are moving to our template repo. These templates provide a "readme.md" file which can contain any extra information about a template, such as dependencies or requirements.

The panel should read these templates readmes (they will still be installed on the server itself, they will not be using our repo as the source) and display it to the user during the installation step.

Example: https://github.com/PufferPanel/templates/tree/master/teamspeak3

The readme should be display on the panel.

Each readme will be called <templatename>.md, to match the json name. This should make it easy to both share and retrieve the files.

The build process will handle the mapping of the files so that distribution works as-is.

**Comment by khionu** [comment]
This is in 2.0, couldn't this be closed?
