### ISSUE TITLE
Inaccessible Nodes timeout Panel

### ISSUE THREAD

**Issue by khionu** [PufferPanel/PufferPanel#846]
I had a node that was setup on a temporary VPS for testing purposes. Deleting the VPS makes the node unavailable, and the panel times out trying to access it.

**Comment by LordRalex** [comment]
What page were you on?

**Comment by khionu** [comment]
Any and all pages will time out. Viewing a specific server, index, list of nodes, account settings, doesn't matter.

**Comment by LordRalex** [comment]
Noting for reference:

This occurs because the browser is waiting for the server-status call to finish on the index page before letting you then redirect when you've clicked a link. Unsure why it's doing that and don't have a way to fix it atm.
