### ISSUE TITLE
Sanitize MySQL password

### ISSUE THREAD

**Issue by Pandry** [PufferPanel/PufferPanel#849]
After a long time, I'm back, sorry for the absence.
I wanted to install again the panel, and I had the awesome luck of having a password ending for `\`.
This escaped the string terminator char and ruined my installation.

![totermw_2018-09-10_12-43-08](https://user-images.githubusercontent.com/17499836/45292981-270ec000-b4f7-11e8-8ff8-9ad259726b86.png)
![totermw_2018-09-10_12-19-25](https://user-images.githubusercontent.com/17499836/45292982-27a75680-b4f7-11e8-883f-036c0d11d51b.png)
![totermw_2018-09-10_12-18-32](https://user-images.githubusercontent.com/17499836/45292983-27a75680-b4f7-11e8-9e8e-e57bdadea227.png)

**Comment by Pandry** [comment]
I guess the generation command should be changed
https://github.com/PufferPanel/PufferPanel/blob/a669da0f3fcb9e27200b9236acdb53c803be05d7/pufferpanel#L84

It looks like that when the underscore(`_`) is preceded by  a minus (`-`), the "regex" expression is not respected:

```
[root@localhost ~]# for i in {1..15}; do \
> cat /dev/urandom | tr -dc 'a-zA-Z0-9,;.:#+*~@&%-_' | fold -w 32 | head -n 1\
> ;done
H6uo_1*WXS\B'-m.P'7M=cAu?naE#D*w
DPkZXNBTzI7(_EA1cwvnkEAjX\cQI:[M
z/pi8EBSVZzl2giZj]>HpM3TQl7FfnN;
l>*ibh/A2>0kYt%e[5plpMPR(+wIqH:*
e@mY6v_im<,rgH,'aX5B)R49i1xf>BUX
R4Ygww7\RM4~hd<:F?0Ard]~guxns6R0
qC:=K'm6>j,Gd+>=JBBdL9Pw[&2D7Q;3
QcmUBP0Tc_K5zk6H5Q^'Ag):d].%:cl:
%5YuiRzm?TF~XMXm9=teX]8XDXzo/qTq
8DVT*Q+)rk.\2sm+XVmg+E0gPM6.N'o1
]Z&^aZ4c<_U^tPDEFR*Lge5D#yqMBBO[
GL7;,hjRK=m=[FLFRRDhRPkVHUzdh2hd
-Mq0w=,FMruIs/SIGSb4?d3zshfjdJsM
Pt'0]Epd:3b~e%Y<6B0igRdIT7*p7;=2
m62kIxOE:NIA(_jtGhsk=OBl&Q~g(lW8
```
As you can tell there are multiple backslashes, but if we remove the underscore:
```
[root@localhost ~]# for i in {1..15}; do cat /dev/urandom | tr -dc 'a-zA-Z0-9,;.:#+*~@&%-' | fold -w 32 | head -n 1;done
agngtd#hG4JUgb2&Nsj-fJmBMAKYV9sr
DHgySOAO1rnbUypI:R3IOk*3F@-qA%&5
01wSAqsaBYHnrU:iG9-+&jdOU#tVEA-G
d@r%Ah.6:Sb1bvdJ40KwY6.rZulEU192
YE@7Muxxr1GuY2glLR%;9@GEc%aDt&qR
f4:ITS1hgxVucc+U%JQm~+KJ;~Fqd:mm
J@V#r1jmR*rU3n1mKV#we3OBJ2PV12jt
,QaK8Zdp0g@kjBn5#EZ:zi3%LZZ5v1nd
rjLTdceDjWLEu-AW4O*Tdrp*F20%ZzcW
Fi*~%TtDmF*Rj*avDGAt0Y;U0&sNbpuM
D%Nf#c*nHPWek3IM2,21YC*STAlz6@6k
Ga7nBj*CVbmZ8rFbrUxs+B-*iyj5+RkF
2VbXGNi4#V5:4BGi5qcbQA4ixZ2gJ5%D
Pb6OyMabgmAR0JOdwv@1evy;*@.*,akw
S*6Ui2~zZi@kf-YBmBv.4EFd.JlT;:K*
```
the password looks fine to me.

Otherwise, another possible solution could be using a string with all the allowed characters:
```
P="0123456789ABCDEFGHIJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz" && head -c 32 < /dev/urandom | tr '\000-\377' "$P$P$P$P$P" && echo
DVS6Uwg4PKt3zXvAxErKVxw7Vp3601PE
```

**Comment by Pandry** [comment]
I figured out that the minus (`:-_`) includes all these characters:
https://github.com/PufferPanel/PufferPanel/blob/a669da0f3fcb9e27200b9236acdb53c803be05d7/pufferpanel#L84

`:-;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`

**Comment by Pandry** [comment]
In my PR #850 I did try to keep the generated string the same, but I would suggest an algorithm like this one:
```
newPw=$(P="0123456789ABCDEFGHIJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz" && head -c 32 < /dev/urandom | tr '\000-\377' "$P$P$P$P$P" && echo)
```

**Comment by LordRalex** [comment]
I would rather just fix it for now. I have it planned to rewrite the installer anyways, so I'd don't really want to spend too much time on it right now.
