### ISSUE TITLE
TCP SYN to 54.39.104.196 dport 443 times out

### ISSUE THREAD

**Issue by lol768** [PufferPanel/PufferPanel#872]
https://thankyou.pufferpanel.com is not responsive
(via JuanDelPueblo in #admincraft, irc.esper.net)

_Thanks_ in advance <sub>sorry I couldn't help myself</sub>

**Comment by LordRalex** [comment]
I disabled the service since we deprecated it as we can track stats for usage (which is partly what it did) and when we did a service migration I did not restore it.

Since it hurts the installer, I'll fix it so curl should not take forever to reject it.

**Comment by lol768** [comment]
This fails fast now
