### ISSUE TITLE
Installing throws error on DB user creation.

### ISSUE THREAD

**Issue by InflamedSebi** [PufferPanel/PufferPanel#880]
when running './pufferpanel install' the script has this error:
```
Creating pufferpanel account and installing database...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'kB:qZFiNhHso4Oa:tGe3rsxeFQZiKmxC'' at line 1
MySQL has been configured and the database was installed
Switching to new user for further commands
------------
```

and then ongoing this:
`ERROR 1045 (28000): Access denied for user 'pufferpanel'@'localhost' (using password: YES)`

so somethings seems to be incorrect during user creation.... Any help?

OS and mysql:
/usr/sbin/mysqld  Ver 8.0.19-0ubuntu0.19.10.3 for Linux on x86_64 ((Ubuntu))

**Comment by InflamedSebi** [comment]
so, seems like the implicit user creation via GRANT does not work for mysql 8+ and is deprecated a while now.
Fixed it for myself by splitting it to USER CREATE and GRANT.

**Comment by InflamedSebi** [comment]
Also mysql changed user authentication in 8.0.4 due to security concerns, which will cause Error 500 on the Webpage and `PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client #2054 in /srv/pufferpanel/vendor/j4mie/idiorm/idiorm.php:328 caused by PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /srv/pufferpanel/vendor/j4mie/idiorm/idiorm.php:328` in the /srv/pufferpanel/logs/exception.log

this can be worked around if you create the user with `CREATE USER 'pufferpanel'@'localhost' IDENTIFIED WITH mysql_native_password BY '${pass}';` but supporting the new authentication method would be superior ofc.
see: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-4.html for details

**Comment by Misteralex007** [comment]
So what do we have to do to fix thie issue ?
I'm trying to install PufferPanel as well on Ubuntu 20.04 LTS and MySQL server v8

**Comment by demigh0d** [comment]
To fix the mysql user create; look for the following lines in the file 'pufferpanel: 

     mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
      GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'${newHost}' IDENTIFIED BY '${newPw}';
      GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'localhost' IDENTIFIED BY '${newPw}';

Replace them with the following:

    mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
     CREATE USER 'pufferpanel'@'${newHost}' IDENTIFIED BY '${newPW}';"

    mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
     GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'${newHost}';
     GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'localhost';"

**Comment by agucova** [comment]
I can confirm that works, I'll make a PR.

**Comment by alexbergsland** [comment]
> To fix the mysql user create; look for the following lines in the file 'pufferpanel:
> Replace them with the following:
> 
> ```
> mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
>  CREATE USER 'pufferpanel'@'${newHost}' IDENTIFIED BY '${newPW}';"
> 
> mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
>  GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'${newHost}';
>  GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'localhost';"
> ```

Shouldn't that be:
 ```
     mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
     CREATE USER 'pufferpanel'@'${newHost}' IDENTIFIED WITH mysql_native_password BY '${newPW}';"

    mysql -h ${mysqlHost} -P ${mysqlPort} -D ${mysqlDb} -u ${mysqlUser} --password="${mysqlPass}" -e "
     GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'${newHost}';
     GRANT ALL PRIVILEGES ON pufferpanel.* TO 'pufferpanel'@'localhost';"
 ```
Anyway, I finally got it to work by editing the script to my paste above and then hard coding the random password so it was the same every time. Then manually creating the user and granting privileges (I use a remote host so I wanted to know that was not the cause for my troubles).
Then I ran the script again, it would complain that it could not create the pufferpanel user (because I had already created it manually) but it would still finish and the login page would appear.

**Comment by VottusCode** [comment]
It is great that the login page has appeared, but does it go further than that? If PufferPanel is not tested for MySQL 8, i can probably expect some bugs, but is it usable or not?

**Comment by InflamedSebi** [comment]
Don't use version 1.x any more. 2.x is stable enough for normal use and there are great features in the pipeline. This issue was solely present in version 1.x which is out of support quite a while now.

**Comment by VottusCode** [comment]
@InflamedSebi Yeah, my bad. For some reason when I was looking up the docs I was pointed to the old install script which had this issue. I realized that it was the old version.
