### ISSUE TITLE
PufferD game servers don't auto-start on boot?

### ISSUE THREAD

**Issue by kmott** [PufferPanel/PufferPanel#881]
Hello!

First, thank you for creating a modern game management server that actually works--I REALLY enjoy using it.

I did notice that when my pufferd servers restart, the pufferd daemon starts on-boot, but pufferd itself doesn't start any games it's aware of--is there a setting somewhere to enable auto-start on (re)boot somehow (I have to click the green `start` button in the UI to get it to start after boot).

I am currently running pufferd v1.2.8 and pufferpanel v1.2.4.  Thank you!

**Comment by LordRalex** [comment]
You need to add the following field to the "run" object in the server's json file, then "Reload" the server through the admin console.

"autostart": true

There is also autorecover and autorestart as well, which will restart the server on a non-0 exit code and restart on a 0-exit code respectfully.

**Comment by kmott** [comment]
Thank you very much @LordRalex!  For anyone that stumbles on this later, you can easily add those 3 options to the server JSON using something like this (make sure to save the output of the cmd to a new file before replacing your game server's existing JSON file):

```
jq -r '.pufferd.run += { "autostart": true, "autorecover": true, "autorestart": true }' my-gameserver.json
```
