### ISSUE TITLE
Ability to write to file after server edit

### ISSUE THREAD

**Issue by codevski** [PufferPanel/PufferPanel#891]
Wondering if it's possible to write to a file when editing a server. 

For example:
- Stop a running server that uses a config file when starting.
- Edit the server and once saving to write / update the server file.
- Start the server again with an updated config

If it is currently supported can we have docs on it? If not can we see it implemented in future releases?

**Comment by LordRalex** [comment]
An endpoint exists for this already: https://speca.io/PufferPanel/pufferd/2.0#POST-server-id-reload

You can use the "Reload" button in the admin side of the server to trigger this call.

**Comment by codevski** [comment]
![image](https://user-images.githubusercontent.com/1435321/80659292-e1d44300-8acb-11ea-8e25-0a5a3af9dcd2.png)

Do you mean this? If so that doesn't write to file. Accessed file from terminal and it hasn't been updated...

**Comment by LordRalex** [comment]
What kind of file do you refer to, a file within the server itself?

**Comment by codevski** [comment]
Yep so during install template I have something like this for example 

``` {
          "type": "writefile",
          "text": "# License key for your server (https://keymaster.fivem.net)\nsv_licenseKey ${licensekey}\n",
          "target": "resources/server.cfg"
        }```

Then when you edit the server and save, I would like to update server.cfg with updated `licensekey` thats located in resources/server.cfg

**Comment by LordRalex** [comment]
That makes more sense now.

**Comment by LordRalex** [comment]
This handled now using a "pre" task. As part of run, you can configure it to run any command or operation that you want.
