### ISSUE TITLE
Websockets being loaded over HTTP

### ISSUE THREAD

**Issue by cryptographic1337** [PufferPanel/PufferPanel#895]
When one views a server, the websockets are loaded over an HTTP connection, even with require secure connections on. The browser then blocks the request, making it impossible to view a server.
```
index:428 Mixed Content: The page at 'https://panel.example.com/node/index' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://panel.example.com:5656/server/uuid/console?accessToken=16bb6357b0298b4ff5cfc5f4038e3ca1'. This request has been blocked; this endpoint must be available over WSS.
```

**Comment by LordRalex** [comment]
You need to enable HTTPS on the daemon as well.

https://www.pufferpanel.com/docs/using-letsencrypt-with-pufferpanel#enabling-https-on-pufferd
