### ISSUE TITLE
Auto-deploy node doesn't add space

### ISSUE THREAD

**Issue by jakeau** [PufferPanel/PufferPanel#898]
Auto deploy source doesn't include space in deploy script
Received 'sudo bash -c 'source <(curl -sSLkhttp'
expected 'sudo bash -c 'source <(curl -sSLk http'

**Comment by jakeau** [comment]
Also in deployment script ./pufferd --install --auth has no space

**Comment by LordRalex** [comment]
This is an issue with later versions of PHP. Use PHP 7.2 for the best support.
