### ISSUE TITLE
v1.2.4 -  Mysql user with grant option (debug log #bug) - ubuntu 20.04

### ISSUE THREAD

**Issue by alexonbstudio** [PufferPanel/PufferPanel#899]
after install
MySQL Configuration
Enter the MySQL host [localhost]:
Enter the MySQL port [3306]:
Enter the MySQL username (MUST HAVE GRANT) [root]: root
Enter the MySQL account password: mysql: [Warning] Using a password on the command line interface can be insecure.

Creating pufferpanel account and installing database...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'p'0'1' at line 1
MySQL has been configured and the database was installed
Switching to new user for further commands

Configuring site details
Please enter the domain or IP (if you do not have a domain) for your site (do NOT include http(s)://): domaine.tld
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'pufferpanel'@'localhost' (using password: YES)
Settings saved to database

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'pufferpanel'@'localhost' (using password: YES)

**Comment by alexonbstudio** [comment]
seem to ubuntu 18.04 TLS:
Enter the MySQL account password: mysql: [Warning] Using a password on the command line interface can be insecure.

**Comment by derpydm** [comment]
This seems to be an issue with your MySQL password. I've tried a v1.2.4 install on 18.04 and it works fine.

**Comment by PotatoSauceVFX** [comment]
Is 20.04 just not supported?

**Comment by derpydm** [comment]
I believe several other people got it working on their own 20.04 machines.

**Comment by PotatoSauceVFX** [comment]
18.04 works fine for me. Can anyone share their work-around for 20.04?
