### ISSUE TITLE
A bug in centos 7 for v1 of panel

### ISSUE THREAD

**Issue by bagou4502** [PufferPanel/PufferPanel#902]
<img width="606" alt="Capture" src="https://user-images.githubusercontent.com/53863206/82941754-323da400-9f97-11ea-830e-4c1cae7a72e2.PNG">
Hello 

A bug in centos 7 for v1 of panel

**Comment by bagou4502** [comment]
i got 20000000000mo of ram????

**Comment by derpydm** [comment]
This issue (memory being shown in bytes?) was fixed in Alpha 2. Update to fix.

nepcore already answered your question on Discord - don't open an issue
