### ISSUE TITLE
Get error can not cerate server

### ISSUE THREAD

**Issue by broken1arrow** [PufferPanel/PufferPanel#904]
I'm not expert on linux or servers.

I get this error
An error occurred while trying to connect to the remote node. Please check that the daemon is running and try again.
An error occurred trying to add a server. () []

Daemon is running, I have set a external ip and open port 5656 in node.

Running Version v1.2.4 and PHP 7.4

New install. And way i can only use paper 1.14.2 or older?

**Comment by LordRalex** [comment]
Ask on our discord
https://discord.gg/YwUXaD6
