### ISSUE TITLE
[2.0] RPM scriptlets do not handle errors

### ISSUE THREAD

**Issue by jansennerd10** [PufferPanel/PufferPanel#905]
- The PREUN script fails if the pufferpanel service is not registered
    - This makes it impossible to uninstall the package if the installation is broken in this way
- The PREIN script fails if the 'pufferpanel' user is already created

In both of the above cases, the script should simply continue; instead, it exits with a non-zero code, which forces RPM to cancel (un)installation. Generally, RPM scriptlets should always exit with code 0 unless there is a very good reason to block the action being taken (see: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_syntax).

**Comment by LordRalex** [comment]
It already should be handling it with a || true, so it should be either running the command properly, or return true, which should be a non-zero code.

Do you have your logs?

**Comment by jansennerd10** [comment]
Here is the output from the first case:

```
[jansennerd10@mc-01 ~]$ sudo dnf remove pufferpanel
Dependencies resolved.
================================================================================
 Package           Architecture Version               Repository           Size
================================================================================
Removing:
 pufferpanel       x86_64       2.0.0~alpha.3-1       @@commandline        47 M

Transaction Summary
================================================================================
Remove  1 Package

Freed space: 47 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: pufferpanel-2.0.0~alpha.3-1.x86_64                     1/1 
Failed to stop pufferpanel.service: Unit pufferpanel.service not loaded.
error: %preun(pufferpanel-2.0.0~alpha.3-1.x86_64) scriptlet failed, exit status 5

Error in PREUN scriptlet in rpm package pufferpanel
  Verifying        : pufferpanel-2.0.0~alpha.3-1.x86_64                     1/1 
Installed products updated.

Failed:
  pufferpanel-2.0.0~alpha.3-1.x86_64                                            

Error: Transaction failed
```

And from the second:
```
[jansennerd10@mc-01 ~]$ sudo dnf install pufferpanel
Last metadata expiration check: 0:00:26 ago on Fri 26 Jun 2020 10:14:41 PM EDT.
Dependencies resolved.
================================================================================
 Package         Arch       Version           Repository                   Size
================================================================================
Installing:
 pufferpanel     x86_64     2.0.0-alpha.1     pufferpanel_pufferpanel      19 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 19 M
Installed size: 48 M
Is this ok [y/N]: y
Downloading Packages:
pufferpanel-2.0.0-alpha.1.x86_64.rpm             11 MB/s |  19 MB     00:01    
--------------------------------------------------------------------------------
Total                                            11 MB/s |  19 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: pufferpanel-2.0.0-alpha.1.x86_64                       1/1 
useradd: user 'pufferpanel' already exists
error: %prein(pufferpanel-2.0.0-alpha.1.x86_64) scriptlet failed, exit status 9

Error in PREIN scriptlet in rpm package pufferpanel
  Verifying        : pufferpanel-2.0.0-alpha.1.x86_64                       1/1 
Installed products updated.

Failed:
  pufferpanel-2.0.0-alpha.1.x86_64                                              

Error: Transaction failed
```

If there are additional logs somewhere, let me know where I can find them and I'll be happy to provide.

**Comment by jansennerd10** [comment]
> or return true, which should be a non-zero code.

I'm not sure if this is a typo, but RPM treats an exit code of 0 as success and anything else as failure.

**Comment by LordRalex** [comment]
The last one is alpha one, which wasn't quite as smooth for it. That would explain why it doesn't work.

Looks like the uninstall is missing it's wrapper though.

And yes, i meant true being the exit code 0, not non-zero.

**Comment by LordRalex** [comment]
I've pushed a fix for the uninstall
https://github.com/PufferPanel/PufferPanel/commit/5c836c5f50b0b6dfaad70eee8a9e72718e5eca65

This will go out with alpha 4, which is not on the roadmap yet. The next release will be redoing the versioning to get it more ready for a "formal" release.

**Comment by jansennerd10** [comment]
The reason I installed alpha 1 is that I initially tried to install alpha 3 from the package in GitHub releases. That package didn't register the pufferpanel service, so I decided to uninstall and follow the directions to go through the repository. I uninstalled with `--no-preun` after encountering the first problem, and then installed from the repo, which gave me the alpha 1 version.

(If alpha 3 should create the service when installed from the RPM in GitHub releases, I'll test again to be sure and then create a separate issue.)

**Comment by LordRalex** [comment]
Alpha 3 should create the service.

What version is your OS? I think with RPM, the way it did alpha 1 screwed up things, so I may just end up removing alpha 1 from the repo.

**Comment by jansennerd10** [comment]
I'm running CentOS 8.

**Comment by LordRalex** [comment]
I just went through and removed the old versions. 

Once this replicates (it may take an hour...), you can try to re-install pufferpanel to get the latest version directly without specifying a version.
