### ISSUE TITLE
Adding own template in alpha-3 failing  'currentMode is not defined'

### ISSUE THREAD

**Issue by tiramon** [PufferPanel/PufferPanel#907]
When i try to add a template in the UI an press the save button i get a 'currentMode is not defined' in the console
![image](https://user-images.githubusercontent.com/642242/86575864-371f4b80-bf78-11ea-86db-4d59b86d3624.png)

**Comment by nepcore** [comment]
That bug was in alpha 2 and fixed with alpha 3, I can also no longer replicate it on an alpha 3 setup, so make sure you're actually not still on alpha 2 (and make sure you're not dealing with browser cache, just to be safe)

**Comment by tiramon** [comment]
ok ... no idea why, but i guess the problem was the browser cache ...
