### ISSUE TITLE
The web file managers upload function doesn't handle file names correctly

### ISSUE THREAD

**Issue by nepcore** [PufferPanel/PufferPanel#931]
The upload function of the web file manager does not url encode file names which causes problems when the file name contains characters like for example `#`, especially when these happen to be the first character of the file name

**Comment by Pandry** [comment]
Hi!
After a long time I'm back using PufferPanel and here I am trying to start contributing back again!

As far [as I can read](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations), the allowed file names in a POSIX-compatible filesystem should match this RegEx: `^[^-][a-zA-Z0-9_\-\.]+$`
In my opinion the best way would be to check every file name to fully match the RegEx.

**Comment by nepcore** [comment]
The POSIX entry in the list you linked sounds to me like a definition of the minimum supported by POSIX compliant file systems
I know from recent experience that both NTFS and EXT4 allow more than just those chars (and that more than those are commonly used)

Also, the issue here isn't actually the file system, it's the fact that the file name is added to the URL of the upload request and characters like `#` and `?` for example have special meaning there
URL encoding those characters fixes that issue without adding the need to somehow explain to a user (who might not necessarily have any knowledge of file systems) why they can name a file on their computer `#?!@` but somehow PufferPanel can't handle that except if the file gets to the server by any means other than the web file manager
IMO if the servers file system cannot handle some file name it's better for the API to handle that and return an error so the frontend doesn't need to make random guesses at what the server might be able to handle

**Comment by Pandry** [comment]
Yup, the one listed is the bare-minimum supported file name.
IMO we should stand to a bare-minimum standard to optimize compatibility (and avoid having files such as `##old.server.properties!!`) and do a check both server side (a "dummy" regex check that either returns ok or not) and a more articulated one on the frontend that tells the user that a file name cannot contain the `#`,`?`,`!` and `@` chars

**Comment by nepcore** [comment]
I don't see why we should go for a POSIX-only approach when we can easily achieve support for just about everything including, but not limited to, POSIX
If the frontend encodes file names correctly the backend can check if the file system can handle the file name
If it can, all is good, write the file, we're done
If it can't, answer 500 with the body containing an error code specific to the file name not being supported (assuming that go can actually tell that the file name is the issue)
The frontend can then pick up on that error code and tell the user what is going on
One could maybe even have the backend return the file system type (assuming that doesn't have problematic security implications) with that error and define very specific messages for all common file systems explaining what exact chars are and aren't allowed
That would mean just as much compatibility (more actually since it can even handle file systems that aren't POSIX compliant) and no issues when a user tries to upload some Minecraft modpack like RLCraft which has a file `# LibLoader.jar` in the mods directory (that is how I found the problem)

**Comment by Pandry** [comment]
Oh, ok.
Didn't see that coming.
Didn't know that some mods use such "crappy" names.
In this case I guess we could just URL encode, but I still think there should be some kind of whitelist (both on frontend and on backend) (I wouldn't like attempting to write a file named `Filen%20%00`)

**Comment by nepcore** [comment]
The `%` sign would obviously need encoding as well
Also, in your example you have `touch` parse the output from `echo` and because standard is to consider 0x00 as the end of a string I'd not be surprised if that is already be cut away by your shell or at least `touch` itself and the 0x00 probably never touches the file system
But I get your point and sure, trying to write actual control characters is probably not the best of ideas, however, I doubt the average user will ever run into that and there are so many ways to manipulate JS code (plus the fact that you can just make the HTTP requests yourself because API) that I don't think trying to catch that on the frontend is worth the effort
Though, yes, I do agree that _if_ the file system functions in go don't handle that already, we should definitely check for any control chars

**Comment by Pandry** [comment]
I was not talking about an un-encoded percent sing, but rather a crafted request having (for example) a null char.
I also agree that the example in this case is not accurate at all and that this is probably `touch` truncating the string, but you got the point.
What I'm worried about is that Go could allow something I'm not seeing.
Under this point of view I would rather treat any kind of user input as unsafe and would adopt a whitelist, but that would be my approach.
I tested this program in my PC ([here a link to the playground](https://play.golang.org/p/L2z4Owl66B2)):
```
package main
import "io/ioutil"
func main(){
  if err := ioutil.WriteFile("./hello.txt", []byte("Hello world!"), 777); err != nil {panic(err)}
  if err := ioutil.WriteFile("./hello\x20World.txt", []byte("Hello world!"), 777); err != nil {panic(err)}
  if err := ioutil.WriteFile("./2\x3E1.txt", []byte("Hello world!"), 777); err != nil {panic(err)}
  if err := ioutil.WriteFile("./hello\x00Null.txt", []byte("Hello world!"), 777); err != nil {panic(err)}
}
```
And in fact the null char returns an error:
![image](https://user-images.githubusercontent.com/17499836/95738374-69cc9480-0c89-11eb-8547-954c2c1c3169.png)

But I would be cautios anyway
