### ISSUE TITLE
API: start, stop, kill server

### ISSUE THREAD

**Issue by jstasiaczek** [PufferPanel/PufferPanel#940]
Hi,
I was trying to use you API to start/stop/kill server but I have problem when I'm trying to do this.
I created new user that is not admin, and I granted him only to start/stop/kill and send command to minecraft server. When I'm calling /auth/login/ endpoint with json:
```
{
    "username": "the_user",
    "password": "some_password"
}
```
I'm receiving following:
```
{
    "session": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzZXNzaW9uIiwiZXhwIjoxNjA0MTc1NDU4LCJpYXQiOjE2MDQxNzE4NTgsInN1YiI6IjEiLCJwdWZmZXJwYW5lbCI6e319.ZLLIkd1uL5rG8pzwQo56ommPvLBgmhJ2BzgOpiUU-bGQ8KD7_qEisN1zb-9ICVvyi1fjgJx0qCEKul_mF8VHZg",
    "scopes": [
        "servers.admin",
        "servers.create",
        "nodes.view",
        "nodes.deploy",
        "nodes.edit",
        "templates.view",
        "users.view",
        "users.edit",
        "servers.view"
    ]
}
```
Then I trying to call /daemon/server/e6bdac4a/start
I'm setting puffer_auth or Authorization header (I tried many possibilities) but I always receive error:
```
{
    "error": {
        "msg": "missing scope",
        "code": "ErrMissingScope",
        "metadata": {
            "scope": "servers.start"
        }
    }
}
```
but when I'm connecting to Websocket /proxy/daemon/socket/e6bdac4a with puffer_auth cookie, and I'm sending command like pufferpanel frontend I can start/stop/kill server without any problem.

It is hard to find any api doc, so I was reading pufferpanel code to achieve anything (maybe this is a problem).
Am I missing something or am I doing something wrong?

**Comment by LordRalex** [comment]
The token you get for login is not applicable to the /daemon endpoint due to differences. You should use /proxy anyways because it handles stuff for you.
