### ISSUE TITLE
Add an option to disable registration through the webinterface

### ISSUE THREAD

**Issue by adroslice** [PufferPanel/PufferPanel#942]
This should be as simple as a boolean option like "panel.settings.allowRegistration" to hide the registration button, disable the registration page/view and disabling the API endpoint (either removing it, or always returning an error). It's been requested, or at least asked about a few times on Discord:
[Screenshot](https://i.imgur.com/KHe71tz.png)

This is not a high priority issue at all, but I believe it'd be helpful to at least have it open. At the moment, the only theoretical way to disable registration is to hide the register button using a theme with custom CSS, and setting up a reverse proxy to block requests to the register endpoint.

**Comment by LordRalex** [comment]
The other problem is that you have to deal with allowing new users via the "add user" feature. I'd prefer they "register" so that it is the same flow, so we can't just delete the button.

**Comment by KlutzyBubbles** [comment]
Would like to second this suggestion, in response to lordralex, you might prefer that users register, but others wont. An option to disable registering will make it easier for most and you can still leave it on for yours.

I am very surprised this wasnt added in when the registration page was made, as a interface that i would assume targets mostly private server admins, i wouldnt see why a register page be default (regardless of it not giving any permissions on a register)

**Comment by OllieSteam** [comment]
You can remove register by editing the JS code.
if you remove this block from `chunk-2d2086b7.0251d16a.js` inside the folder js at the Webroot folder.
`t("v-btn",{attrs:{text:"",block:"",to:{name:"Register"}},domProps:{textContent:s._s(s.$t("users.RegisterLink"))}})`
This removes the button on login but not the /auth/registration page.
`chunk-3d8c34dc.1975b959.js` is the registration page in minified JS so after unminify the code you can remove the backend/frontend and add ur own script to re route users back to the login page.
**I would suggest making backups before attempting this.**

**Comment by disconsented** [comment]
chunk names are not guaranteed to be the same, just use the supported config option `panel.registrationEnabled` instead.

**Comment by nepcore** [comment]
you could also do the much more sensible thing and use that checkbox on the settings page of the panel which also survives updates unlike messing about in the js, plus, those file names can change with every version
