### ISSUE TITLE
Error when trying to edit a server.

### ISSUE THREAD

**Issue by EarlyGamer45** [PufferPanel/PufferPanel#945]
When i try to see a server it gives this error and if i restart the pufferpanel service it give's the same error.
Error: { "message": "Request failed with status code 403", "name": "Error", "stack": "Error: Request failed with status code 403\n at t.exports (http://<ip>:8080/js/chunk-vendors.25ec2db5.js:7:79339)\n at t.exports (http://<ip>:8080/js/chunk-vendors.25ec2db5.js:20:57976)\n at XMLHttpRequest.p.onreadystatechange (http://<ip>:8080/js/chunk-vendors.25ec2db5.js:37:44703)", "config": { "url": "/api/servers", "method": "get", "params": { "page": 1, "limit": 10 }, "headers": { "Accept": "application/json, text/plain, */*", "Authorization": "Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzZXNzaW9uIiwiZXhwIjoxNjA0NTEyNTM5LCJpYXQiOjE2MDQ1MDg5MzksInN1YiI6IjIiLCJwdWZmZXJwYW5lbCI6e319.oZdsygw9oMu2EEFBs8uwj9nEMmEx6slitZ2HY4KB2aHzA2vyxvvHtXW0pCTHuTphxMfkIcnYlJ1fN5_Xk4ia8w" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }.

**Comment by nepcore** [comment]
`status code 403` means your user does not have permission, I'd assume you probably fell for #925 and assumed that that permission should not be granted, but despite the label it actually only allows a user to see the servers they have been given access to and should therefore be granted in most cases

**Comment by EarlyGamer45** [comment]
but i'm logged in with admin account..

**Comment by EarlyGamer45** [comment]
I fixxed the problem, i modified a normal user account but it overwrited my admin account so with ssh i created a new admin account so i  edited my admin normal account and it worked just fine. but i noticed that modifing the normal user account (previous) he overwrited all account with deleting all informations of 3 account. is that normal??
