### ISSUE TITLE
[Security] Sub-users without run command permissions can run commands.

### ISSUE THREAD

**Issue by AwesomestCode** [PufferPanel/PufferPanel#950]
Title says it all. You don't need to do anything special, just create a new sub user with the view console perm but not the send command to console perm, observe how you can still send commands to console.

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/PufferPanel/issues/941

**Comment by AwesomestCode** [comment]
Whoops, sorry for the duplicate. Thanks!
