### ISSUE TITLE
Advanced docker options

### ISSUE THREAD

**Issue by dada513** [PufferPanel/PufferPanel#961]
Right now docker in PufferPanel uses the "host" setting, which disables network isolation.
There is also no way to set other docker options.
It would be very useful for templates to be able to further configure docker, like opening ports, limiting disk space, etc.

**Comment by bad-exe** [comment]
Agreed

**Comment by FriendlyGamer** [comment]
> Right now docker in PufferPanel uses the "host" setting, which disables network isolation.

That's my biggest pain point with this software at the moment. I would really love to sublease the node that we are renting in an effort to support our community without directly relying our community members to tip the hat. But rather to sublease the "excess" resources on our node.  

So if  at the minimum they can get the networking isolated then that would be a wonderful thing for us.

**Comment by LordRalex** [comment]
We already support it, the UI just doesn't expose it.
It follows the standard docker naming. Goes with the image.

	Binds       map[string]string `json:"bindings,omitempty"`
	NetworkMode string            `json:"networkMode,omitempty"`
	Network     string            `json:"networkName,omitempty"`
	Ports       []string          `json:"portBindings,omitempty"`

**Comment by FriendlyGamer** [comment]
> We already support it, the UI just doesn't expose it.
> It follows the standard docker naming. Goes with the image.
> 
> ```
> Binds       map[string]string `json:"bindings,omitempty"`
> NetworkMode string            `json:"networkMode,omitempty"`
> Network     string            `json:"networkName,omitempty"`
> Ports       []string          `json:"portBindings,omitempty"`
> ```

I understand but I am not quite sure how to make this the default on our node. Could steps be explained on how do this "in the back" and get Pufferpanel software to respect them on every instance? 

I researched this heavily yesterday but I am confused on how to go about this.

**Comment by dada513** [comment]
I am confused too. Can you give me an example on how to do that? Do I put this in the image name or what

**Comment by LordRalex** [comment]
The server json will accept fields called the following:

bindings: A list of directories to mount to the container as well. Key is the source path, value is the target in the container.
networkMode: The "mode" that the network should be using. Refer to https://docs.docker.com/network/#network-drivers for the names
networkName: The name of the network the container should join (in case you made multiple docker networks for containers to allow X and Y to talk, but not to A and B)
ports: The ports to expose, follows the docker convention for defining ports (

```json
{
  "type": "docker",
  "image": "mycustomimage",
  "bindings": {
       "/hostfolder": "/containerfolder"
   },
  "networkMode": "bridge",
  "networkName": "mcnetwork",
  "Ports": [
      "ip:publicPort:privatePort/proto"
   ]
}
```

**Comment by FriendlyGamer** [comment]
> The server json will accept fields called the following:
> 
> bindings: A list of directories to mount to the container as well. Key is the source path, value is the target in the container.
> networkMode: The "mode" that the network should be using. Refer to https://docs.docker.com/network/#network-drivers for the names
> networkName: The name of the network the container should join (in case you made multiple docker networks for containers to allow X and Y to talk, but not to A and B)
> ports: The ports to expose, follows the docker convention for defining ports (
> 
> ```json
> {
>   "type": "docker",
>   "image": "mycustomimage",
>   "bindings": {
>        "/hostfolder": "/containerfolder"
>    },
>   "networkMode": "bridge",
>   "networkName": "mcnetwork",
>   "portBindings": [
>       "ip:publicPort:privatePort/proto"
>    ]
> }
> ```

OKAY so here what my template looks like right now... 
```
{
    "type": "minecraft-java",
    "data": {
        "eula": {
            "type": "boolean",
            "desc": "Do you agree to the Minecraft EULA?",
            "display": "EULA Agreement (true/false)",
            "required": true,
            "value": "false"
        },
        "ip": {
            "type": "string",
            "desc": "What IP to bind the server to",
            "display": "IP",
            "required": true,
            "value": "0.0.0.0"
        },
        "memory": {
            "type": "integer",
            "desc": "How much memory in MB to allocate to the Java Heap",
            "display": "Memory (MB)",
            "required": true,
            "value": "2048"
        },
        "motd": {
            "type": "string",
            "desc": "This is the message that is displayed in the server list of the client, below the name. The MOTD does support <a href='https://minecraft.gamepedia.com/Formatting_codes' target='_blank'>color and formatting codes</a>.",
            "display": "MOTD message of the day",
            "required": true,
            "value": "A Minecraft Server\\n\\u00A79 hosted on PufferPanel",
            "userEdit": true
        },
        "port": {
            "type": "integer",
            "desc": "What port to bind the server to",
            "display": "Port",
            "required": true,
            "value": "2556"
        },
        "version": {
            "type": "string",
            "desc": "Version of Minecraft to install (<a href='https://papermc.io/downloads'>Paper maintained versions</a>). Must be specified as a release number, e.g. 1.16.1",
            "display": "Version",
            "required": true,
            "value": "1.16.4"
        }
    },
    "display": "Tuinity - Minecraft",
    "environment": {
        "type": "standard"
    },
    "install": [
        {
            "files": [
                "https://ci.codemc.io/job/Spottedleaf/job/Tuinity/lastSuccessfulBuild/artifact/tuinity-paperclip.jar"
            ],
            "type": "download"
        },
        {
            "source": "tuinity-*.jar",
            "target": "tuinity.jar",
            "type": "move"
        },
        {
            "target": "server.properties",
            "text": "server-ip=${ip}\nserver-port=${port}\nmotd=${motd}\n",
            "type": "writefile"
        },
        {
            "target": "eula.txt",
            "text": "eula=${eula}",
            "type": "writefile"
        }
    ],
    "run": {
        "command": "java -Xms${memory}M -Xmx${memory}M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Djline.terminal=jline.UnsupportedTerminal -jar tuinity.jar",
        "stop": "stop",
        "environmentVars": {},
        "pre": [],
        "post": []
    },
    "supportedEnvironments": [
        {
            "type": "standard"
        },
        {
            "image": "adoptopenjdk/openjdk11:jdk-11.0.9_11.1-alpine-slim",
            "type": "docker"
        }
    ],
    "name": "minecraft-paper"
}
``` 
So by your example in the JSON editor I need to do the following from... 
```
  {
            "image": "adoptopenjdk/openjdk11:jdk-11.0.9_11.1-alpine-slim",
            "type": "docker"
        }
``` 
To...
 ```
  {
            "image": "adoptopenjdk/openjdk11:jdk-11.0.9_11.1-alpine-slim",
            "type": "docker"
   },
  "networkMode": "bridge",
  "networkName": "mcnetwork",
  "portBindings": [
      "ip:{port}:{port}/tcp"
        }
```  
Would expose the port inputted in Pufferpanel's server creation editor and server's editor on TCP protocol to the outside internet right? Assuming the network name exists (in the example mcnetwork) in the host itself right?   

Thanks very much in advance!

**Comment by LordRalex** [comment]
```json
 {
           "image": "adoptopenjdk/openjdk11:jdk-11.0.9_11.1-alpine-slim",
           "type": "docker",
           "networkMode": "bridge",
           "networkName": "mcnetwork",
           "portBindings": [
               "ip:{port}:{port}/tcp"
             }
},
```

**Comment by FriendlyGamer** [comment]
> ```json
>  {
>            "image": "adoptopenjdk/openjdk11:jdk-11.0.9_11.1-alpine-slim",
>            "type": "docker",
>            "networkMode": "bridge",
>            "networkName": "mcnetwork",
>             "ip:{port}:{port}/tcp"
> },
> ```

Awesome thanks, what about if I wanted to add additional port(s) because someone need a port for Dynmap, Plan or whatever plugins that requires additional ports to be assigned? 

Would I make another port variable then after this create another line like this... 
` "ip:{optport}:{optport}/tcp"` 

Under the port bindings? 
If I wanted to assign them another port and so on? 

Thanks very much in advance.

**Comment by LordRalex** [comment]
Variable replacements are not currently supported in this section right now.

**Comment by FriendlyGamer** [comment]
> Variable replacements are not currently supported in this section right now.

So we would need to at the moment create a separate template for EVERY instance since a variable can't be declared in such section?

**Comment by LordRalex** [comment]
No. A template is just that, a template. Once you deploy the server, you can edit the server's json and manually set the value for the port you want.

**Comment by FriendlyGamer** [comment]
> No. A template is just that, a template. Once you deploy the server, you can edit the server's json and manually set the value for the port you want.

Then "install" then it will use it's own json file correct?

**Comment by LordRalex** [comment]
Yes. Templates are only used when you *create* a server. After that, the server's json is the only thing it looks at. It doesn't even know what template was used.

**Comment by FriendlyGamer** [comment]
> Yes. Templates are only used when you _create_ a server. After that, the server's json is the only thing it looks at. It doesn't even know what template was used.

Thanks you very much for helping me understand a temporary solution to this. This seems to be _bearable_ for the near future and _seems to suffice_ for what I need to do in order to be "safe" for subleasing.  

Though I hope this sooner or later gets updated so it's more user friendly in the future.
