### ISSUE TITLE
Security For PufferTeam!!! VERY IMPORTANT!!!!

### ISSUE THREAD

**Issue by MichaelDevC** [PufferPanel/PufferPanel#965]
Hi everyone!
I'm Michael and user and "Web Developer" (Not in the team of PufferPanel).
Today i want to report this very huge security problem to the PufferTeam!

When a user **Login or Change his profile** settings, if you don't use **SSL** all information, also the password, are sent to the daemon without any encryption.... (See the media attached after)

So i want to suggest to make a encryption between daemon and WebUI, for SECURITY REASON!

ps. the string hidden in the screen isn't encrypted -_-

Thx

![ReportForPufferTeam](https://user-images.githubusercontent.com/57275048/103081763-e4deef00-45d8-11eb-824a-314ac5d265d1.jpg)

**Comment by Romitou** [comment]
This is normal and the PufferPanel team can do nothing but recommend the use of SSL as they point out in the documentation.
Just set up a reverse proxy with SSL like anyone else to solve this problem.

**Comment by tommasobenatti** [comment]
Apeuova triggered

**Comment by MichaelDevC** [comment]
That's a scam....
Why not make a ENCRIPTYON.... it's not so difficult

**Comment by Romitou** [comment]
Contributions are welcome in an open source project, so you can do so

**Comment by nepcore** [comment]
There are multiple ways to go about encryption and problems with every one of them, not problems that prevent using a security mechanism, but problems making it hard or even impossible to do so generically for any user

Option 1: RTFM  
This is the current approach  
Expect the user to read the docs and not stumble around the world blindfolded, the docs provide a detailed guide on setting up a reverse proxy to handle TLS termination in a solid and reliable manner  
Making the necessity of using TLS more visible to the unaware by adding a warning box similar to the one @Romitou mentioned to the install page of the docs would probably be a good idea though  
Surely this approach has its own shortcomings in that a user can choose to ignore such a warning and at least to me it seems quite close to impossible to prevent ignoring warnings, but in my opinion, even with its shortcomings, this is the only sane approach I'm aware of

Option 2: Have the integrated webserver do TLS by default  
Sounds like a good idea, right? But that falls short when it comes to certificates, sure, Let's Encrypt offers free certificates, but not every user has a domain and you won't see an authority giving you a cert for an IP, even if they did, PufferPanel has no clue what domain or IP it is running on and couldn't ask for a cert for your domain/IP on its own

Option 3: Build your own transport layer security  
TLS as supported by your average webserver is usually provided through the use of libraries like openssl that are widely used, tested and in case of problems quickly fixed, implementing even just one encryption algorithm on your own to encrypt requests with you expose yourself to bugs in that implementation which are often hard to find or notice plus you need to manage key transfer yourself which can again be subject to bugs plus all the code becomes much more complex and thereby more prone to bugs and harder to maintain, and we haven't even touched on how it is necessary to have a trustable authority in the mix to prevent man in the middle attacks, so this option is completely out of the question

Another thing some might propose is to hash the password on the frontend before sending it out, but that doesn't help with anything as an attacker would still be able to catch whatever is sent to the API and just send a similar request themselves, so this one is dead in the water from the start

And just as a little sidenote: even if your request is sent over HTTPS your browsers devtools will show the unencrypted request as the browser knows what it sent to the server anyways (it does the client side TLS handling after all) and debugging requests with encrypted blobs you don't have the decryption key for is not really helpful

As @Romitou already said, contributions are welcome, so feel free to contribute, be it with a pull request or through pointing out/ discussing how this could be achieved, I'd assume everyone would be excited about a reasonable way of providing encryption in any context, I know I would be, but just yelling "make an encryption" won't get us there
