### ISSUE TITLE
Backup Funktion

### ISSUE THREAD

**Issue by M4RKUS-11111** [PufferPanel/PufferPanel#970]
It would be nice if you could backup server states by just hitting a buton.

Similar to the snapshot fuction you have on VirtualBox

I think this could be done via git or if btrfs is installed via subvolumes witch could be snapshoted

**Comment by M4RKUS-11111** [comment]
Maybe an option for automatic backup at a specified time would be nice, too

**Comment by InflamedSebi** [comment]
There is an issue for backups already.
duplicate of #842

**Comment by M4RKUS-11111** [comment]
Oh, i actually was looking for an existing issue, but maybe I didn't see it.
But I don't think git has been suggested as a versioning option.
