### ISSUE TITLE
Option to edit start konfiguration in server settings

### ISSUE THREAD

**Issue by M4RKUS-11111** [PufferPanel/PufferPanel#971]
Is it possible to add a function to edit the start command for a server in its settings. ( Not only in the templates )?

**Comment by InflamedSebi** [comment]
You can add a variable to the template that is used in the start command of a server. This variable can then be edited in the server setting to adjust the startup command at any time.

**Comment by M4RKUS-11111** [comment]
Ok, thanks for answer
