### ISSUE TITLE
Option to copy/delete a template

### ISSUE THREAD

**Issue by M4RKUS-11111** [PufferPanel/PufferPanel#972]
I is possible to a option to copy a template. ( To create a modified and a normal version of a server)

**Comment by InflamedSebi** [comment]
You can copy templates using the JSON tab (upper right corner) in the template editor, then you can insert the copied json text in the same JSON tab when creating a new template.

deleting is a duplicate of #923

**Comment by M4RKUS-11111** [comment]
Oh, ok nice tipp, but shouldn't it be easy to create a simple function for it?
Or is it planned that you copy the JSON version and paste it into your own if you want to copy it. If so, should I close the issue?

**Comment by InflamedSebi** [comment]
Imo the way it works right now is sufficient. Usually you don't need to copy a template at all. If you have 2 versions of the same template you could do better, by adding options and variables to the original template to make it more dynamic and allow for both uses in one template. And fore those rare cases where you really need to copy, I can handle a little copy pasting.

This whole thing is done by only a few peeps in their free time, so they can't do everything and there are a lot of great feature suggestions/requests I personally would rather love to see implemented than another way of duplicating templates.
 But those are just my 2 cents.

**Comment by M4RKUS-11111** [comment]
Ok, yes you convinced me. (I hope backups will be possible soon)
