### ISSUE TITLE
Option to start / stop specified Server from terminal / crontab etc

### ISSUE THREAD

**Issue by M4RKUS-11111** [PufferPanel/PufferPanel#975]
Is it possible to add a function to start/stop a server via the terminal?

**Comment by InflamedSebi** [comment]
There is an API ( https://speca.io/PufferPanel/pufferd/2.0 ), so in theory you can build a script that triggers the /start and /stop endpoints and run this via cron if needed.
Depending on your usage, there is an option to auto-start a server, whenever it is down, so you might get a way by enabling that option and then just shutting down the server via plugin or any other way.

**Comment by M4RKUS-11111** [comment]
Oh, ok thanks for the answer
