### ISSUE TITLE
Paper CI Auth required - server plugin PaperSpigot - Minecraft 1.14.2

### ISSUE THREAD

**Issue by Nealsch** [PufferPanel/PufferPanel#980]
Hi
New to PufferPanel but picked up an error on PaperSpigot - Minecraft 1.14.2 server plugin.
A few weeks back papermc.io made a change requiring auth to access the required jar and it appears also path changes.

The puffered log will show:
[13:14:21] [DEBUG] Download file from https://papermc.io/ci/job/Paper-1.14/lastSuccessfulBuild/artifact/paperclip.jar to /var/lib/pufferd/servers/0973b0fb-2166-4821-b081-22bbde1c4459
[13:14:21] [ERROR] Error running process: 
server returned 403 Forbidden

Papermc reports the solution here: https://papermc.io/forums/t/paper-ci-auth-required/5928/2
The resolution is to:
#!/bin/sh
# This is identical to the version shown above, except with the added configuration option for a static filename, defaulting to "server.jar"

version=1.16.4 # Set minecraft version here, not build number. Must be full version. 1.16 means 1.16.0, will not correct to 1.16.4
prj="paper" # Set project, this could be paper, waterfall, or travertine
filename="server.jar"
build=$(curl "https://papermc.io/api/v2/projects/${prj}/versions/${version}"| jq '.builds[-1]')
curl -L {https://papermc.io/api/v2/projects/${prj}/versions/${version}/builds/${build}/downloads/${prj}-${version}-${build}.jar} -o ${filename}

**Comment by InflamedSebi** [comment]
Hey, it is working for me with the following adjustments:

1. Got to Templates and and modify your minecraft-paper template.
2. Use the JSON button in the upper right corner to see the textual representation.
3. Look for the "install" section and modify it to look like this:
```
    "install": [
        {
            "target": "download.sh",
            "text": "#!/bin/sh\nprj=\"paper\"\nbuild=$(curl \"https://papermc.io/api/v2/projects/${prj}/versions/${version}\"| jq '.builds[-1]')\ncurl -LO {https://papermc.io/api/v2/projects/${prj}/versions/${version}/builds/${build}/downloads/${prj}-${version}-${build}.jar}",
            "type": "writefile"
        },
        {
            "commands": [
                "chmod u+x download.sh",
                "./download.sh"
            ],
            "type": "command"
        },
        {
            "source": "paper-*.jar",
            "target": "paper.jar",
            "type": "move"
        },
        {
            "target": "server.properties",
            "text": "server-ip=${ip}\nserver-port=${port}\nmotd=${motd}\n",
            "type": "writefile"
        },
        {
            "target": "eula.txt",
            "text": "eula=${eula}",
            "type": "writefile"
        }
    ],
```
So instead of just downloading on the latest branch we create a script like paper wants us to, make it executable and finally run it.
If you made any other customizations  to the install procedure you have to implement them again, since this was derived from the default one.
