### ISSUE TITLE
Errors when login

### ISSUE THREAD

**Issue by lolo773** [PufferPanel/PufferPanel#984]
Hello there,
 It pops up error when i tried to login the panel after installed. It said "Unknown Error".
 
 `{ "message": "Request failed with status code 404", "name": "Error", "fileName": "http://webpanel.xxx.xyz/js/chunk-vendors.80dd09ba.js", "lineNumber": 7, "columnNumber": 79339, "stack": "2d83/t.exports@http://webpanel.innopvp.xyz/js/chunk-vendors.80dd09ba.js:7:79339\n467f/t.exports@http://webpanel.xxx.xyz/js/chunk-vendors.80dd09ba.js:20:57976\nb50d/t.exports/</f.onreadystatechange@http://webpanel.xxx.xyz/js/chunk-vendors.80dd09ba.js:37:44704\n", "config": { "url": "/auth/login", "method": "post", "data": "{\"email\":\"asd\",\"password\":\"<password>\"}", "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/json;charset=utf-8" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 } }`

Please help for the troubleshoot.

**Comment by LordRalex** [comment]
Please use our discord.
