### ISSUE TITLE
[BUG] Filemanager odd sorting.

### ISSUE THREAD

**Issue by InflamedSebi** [PufferPanel/PufferPanel#985]
The Filemanager sorts alphanumerical, but the odd thing is the case sensitivity, so it is sorted like:
Aname
Applepie
Banana
anothername
avocado
bread

I would expect it to sort non case sensitive like:
Aname
anothername
Applepie
avocado
Banana
bread

Maybe there is an easy fix for this, because this is really not intuitive.

**Comment by nepcore** [comment]
It's sorted by codepoint and in UTF-8 you first get all uppercase letters, then a few symbols, then the lowercase letters  
Though it is without question not the most intuitive sorting for the average user  
I just never noticed as everything i tested with always started on lowercase letters
