### ISSUE TITLE
Non Admin users cannot list servers they are added to

### ISSUE THREAD

**Issue by KlutzyBubbles** [PufferPanel/PufferPanel#987]
If i add someone to a server, i have to either give them the permission to list all servers (including ones they dont have access too) or give them a direct link to the server page (which is inconvenient especially when they come back saying they lost the link).

When no server list permissions are given and they have access to a server, the server list page just returns 403.

I believe this is a bug, when a user has access to view / edit anything in a server, it should automatically list at a minimum the servers they have access too

**Comment by thecmdradama** [comment]
Out of curiosity what Database are you using?

**Comment by InflamedSebi** [comment]
"List all servers" means he can only see all servers he is owner of. The title was just misleading. See https://github.com/PufferPanel/PufferPanel/issues/925

So you are supposed to give this permission to them and they do not see all servers but all they own.

**Comment by KlutzyBubbles** [comment]
Hmm, im not sure why that issue you linked is closed, i still think either the permission should be re named or another permission added to fix this.

**Comment by nepcore** [comment]
That issue has been closed as the permission has been renamed, that change will be part of the next release
