### ISSUE TITLE
add valheim

### ISSUE THREAD

**Issue by Smallinger** [PufferPanel/PufferPanel#988]
is it possible to add valheim ?

**Comment by InflamedSebi** [comment]
Since valheim is just another steamcmd server, you can. You would want to make a copy of any steamcmd server template (arma, ark, cs:go, etc...) and just edit it to fit the valheim server requirements.
If you are having trouble doing so, you might want to join the discord for further assistance.

**Comment by Smallinger** [comment]
here is the code for valheim
`{
    "type": "valheim",
    "data": {
        "name": {
            "type": "string",
            "desc": "Choose your servername.",
            "display": "Name",
            "required": true,
            "value": "Valheim Server",
            "userEdit": true
        },
        "password": {
            "type": "string",
            "desc": "Set the server password.",
            "display": "Password",
            "required": true,
            "value": "valheim",
            "userEdit": true
        },
        "port": {
            "type": "integer",
            "desc": "What port to bind the server to",
            "display": "Port",
            "required": true,
            "value": "2456",
            "userEdit": true
        },
        "world": {
            "type": "string",
            "desc": "What worldmap name to use.",
            "display": "World",
            "required": true,
            "value": "VHWorld",
            "userEdit": true
        }
    },
    "display": "Valheim Dedicated Server",
    "environment": {
        "type": "tty"
    },
    "install": [
        {
            "files": [
                "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
            ],
            "type": "download"
        },
        {
            "target": "steamcmd",
            "type": "mkdir"
        },
        {
            "commands": [
                "tar --no-same-owner -xzvf steamcmd_linux.tar.gz -C steamcmd",
                "steamcmd/steamcmd.sh +login anonymous +force_install_dir .. +app_update 896660 +quit",
                "mkdir -p .steam/sdk32",
                "cp steamcmd/linux32/steamclient.so .steam/sdk32/steamclient.so"
            ],
            "type": "command"
        }
    ],
    "run": {
        "command": "./valheim_server.x86_64 -name ${name} -port ${port} -world ${world} -password ${password} -public 1 > /dev/null &",
        "stopCode": 2,
        "environmentVars": {
            "LD_LIBRARY_PATH": "./linux64:$LD_LIBRARY_PATH",
            "SteamAppId": "892970",
            "templdpath": "$LD_LIBRARY_PATH"
        },
        "pre": [],
        "post": []
    },
    "supportedEnvironments": [
        {
            "type": "tty"
        },
        {
            "image": "pufferpanel/srcds",
            "type": "docker"
        }
    ],
    "name": "Valheim"
}`

**Comment by thecmdradama** [comment]
@Smallinger you should make a PR for it https://github.com/PufferPanel/templates/pulls. It won't be added to the templates otherwise.
