### ISSUE TITLE
Fedora repository not working

### ISSUE THREAD

**Issue by bitrot-alpha** [PufferPanel/PufferPanel#999]
OS: Fedora 33

I tried to use `script.rpm.sh` to install Pufferpanel, but when I run `sudo dnf install pufferpanel`, it gives the error `Unable to find a match: pufferpanel` I tried to open https://packagecloud.io/pufferpanel/pufferpanel/fedora/33/x86_64/ in my browser, but nothing shows up, not even a directory listing (don't know if it's supposed to be accessed from a web browser..)

The script ran successfully, it added pufferpanel's `.repo` files to `/etc/yum.repos.d`, but I'm not getting anything out of `dnf repository-packages pufferpanel_pufferpanel list`

Should I report this to PackageCloud?

Thanks for the read.

**Comment by MrSherish** [comment]
+1, I have exactly same problem on Fedora 33 Server

**Comment by LordRalex** [comment]
This isn't a packagecloud issue. We do not push our packages to a Fedora repo. I've manually added a Fedora 33 package for it.
